import Image from 'next/image';
import { products } from '@/lib/site-data';
import { BrandFilters, ProductDetails } from './brands-client';
import { FAQ } from './site-client';

const shop='https://smartstore.naver.com/gucmall';
const details:Record<string,{name?:string;category:string;type:string;use:string;gmk:string;amount:string;ingredients:string;method:string;storage:string;caution:string;maker?:string;reportName?:string}>={
 'premium-gift':{name:'기운찬 本',category:'매일의 영양 선물하기',type:'기타가공품',use:'매일 간편하게 챙기거나 선물하기 좋은 분말제품',gmk:'GMK® 원료 사용',amount:'120g (2g × 60포)',ingredients:'GMK® 분말, 꽃송이버섯분말, 치커리뿌리추출물분말, 비타민·미네랄 원료 등',method:'1일 1~2회, 1회 1포를 물과 함께 섭취합니다.',storage:'직사광선과 고온다습한 곳을 피해 보관합니다.',caution:'알레르기 체질이거나 특정 원료에 민감한 경우 원재료명을 확인하세요.',reportName:'기운찬'},
 'grape-jelly':{category:'매일의 식탁',type:'기타가공식품',use:'샤인머스캣 맛을 스틱으로 간편하게 즐기는 젤리',gmk:'GMK® 원료 사용',amount:'200g (20g × 10포)',ingredients:'정제수, 프락토올리고당, 샤인머스캣 혼합농축액 등',method:'성인은 하루 1~3포를 섭취하고, 어린이는 보호자가 포장을 제거한 뒤 이용합니다.',storage:'직사광선을 피해 실온 보관하며, 차갑게 보관하면 더욱 시원하게 즐길 수 있습니다.',caution:'어린이가 포장재를 직접 삼키지 않도록 보호자가 확인하세요.'},
 'immune-mk':{category:'매일의 영양',type:'건강기능식품',use:'비타민과 미네랄을 하루 섭취량에 맞춰 챙기는 캡슐 제품',gmk:'GMK® 원료 사용',amount:'48g (400mg × 120캡슐)',ingredients:'비타민C, 아연, 셀렌, 비타민D, 비타민B6·B2·B1, GMK® 원료 등',method:'1일 1회, 1회 4캡슐을 물과 함께 섭취합니다.',storage:'직사광선과 고온다습한 곳을 피해 보관합니다.',caution:'특정 원료에 알레르기가 있거나 의약품을 복용 중인 경우 원재료와 주의사항을 확인하세요.'},
 'giunchan-drink':{category:'마시는 일상',type:'혼합음료',use:'부담 없이 바로 마실 수 있는 340mL 병 음료',gmk:'GMK® 원료 사용',amount:'340mL',ingredients:'정제수, 기운찬버섯GMK 등',method:'개봉 후 바로 음용하며 차갑게 또는 따뜻하게 즐길 수 있습니다.',storage:'직사광선을 피해 실온 보관하고 개봉 후에는 바로 드세요.',caution:'용기가 변형되거나 내용물에 이상이 있는 경우 섭취하지 마세요.'},
 'giuncha-extract':{category:'마시는 일상',type:'혼합음료',use:'취향에 따라 농도를 조절해 마시는 500mL 원액형 음료',gmk:'GMK® 원료 사용',amount:'500mL',ingredients:'기운찬버섯GMK, 보리차 베이스 원료 등',method:'원하는 농도로 물에 희석해 음용합니다.',storage:'직사광선을 피해 보관하고 개봉 후에는 냉장 보관합니다.',caution:'원재료와 실제 포장의 최신 섭취 안내를 확인하세요.'},
 'mushroom-tea':{category:'마시는 일상',type:'침출차',use:'티백 하나로 따뜻하거나 시원하게 즐기는 버섯차',gmk:'GMK® 원료 사용',amount:'12g (0.8g × 15티백)',ingredients:'차가버섯, 상황버섯, 영지버섯 원료 등 제품 표시사항 기재 원료',method:'티백 1개를 적당한 온도의 물에 충분히 우린 뒤 마십니다. 냉침으로도 이용할 수 있습니다.',storage:'직사광선과 고온다습한 곳을 피해 보관합니다.',caution:'개별 버섯 원료 표기는 이 완제품의 원재료 정보이며 GMK®의 제조 구성을 의미하지 않습니다.'},
 'mushroom-tea-gift':{category:'마시는 일상 선물하기',type:'침출차 선물 구성',use:'버섯마시면기운차를 선물용 패키지에 담은 구성',gmk:'GMK® 원료 사용',amount:'버섯마시면기운차 선물 구성',ingredients:'버섯마시면기운차 단품과 동일한 표시 원재료',method:'티백 1개를 물에 충분히 우려 따뜻하게 또는 차갑게 이용합니다.',storage:'직사광선과 고온다습한 곳을 피해 보관합니다.',caution:'구성품 수량과 쇼핑백 포함 여부는 공식 판매처의 최신 정보를 확인하세요.'},
 'mushroom-spoon':{category:'매일의 식탁',type:'기타가공품',use:'밥이나 요리에 한 스푼씩 더하는 세 가지 분말 제품',gmk:'GMK® 원료 사용',amount:'각 50g',ingredients:'밥할 때, 밥할 때 홍국, 요리할 때 제품별 표시 원재료',method:'밥 또는 요리 3~4인분 기준 한 스푼을 넣어 사용합니다.',storage:'직사광선과 고온다습한 곳을 피해 보관하고 사용 후 밀봉합니다.',caution:'세부 원재료와 알레르기 정보는 각 제품 포장의 최신 표시사항을 확인하세요.',maker:'주식회사 기운찬 자체 생산'},
};
const ordered=['premium-gift','grape-jelly','immune-mk','giunchan-drink','giuncha-extract','mushroom-tea','mushroom-tea-gift','mushroom-spoon'];
const brandFaq=[
 {q:'도두On은 어떤 브랜드인가요?',a:'도두On은 주식회사 기운찬이 운영하는 소비자 브랜드입니다. 기운찬이 연구·개발한 GMK® 원료를 차·음료·분말·젤리·건강기능식품 등 일상의 제품으로 연결합니다.'},
 {q:'도두On이라는 이름은 어떤 의미인가요?',a:'도두On은 기운과 건강을 북돋운다는 우리말 ‘돋우다’에서 시작됐습니다. ‘On’에는 건강한 일상 습관을 켠다는 의미와 온(溫)의 따뜻함을 담았습니다.'},
 {q:'기운찬과 도두On은 어떤 관계인가요?',a:'기운찬은 GMK® 원료를 연구·개발하는 기업이고, 도두On은 그 원료로 만든 소비자 제품을 하나의 체계로 연결하는 기운찬의 소비자 브랜드입니다.'},
 {q:'GMK®는 제품 이름인가요?',a:'GMK®는 완제품명이 아니라 기운찬이 개발한 복합버섯균사체 원료 브랜드입니다. 소비자는 GMK® 원료가 사용된 제품을 도두On 브랜드에서 만날 수 있습니다.'},
 {q:'모든 도두On 제품에 GMK®가 들어 있나요?',a:'모든 도두On 제품에는 제품 특성에 따라 GMK®, GMK® 추출액 또는 GMK® 추출물이 사용됩니다. 정확한 사용 형태는 각 제품의 상세정보에서 확인할 수 있습니다.'},
 {q:'제품 포장에 도두On 로고가 없는 제품도 있나요?',a:'일부 기존 제품은 도두On 브랜드 체계가 정립되기 전에 개발돼 현재 패키지에 도두On 로고가 표시되지 않을 수 있습니다. 패키지는 제품별 생산과 리뉴얼 일정에 따라 순차적으로 변경됩니다.'},
 {q:'기운찬 本은 어떤 제품인가요?',a:'기운찬 本은 2015년 처음 출시된 기운찬의 시그니처 분말제품입니다. 품목제조보고상 제품명은 ‘기운찬’이며, 현재는 회사의 근본 제품이라는 의미를 담아 ‘기운찬 本’으로 소개하고 있습니다.'},
 {q:'도두On 제품은 어디에서 구매할 수 있나요?',a:'도두On 제품은 기운찬 공식 네이버 스마트스토어에서 구매할 수 있습니다. 제품별 구매 버튼을 통해 공식 판매페이지로 이동할 수 있습니다.'},
 {q:'제품의 원재료와 섭취방법은 어디에서 확인하나요?',a:'제품별 원재료, 내용량, 섭취방법과 주의사항은 이 페이지의 제품 상세정보와 실제 제품 포장의 최신 표시사항에서 확인할 수 있습니다.'},
];
function Product({slug}:{slug:string}){const base=products.find(p=>p.slug===slug)!;const d=details[slug];const name=d.name||base.name;return <article id={slug==='premium-gift'?'giunchan-bon':slug} className="brand-product" data-category={d.category}><Image src={base.image} alt={`${name} 실제 제품 패키지`} width={760} height={570} unoptimized/><div className="brand-product-copy"><small>{d.category.replace(' 선물하기','')} · {d.type}</small><h3>{name}</h3><p>{d.use}</p><dl className="brand-product-facts"><div><dt>사용 원료</dt><dd>{d.gmk}</dd></div><div><dt>내용량</dt><dd>{d.amount}</dd></div></dl><div className="brand-product-actions"><a href={shop} target="_blank" rel="noreferrer" aria-label={`${name} 공식 스토어에서 구매하기, 새 창`}>구매하기 ↗</a></div><ProductDetails id={slug==='premium-gift'?'giunchan-bon':slug}><dl className="brand-detail-list"><div><dt>주요 원재료</dt><dd>{d.ingredients}</dd></div><div><dt>이용방법</dt><dd>{d.method}</dd></div><div><dt>보관방법</dt><dd>{d.storage}</dd></div><div><dt>주의사항</dt><dd>{d.caution}</dd></div>{d.maker&&<div><dt>제조</dt><dd>{d.maker}</dd></div>}{d.reportName&&<><div><dt>소비자 브랜드명</dt><dd>기운찬 本</dd></div><div><dt>품목제조보고 제품명</dt><dd>{d.reportName}</dd></div></>}</dl><p className="brand-legal">원재료, 영양정보, 섭취방법과 주의사항은 실제 제품 포장의 최신 표시사항을 우선해 확인해 주세요.</p></ProductDetails></div></article>}
export function BrandsPage(){return <main className="brands-onepage"><section className="brands-hero"><Image src="/assets/product-premium.webp" alt="" fill priority unoptimized/><div className="brands-hero-shade"/><div className="shell"><small>DODOON BRAND</small><h1>매일, 건강을 돋우다</h1><p>도두On은 기운찬이 연구·개발한 GMK® 원료를 일상에서 부담 없이 먹고 마실 수 있는 제품으로 연결하는 소비자 브랜드입니다.</p><div><a className="button light" href="#products">도두On 제품 보기</a><a className="button ghost" href={shop} target="_blank" rel="noreferrer">공식 스토어 바로가기 ↗</a></div></div></section><div className="shell brand-sections">
 <section className="brand-story-new"><div><small>BRAND STORY</small><h2>‘돋우다’에서 시작된 이름, 도두On</h2><p>도두On은 우리말 ‘돋우다’에서 시작된 이름입니다. 건강과 기운을 북돋우는 의미에, 일상의 건강한 습관을 켠다는 ‘On’과 온(溫)의 따뜻함을 더했습니다.</p><p>기운찬이 연구와 원료를 책임진다면, 도두On은 그 원료를 맛과 형태, 섭취 편의성을 고려한 일상의 제품으로 전합니다.</p></div><Image src="/assets/dodoon-official-logo.jpg" alt="도두On 브랜드 로고" width={520} height={640} unoptimized/><div className="brand-name-meanings">{[['돋우다','기운과 일상을 북돋우다'],['On','건강한 일상 습관을 켜다'],['온(溫)','따뜻하게 이어가는 건강']].map(([t,c])=><article key={t}><h3>{t}</h3><p>{c}</p></article>)}</div></section>
 <section><small>FROM RESEARCH TO LIFE</small><h2>연구한 원료가 일상의 제품이 되기까지</h2><p>기운찬은 특허기술을 기반으로 GMK® 원료를 연구·개발하고, 도두On을 통해 그 원료를 일상에서 먹고 마실 수 있는 제품으로 연결합니다.</p><ol className="brand-flow">{[['주식회사 기운찬','특허기술과 연구개발'],['GMK®','기운찬이 개발한 복합버섯균사체 B2B 원료 브랜드'],['도두On','GMK® 원료를 활용한 기운찬의 소비자 브랜드'],['도두On 제품','차·음료·분말·젤리·건강기능식품 등 실제 판매제품']].map(([t,c],i)=><li key={t}><span>0{i+1}</span><h3>{t}</h3><p>{c}</p></li>)}</ol><a className="text-link" href="/technology">기운찬 기술 보기 →</a></section>
 <section><small>OUR VALUES</small><h2>도두On이 제품을 만드는 기준</h2><div className="brand-values-new">{[['정직하게 설명하는 건강','사용한 원료와 제품 정보를 확인 가능한 범위에서 정확하고 이해하기 쉽게 설명합니다.'],['매일 이어가는 건강','부담 없이 반복할 수 있도록 맛과 형태, 섭취방법과 휴대 편의성을 함께 고민합니다.'],['사람의 일상을 생각하는 건강','성분을 나열하는 데 그치지 않고, 누가 언제 어떻게 제품을 이용할지를 먼저 생각합니다.']].map(([t,c],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{c}</p></article>)}</div></section>
 <section className="brand-categories"><small>DAILY CATEGORIES</small><h2>오늘의 생활에 맞는 제품 찾기</h2><div>{[['마시는 일상','음료나 차 형태로 일상에서 간편하게 즐길 수 있는 제품입니다.'],['매일의 식탁','간식이나 식사에 자연스럽게 더할 수 있도록 맛과 사용 편의성을 고려한 제품입니다.'],['매일의 영양','일상에서 꾸준히 챙길 수 있도록 영양과 섭취 편의성을 고려한 제품입니다.'],['선물하기','마음을 전하기 좋은 제품 구성을 모았습니다.']].map(([t,c])=><article key={t}><h3>{t}</h3><p>{c}</p></article>)}</div></section>
 <section className="signature-product"><Image src="/assets/product-gift.webp" alt="기운찬 本 시그니처 분말제품 패키지" width={900} height={680} unoptimized/><div><small>SIGNATURE PRODUCT · SINCE 2015</small><h2>기운찬 本</h2><h3>2015년부터 이어온 기운찬의 시그니처 분말제품</h3><p>기운찬 本은 2015년 ‘차가품은 버섯’이라는 이름으로 처음 출시된 기운찬의 첫 제품입니다. 2017년 회사명과 같은 ‘기운찬’으로 이름을 바꾸었고, 지금은 회사의 시작과 연구철학을 담은 근본 제품이라는 의미에서 ‘기운찬 本’으로 소개하고 있습니다.</p><p>‘本’에는 기운찬의 첫 제품에서 이어져 온 회사의 근본이라는 의미와, 건강한 일상은 기본적인 식생활과 꾸준한 생활관리에서 시작된다는 생각을 담았습니다.</p><ul><li>1포 2g · 총 60포</li><li>30포씩 두 개의 내부 상자</li><li>GMK® 분말 사용</li></ul><div className="inline-actions"><a className="button orange" href="#giunchan-bon">제품 정보 보기</a><a className="text-link" href={shop} target="_blank" rel="noreferrer">공식 스토어에서 구매 ↗</a><a className="text-link" href="/technology">GMK® 연구 보기 →</a></div><p className="brand-legal">연결된 연구자료는 특정 연구용 시료와 연구모델에 관한 것으로, 기운찬 本 완제품의 질병 예방·치료 또는 기능성을 의미하지 않습니다.</p></div></section>
 <section id="products"><small>ALL PRODUCTS</small><h2>현재 판매 중인 도두On 제품</h2><p>모든 도두On 제품에는 제품의 특성에 따라 GMK®, GMK® 추출액 또는 GMK® 추출물이 사용됩니다.</p><BrandFilters/><div className="brand-product-list">{ordered.map(slug=><Product slug={slug} key={slug}/>)}</div></section>
 <section className="brand-shop"><small>OFFICIAL STORE</small><h2>도두On 제품을 공식 판매처에서 만나보세요</h2><p>도두On 제품은 기운찬 공식 네이버 스마트스토어에서 구매할 수 있습니다. 판매가격, 배송과 재고정보는 공식 판매처의 최신 정보를 확인해 주세요.</p><a className="button light" href={shop} target="_blank" rel="noreferrer">기운찬 공식 스마트스토어 ↗</a></section>
 <section><small>PRACTICAL GUIDE</small><h2>도두On 자주 묻는 질문</h2><FAQ items={brandFaq}/></section>
 </div></main>}
