import Image from 'next/image';
import {publicProductFacts} from '@/lib/facts/products';
import {gmkDefinition} from '@/lib/facts/research';
import {BrandFilters,ProductDetails} from './brands-client';
import {FAQ} from './site-client';
const shop='https://smartstore.naver.com/gucmall';
const brandFaq=[{q:'도두On은 어떤 브랜드인가요?',a:'도두On은 주식회사 기운찬이 운영하는 소비자 브랜드입니다. 연구한 원료와 식품개발 경험을 일상에서 이용하기 쉬운 제품으로 연결합니다.'},{q:'GMK®는 제품 이름인가요?',a:`${gmkDefinition} GMK®는 소비자 완제품명이 아닙니다.`},{q:'모든 제품에 같은 GMK® 원료가 사용되나요?',a:'제품에 적용된 원료와 형태는 제품별 표시사항을 기준으로 확인해야 합니다. 연구자료의 결과를 개별 판매제품의 효능으로 연결하지 않습니다.'},{q:'제품은 어디에서 구매할 수 있나요?',a:'기운찬 공식 네이버 스마트스토어에서 판매가격, 배송과 재고를 확인할 수 있습니다.'}];
function Product({slug}:{slug:string}){const item=publicProductFacts.find(product=>product.slug===slug)!;const rows=[['식품유형',item.foodType],['제품 구분',item.classification],['내용량',item.amount],['GMK® 적용',item.gmk],['적용 원료 형태',item.ingredientForm],['제조원',item.manufacturer],['판매원',item.seller],['이용방법',item.method],['알레르기 정보',item.allergen],['보관방법',item.storage]].filter((row):row is string[]=>Boolean(row[1]));return <article id={slug} className="brand-product" data-category={item.category}><Image src={item.image} alt={`${item.name} 제품 이미지`} width={760} height={570} unoptimized/><div className="brand-product-copy"><small>{item.category} · {item.classification}</small><h3>{item.name}</h3><p>{item.summary}</p><dl className="brand-product-facts"><div><dt>식품유형</dt><dd>{item.foodType}</dd></div><div><dt>내용량</dt><dd>{item.amount}</dd></div></dl><div className="brand-product-actions"><a href={shop} target="_blank" rel="noreferrer" aria-label={`${item.name} 공식 스토어에서 구매하기, 새 창`}>구매하기 ↗</a></div><ProductDetails id={slug}><dl className="brand-detail-list">{rows.map(([label,value])=><div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><p className="brand-legal">제품 정보는 제공된 표시사항을 기준으로 정리했습니다. 실제 제품 포장의 최신 표시사항을 우선해 확인해 주세요.</p></ProductDetails></div></article>}
export function BrandsPage(){return <main className="brands-onepage"><section className="brands-hero"><Image src="/assets/product-premium.webp" alt="" fill priority unoptimized/><div className="brands-hero-shade"/><div className="shell"><small>DODOON BRAND</small><h1>매일, 건강을 돋우다</h1><p>도두On은 주식회사 기운찬의 소비자 브랜드로, 연구한 원료와 식품개발 경험을 일상의 제품으로 연결합니다.</p><div><a className="button light" href="#products">제품 보기</a><a className="button ghost" href={shop} target="_blank" rel="noreferrer">공식 스토어 ↗</a></div></div></section><div className="shell brand-sections">
<section className="brand-story-new"><div><small>BRAND STORY</small><h2>‘돋우다’에서 시작된 이름, 도두On</h2><p>건강과 기운을 북돋우는 의미에 일상의 건강한 습관을 켠다는 ‘On’과 온(溫)의 따뜻함을 더했습니다.</p></div><Image src="/assets/dodoon-official-logo.jpg" alt="도두On 브랜드 로고" width={520} height={640} unoptimized/><div className="brand-name-meanings">{[['돋우다','기운과 일상을 북돋우다'],['On','건강한 일상 습관을 켜다'],['온(溫)','따뜻하게 이어가는 건강']].map(([t,c])=><article key={t}><h3>{t}</h3><p>{c}</p></article>)}</div></section>
<section><small>FROM RESEARCH TO LIFE</small><h2>연구한 원료가 일상의 제품이 되기까지</h2><p>{gmkDefinition} 도두On은 원료와 완제품을 구분하고 제품별 표시사항에 맞춰 정보를 안내합니다.</p><ol className="brand-flow">{[['주식회사 기운찬','연구개발과 원료사업'],['GMK®','복합버섯균사체 기본 원료'],['도두On','기운찬의 소비자 브랜드'],['판매제품','제품별 표시사항에 따른 식품']].map(([t,c],i)=><li key={t}><span>0{i+1}</span><h3>{t}</h3><p>{c}</p></li>)}</ol><a className="text-link" href="/technology">기운찬 기술 보기 →</a></section>
<section className="signature-product"><Image src="/assets/product-gift.webp" alt="기운찬 분말 제품" width={900} height={680} unoptimized/><div><small>SIGNATURE PRODUCT</small><h2>기운찬</h2><p>공식 제품명은 ‘기운찬’입니다. 식품유형, 내용량, 제조원과 알레르기 정보는 아래 제품정보와 실제 포장에서 확인할 수 있습니다.</p><ul><li>기타가공품</li><li>120g (2g × 60포)</li><li>GMK® 분말 적용</li></ul><div className="inline-actions"><a className="button orange" href="#premium-gift">제품 정보 보기</a><a className="text-link" href={shop} target="_blank" rel="noreferrer">공식 스토어 ↗</a></div><p className="brand-legal">GMK® 관련 연구자료는 개별 판매제품의 기능성이나 질병 예방·치료 효과를 의미하지 않습니다.</p></div></section>
<section id="products"><small>ALL PRODUCTS</small><h2>현재 판매 중인 8개 제품군</h2><p>제품별 식품유형과 GMK® 적용 여부는 각 표시사항을 기준으로 구분합니다.</p><BrandFilters/><div className="brand-product-list">{publicProductFacts.map(item=><Product slug={item.slug} key={item.slug}/>)}</div></section>
<section className="brand-shop"><small>OFFICIAL STORE</small><h2>공식 판매처에서 확인하세요</h2><p>판매가격, 배송과 재고정보는 기운찬 공식 네이버 스마트스토어의 최신 정보를 확인해 주세요.</p><a className="button light" href={shop} target="_blank" rel="noreferrer">기운찬 공식 스마트스토어 ↗</a></section><section><small>PRACTICAL GUIDE</small><h2>도두On 자주 묻는 질문</h2><FAQ items={brandFaq}/></section></div></main>}
