import Image from 'next/image';
import {notFound} from 'next/navigation';
import {ContentExplorer} from './content-explorer';
import {findContent,publishedInsights,publishedNews,type ContentEntry} from '@/lib/content-data';

const insightCategories=['전체','GMK® 이해','버섯과 균사체','원료 이야기','연구 쉽게 읽기','식품과 제품'];
const newsCategories=['전체','기업소식','연구성과','특허·인증','제품·브랜드','사업·협력','사회공헌','보도자료'];
function Crumbs({type,title}:{type:'insight'|'newsroom';title?:string}){return <nav className="content-breadcrumb" aria-label="현재 위치"><a href="/">HOME</a><span>/</span><a href={`/${type}`}>{type==='insight'?'INSIGHT':'NEWSROOM'}</a>{title&&<><span>/</span><span>{title}</span></>}</nav>}
function Listing({type}:{type:'insight'|'newsroom'}){const isInsight=type==='insight';const entries=isInsight?publishedInsights:publishedNews;return <main className={`content-hub ${type}-hub`}><header className="content-hero"><div className="shell"><Crumbs type={type}/><small>{isInsight?'GIUNCHAN INSIGHT':'GIUNCHAN NEWSROOM'}</small><h1>{isInsight?'GMK®와 버섯균사체를 이해하는 지식 아카이브':'기운찬의 연구와 사업 소식'}</h1><p>{isInsight?'기운찬의 원료와 연구, 버섯균사체와 식품 관련 개념을 질문 중심으로 쉽고 정확하게 설명합니다.':'연구성과, 특허, 제품과 브랜드, 사업협력 및 지역사회 활동을 날짜와 사실 중심으로 전합니다.'}</p></div></header><div className="shell content-hub-body"><ContentExplorer entries={entries} type={type} categories={isInsight?insightCategories:newsCategories}/><aside className="content-disclaimer">{isInsight?'인사이트의 내용은 버섯균사체와 식품·연구 관련 정보를 이해하기 쉽게 설명하기 위한 일반 정보입니다. 특정 제품의 질병 예방·치료 또는 개인별 건강상태에 대한 의학적 조언을 의미하지 않습니다.':'뉴스룸은 발표 당시의 연구·사업 현황과 기운찬의 공식 활동을 기록합니다. 과거 기사에 포함된 개발단계와 명칭은 현재 상태와 다를 수 있으므로 각 글의 최종 수정일과 현재 상태를 함께 확인해 주세요.'}</aside></div></main>}
function FactBox({entry}:{entry:ContentEntry}){const facts=[['원 보도 제목',entry.originalTitle],['언론사',entry.publisher],['기자',entry.reporter],['보도일',entry.publishedAt],['소식 유형',entry.category],['관련 기관',entry.relatedOrganizations?.join(', ')],['관련 원료',entry.relatedMaterial],['연구단계',entry.researchStage],['당시 상태',entry.pastStatus],['현재 상태',entry.currentStatus]];return <aside className="content-factbox" aria-label="기사 사실정보"><h2>팩트박스</h2><dl>{facts.filter(([,v])=>v).map(([k,v])=><div key={k}><dt>{k}</dt><dd>{v}</dd></div>)}</dl></aside>}
function Related({entry,entries}:{entry:ContentEntry;entries:ContentEntry[]}){const related=entries.filter(x=>x.slug!==entry.slug&&(x.category===entry.category||x.relatedEntities.some(v=>entry.relatedEntities.includes(v)))).slice(0,3);return <section className="content-related"><h2>관련 콘텐츠</h2><div>{related.map(x=><a key={x.slug} href={`/${x.contentType}/${x.slug}`}><small>{x.category}</small><b>{x.title}</b><span>읽기 →</span></a>)}</div><nav aria-label="관련 페이지"><a href="/technology/publications">연구논문</a><a href="/technology/patents">특허</a>{entry.researchStage==='인체적용시험'&&<a href="/technology/clinical-study">인체적용시험</a>}<a href="/business/ingredient">GMK® 원료</a><a href="/brands">소비자 제품</a></nav></section>}
function Detail({entry}:{entry:ContentEntry}){const list=entry.contentType==='insight'?publishedInsights:publishedNews;const index=list.findIndex(x=>x.slug===entry.slug);const prev=list[index-1],next=list[index+1];const isInsight=entry.contentType==='insight';return <main className={`content-detail ${entry.contentType}-detail`}><div className="shell"><Crumbs type={entry.contentType} title={entry.title}/><article><header><span>{entry.category}</span><h1>{entry.title}</h1><p className="content-answer">{entry.answer}</p><div className="content-meta"><time dateTime={entry.publishedAt}>작성 {entry.publishedAt.replaceAll('-','.')}</time><time dateTime={entry.updatedAt}>최종 수정 {entry.updatedAt.replaceAll('-','.')}</time><span>{isInsight?'작성':'제공'} · {entry.author}</span><span>{isInsight?'자료 검토':'사실 확인'} · {entry.reviewer}</span><span>{entry.readingTime}분 읽기</span></div></header><Image className="content-cover" src={entry.thumbnail} alt={entry.thumbnailAlt} width={1200} height={675} priority unoptimized/><div className="content-article-grid"><aside className="content-toc"><b>목차</b>{entry.sections.map((s,i)=><a key={s.title} href={`#section-${i+1}`}>{s.title}</a>)}</aside><div className="content-prose">{!isInsight&&<FactBox entry={entry}/>} {entry.sections.map((s,i)=><section id={`section-${i+1}`} key={s.title}><h2>{s.title}</h2><p>{s.body}</p></section>)}{isInsight&&<><section className="content-summary"><h2>핵심 요약</h2><p>{entry.answer}</p></section>{entry.terms?.length&&<section><h2>용어 정리</h2><dl className="term-list">{entry.terms.map(x=><div key={x.term}><dt>{x.term}</dt><dd>{x.definition}</dd></div>)}</dl></section>}</>}<section><h2>참고자료와 출처</h2><ul className="source-list">{entry.sourceLinks.map(x=><li key={x.url}><a href={x.url} target="_blank" rel="noreferrer">{x.label} ↗</a></li>)}{entry.legacyUrl&&<li><a href={entry.legacyUrl} target="_blank" rel="noreferrer">기존 기운찬 뉴스룸 아카이브 ↗</a></li>}{!entry.sourceLinks.length&&!entry.legacyUrl&&<li><a href="/technology">기운찬 기술·연구개발 자료</a></li>}</ul></section><aside className="content-note">{entry.disclaimer||(isInsight?'이 글은 일반적인 개념 설명이며 개별 제품의 기능성이나 의학적 조언을 의미하지 않습니다.':'원 보도의 표현과 현재 공식 설명을 구분해 확인해 주세요.')}</aside></div></div><Related entry={entry} entries={list}/><nav className="content-prev-next" aria-label="이전 글과 다음 글">{prev?<a href={`/${prev.contentType}/${prev.slug}`}><small>이전 글</small><b>{prev.title}</b></a>:<span/>}{next&&<a href={`/${next.contentType}/${next.slug}`}><small>다음 글</small><b>{next.title}</b></a>}</nav></article></div></main>}
export function ContentPage({path}:{path:string}){if(path==='/insight')return <Listing type="insight"/>;if(path==='/newsroom')return <Listing type="newsroom"/>;const entry=findContent(path);if(!entry)notFound();return <Detail entry={entry}/>}
