import Image from 'next/image';
import { getHeroImages } from '@/lib/hero-images';
import { notFound } from 'next/navigation';
import { ArrowRight } from 'lucide-react';
import { Header, FAQ, ContactForm } from './site-client';
import { BrandsPage } from './brands-page';
import { ContentPage } from './content-pages';
import { companyDefinition, contactHref, inquiryHref, insights, news, pages, products, type PageInfo } from '@/lib/site-data';
import {publicProductFacts} from '@/lib/facts/products';
import {
 clinicalStudyPublic,
 gmkDefinition,
 gmkResearchStatement,
 ipRegistrationSummary,
 patentPortfolio,
 publicPatentRecords,
 publicIngredientForms,
 publicPublications,
 researchDisclaimer,
} from '@/lib/facts/research';

const shop='https://smartstore.naver.com/gucmall';
function Photo({src,alt,className='',priority=false}:{src:string;alt:string;className?:string;priority?:boolean}) {
 return <Image src={src} alt={alt} width={1920} height={1080} className={className} priority={priority} unoptimized/>;
}
function Button({href,children,tone='dark'}:{href:string;children:React.ReactNode;tone?:'dark'|'light'|'orange'|'ghost'}) {return <a className={'button '+tone} href={href}>{children}<ArrowRight size={16}/></a>}
function SectionHeader({eyebrow,title,copy,align='left'}:{eyebrow:string;title:string;copy?:string;align?:'left'|'split'}) {return <div className={'section-title section-title--'+align}><small>{eyebrow}</small><h2>{title}</h2>{copy&&<p>{copy}</p>}</div>}
const Title=SectionHeader;
function ImageTextSplit({image,alt,children,reverse=false,className=''}:{image:string;alt:string;children:React.ReactNode;reverse?:boolean;className?:string}){return <div className={'image-text-split '+(reverse?'is-reverse ':'')+className}><div className="image-text-split__media"><Photo src={image} alt={alt}/></div><div className="image-text-split__body">{children}</div></div>}
function ProcessInfographic({steps,label}:{steps:readonly (readonly [string,string])[];label:string}){return <ol className="process-infographic" aria-label={label}>{steps.map(([title,description],index)=><li key={title}><span aria-hidden="true">{String(index+1).padStart(2,'0')}</span><div><h3>{title}</h3><p>{description}</p></div></li>)}</ol>}
function ProductCard({item,feature=false}:{item:(typeof products)[number];feature?:boolean}){const content=<><Photo src={item.image} alt={`${item.name} 제품 이미지`}/><div><small>도두On PRODUCT</small><h3>{item.name}</h3><p>{item.summary}</p>{feature&&<dl className="product-facts"><div><dt>제품 유형</dt><dd>음료</dd></div><div><dt>브랜드</dt><dd>도두On</dd></div><div><dt>개발사</dt><dd>주식회사 기운찬</dd></div><div><dt>구매 안내</dt><dd>공식 쇼핑몰</dd></div></dl>}{feature?<><a className="text-link product-detail-link" href={'/brands/dodoon/products/'+item.slug}>제품 자세히 보기 <ArrowRight size={16}/></a><a className="button dark product-all-link" href="/brands/dodoon/products">도두On 제품 전체 보기 <ArrowRight size={16}/></a></>:<span>제품 보기 <ArrowRight size={16}/></span>}</div></>;return feature?<article className="product-card is-feature">{content}</article>:<a className="product-card" href={'/brands/dodoon/products/'+item.slug}>{content}</a>}
function ArticleCard({item,feature=false}:{item:(typeof insights)[number];feature?:boolean}){return <article className={'editorial-card '+(feature?'is-feature':'')}><Photo src={item.image} alt=""/><div><small>{item.category}</small><h3>{item.title}</h3><p>{item.desc}</p><time dateTime={item.date}>{item.date}</time><a className="text-link" href={item.href}>{item.linkLabel} <ArrowRight size={16}/></a></div></article>}
function Footer(){return <footer><div className="shell footer-grid"><div><Photo src="/assets/giunchan-logo-trimmed.png" alt="주식회사 기운찬"/><p>주식회사 기운찬<br/>Giunchan Co., Ltd.</p></div><div><b>CONTACT</b><p>충남 천안시 동남구 충절로 252, 2F<br/>T 041-579-2203 · F 041-585-2203</p><a href="mailto:guc2203@guc.co.kr">guc2203@guc.co.kr</a></div><div><b>COMPANY</b><a href="/company#information">회사 기본정보</a><a href="/company#location">오시는 길</a><a href="/privacy">개인정보 안내</a></div><div><Button href={contactHref}>문의하기</Button><a href={shop} target="_blank" rel="noreferrer">공식 쇼핑몰 ↗</a></div></div><div className="shell copyright">© 2026 Giunchan Co., Ltd. All rights reserved.</div></footer>}
function Layout({children}:{children:React.ReactNode}){return <><Header/>{children}<Footer/></>}
function Hero({section,title,lead,image:_image,home=false,path='/'}:PageInfo&{home?:boolean;path?:string}){const hero=getHeroImages(path);const businessActions=path==='/business'?[['/business/ingredient','GMK® 원료 협력'],['/business/product-development','제품개발 상담']]:path==='/business/ingredient'?[[inquiryHref('GMK® 원료 공급'),'원료 상담하기'],[inquiryHref('원료 샘플'),'샘플 문의하기']]:path==='/business/product-development'?[[inquiryHref('제품개발'),'제품개발 상담'],['/brands/dodoon/products','개발 제품 보기']]:[];return <section className={'hero '+(home?'home-hero':'')}><picture className="responsive-hero"><source media="(max-width: 680px)" srcSet={hero.mobile}/><Image src={hero.desktop} alt="" width={1920} height={home?900:620} priority unoptimized/></picture><div className="hero-shade"/><div className="shell hero-copy"><small>{section}</small>{home?<><p className="home-hero-display">{title.split('\n').map(line=><span key={line}>{line}</span>)}</p><h1>복합버섯균사체 바이오소재 전문기업 기운찬</h1></>:<h1>{title.split('\n').map(line=><span key={line}>{line}</span>)}</h1>}<p>{lead}</p>{home&&<div className="hero-actions"><a className="button light" href="/company">기운찬 알아보기 <ArrowRight size={16}/></a><a className="button ghost" href={inquiryHref('GMK® 원료 공급')}>GMK® 원료사업 문의</a></div>}{businessActions.length>0&&<div className="hero-actions">{businessActions.map(([href,label],i)=><a className={'button '+(i===0?'light':'ghost')} href={href} key={label}>{label}<ArrowRight size={16}/></a>)}</div>}</div></section>}
function InsightCards(){return <div className="editorial-grid">{insights.map((item,i)=><ArticleCard item={item} feature={i===0} key={item.href}/>)}</div>}
function NewsList({compact=false}:{compact?:boolean}){return <div className="news-list">{news.slice(0,compact?3:news.length).map(item=><article key={item.href}><span>{item.source} · {item.date}</span><h2>{item.title}</h2><p>{item.summary}</p>{!compact&&<p><b>기운찬과의 관련성 · 해석</b><br/>{item.meaning}</p>}<a className="text-link" href={item.href} target="_blank" rel="noreferrer">기존 홈페이지에 게재된 원문 출처 ↗</a></article>)}</div>}
function InquiryCta(){return <section className="section contact-band compact-cta"><div className="shell"><small>BUSINESS INQUIRY</small><h2>GMK®와 함께할 가능성을 이야기해 주세요.</h2><p>GMK® 원료 공급, 기술자료, 샘플 검토, 제품 적용, 공동연구 및 국내외 사업 협력에 관한 문의를 기다립니다.</p><a className="button orange" href={inquiryHref('GMK® 원료')}>사업 문의하기 <ArrowRight size={16}/></a></div></section>}
function Home(){const featuredProduct=products[2];const metrics=[{value:'2015',label:'법인 설립',href:'/company#information'},{value:'10',label:'국내 9건·미국 1건 특허',href:'/technology/patents'},{value:'4',label:'국제학술지 논문',href:'/technology/publications'},{value:'완료',label:'인체적용시험',href:'/technology/clinical-study'}];return <Layout><main className="home-page">
 <Hero home section="NATURAL BIO MATERIAL COMPANY" title={'자연을 이해하는 섬세함,\n가능성을 증명하는 과학'} lead={companyDefinition} image="/assets/forest-mycelia.webp"/>
 <section className="hero-metrics" aria-label="기운찬 핵심 성과"><div className="shell">{metrics.map(item=><a href={item.href} key={item.label}><strong>{item.value}</strong><span>{item.label}</span><i aria-hidden="true">↗</i></a>)}</div><p>연구·지식재산 현황은 2026년 8월 기준입니다.</p></section>
 <section className="section home-gmk"><div className="wide-shell"><ImageTextSplit image="/assets/ingredient-plates.webp" alt="기운찬의 바이오소재 연구 이미지"><SectionHeader eyebrow="GIUNCHAN · CORE MATERIAL" title="버섯의 가능성을 하나의 소재로"/><p>{gmkDefinition}</p><p>기운찬은 GMK®의 생산기술과 활용 가능성에 관한 연구를 지속하고 있습니다. GMK®는 소비자 완제품과 구분되는 기업용 원료입니다.</p><p className="gmk-emphasis">공개된 근거를 바탕으로 원료와 제품을 책임 있게 연결합니다.</p><ol className="process-line" aria-label="연구 및 적용 과정"><li>01 소재 연구</li><li>02 공개 근거 축적</li><li>03 원료 협력</li><li>04 제품 적용</li></ol><div className="inline-actions"><Button href="/insight/gmk">GMK® 자세히 알아보기</Button><a className="text-link" href="/technology">연구성과 보기 →</a><a className="text-link" href="/company">회사소개 →</a></div></ImageTextSplit></div></section>
 <section className="section research-evidence"><div className="shell"><SectionHeader eyebrow="RESEARCH EVIDENCE" title="연구로 쌓아온 근거" copy="특허, 전임상 논문과 인체적용시험은 서로 다른 성격의 근거이며 각각의 범위에서 해석해야 합니다."/><div className="evidence-list"><article><strong>10</strong><div><h3>국내외 등록 특허</h3><p>GMK® 복합배양 및 활용과 관련된 공식 권리 현황입니다.</p><a href="/technology/patents">특허 확인하기 →</a></div></article><article><strong>4</strong><div><h3>국제학술지 논문</h3><p>복합버섯균사체 및 관련 추출물의 세포·동물 전임상 연구입니다.</p><a href="/technology/publications">연구논문 확인하기 →</a></div></article><article><strong>완료</strong><div><h3>인체적용시험</h3><p>GMK® 관련 원료에 대한 시험을 완료했으며 세부 결과는 공개하지 않습니다.</p><a href="/technology/clinical-study">현재 상태 확인하기 →</a></div></article></div><p className="research-disclaimer">특허등록은 기능성 승인이나 효능 보증을 의미하지 않습니다. 전임상 연구와 인체적용시험 자료를 개별 판매제품의 효능으로 연결하지 않습니다.</p></div></section>
 <section className="section route-section"><div className="shell"><SectionHeader eyebrow="FROM RESEARCH TO LIFE" title="연구에서 원료로, 원료에서 일상으로" align="split"/><div className="route-split"><a href="/business/ingredient"><small>B2B · INGREDIENT</small><h3>기업을 위한<br/>GMK® 원료사업</h3><p>식품과 건강 관련 제품을 기획하는 기업을 대상으로 GMK® 원료 상담, 규격자료 제공, 샘플 검토, 제품 적용 협의와 공동개발을 진행합니다.</p><b>원료 상담 · 규격자료 · 샘플 검토 · 공동개발</b><span>GMK® 원료사업 알아보기 <ArrowRight/></span></a><a href="/business/product-development"><small>B2C · PRODUCT DEVELOPMENT</small><h3>일상을 위한<br/>제품개발</h3><p>기운찬이 연구·개발한 소재를 음료, 젤리, 농축액 등 소비자가 일상에서 접하기 쉬운 형태의 제품으로 개발합니다.</p><b>음료 · 젤리 · 농축액 · 생활 건강 제품</b><span>제품개발 알아보기 <ArrowRight/></span></a></div></div></section>
 <section className="section product-spotlight"><div className="wide-shell"><SectionHeader eyebrow="DODOON · DAILY WELLNESS" title="과학에서 시작해, 따뜻한 일상으로" copy="도두On은 주식회사 기운찬이 연구한 소재와 식품개발 경험을 소비자의 건강한 일상으로 연결하는 종합 건강 브랜드입니다."/><ProductCard item={featuredProduct} feature/></div></section>
 <section className="section editorial-section"><div className="shell"><SectionHeader eyebrow="LATEST INSIGHT" title="GMK®와 버섯균사체를 이해하다" align="split"/><div className="editorial-grid">{insights.map((item,i)=><ArticleCard item={item} feature={i===0} key={item.href}/>)}</div></div></section>
 <section className="section home-faq"><div className="shell"><SectionHeader eyebrow="PRACTICAL GUIDE" title="자주 묻는 질문"/><FAQ items={[{q:'GMK®는 완제품인가요?',a:'GMK®는 주식회사 기운찬의 독자적인 복합배양 기술로 생산하는 복합버섯균사체 원료이며 소비자 완제품과 구분됩니다.'},{q:'GMK®에는 어떤 연구 근거가 있나요?',a:'공개 근거로 국내외 특허와 국제학술지 전임상 논문이 있습니다. 관련 원료의 인체적용시험은 완료됐으며 세부 결과는 공개하지 않습니다.',href:'/technology',link:'연구개발 확인하기'},{q:'기업이 GMK® 원료를 공급받을 수 있나요?',a:'적용 목적, 제품 유형, 필요 규격과 수량을 확인한 후 원료 공급, 샘플 검토, 기술자료 제공과 공동개발 가능성을 협의할 수 있습니다.',href:'/business/ingredient',link:'원료 공급 알아보기'},{q:'기운찬의 소비자 제품은 어디에서 확인할 수 있나요?',a:'도두On 제품 페이지와 기운찬 공식 쇼핑몰에서 제품별 특징과 구매 정보를 확인할 수 있습니다.',href:'/brands/dodoon/products',link:'도두On 제품 확인하기'}]}/></div></section>
 <section className="section newsroom-home"><div className="shell"><SectionHeader eyebrow="LATEST NEWSROOM" title="기운찬의 새로운 소식" align="split"/><div className="news-editorial">{news.slice(0,3).map((item,i)=><article className={i===0?'is-feature':''} key={item.href}><span>{item.source} · {item.date}</span><h3>{item.title}</h3><p>{item.summary}</p><a href={['/newsroom/gmk-cell-study-2025','/newsroom/gmk-human-application-plan','/newsroom/gmk-preclinical-neuro-study'][i]}>소식 보기 <ArrowRight size={16}/></a></article>)}</div><div className="section-link"><Button href="/newsroom">뉴스룸 더 보기</Button></div></div></section>
 <InquiryCta/>
 </main></Layout>}
function CompanyLegacy(){return <>
 <section id="about" className="section"><div className="shell"><Title eyebrow="WHO WE ARE" title="기운찬은 어떤 회사인가" copy={companyDefinition}/><div className="article-detail wide-copy"><p>핵심 소재 GMK®를 중심으로 연구 근거를 축적하고, 기업의 원료 활용과 소비자 제품개발을 연결합니다. 자연의 가능성을 관찰하는 태도와 공개 가능한 근거를 바탕으로 책임 있게 소통합니다.</p><a className="text-link" href="/technology">특허·논문·인체적용시험 연구 근거 →</a></div></div></section>
 <section className="section warm"><div className="shell"><Title eyebrow="OUR BUSINESS" title="두 가지 방향, 하나의 연구 기반"/><div className="business-weighted"><article><small>B2B INGREDIENT</small><h3>B2B 원료사업</h3><p>복합버섯균사체 소재 GMK®를 기반으로 기업의 연구와 제품기획에 맞는 원료 협력을 추진합니다. 식품·음료 적용, 공동기획, 국내외 공급과 유통 가능성을 함께 검토합니다.</p><Button href="/business/ingredient">B2B 원료사업</Button></article><article><small>B2C DEVELOPMENT</small><h3>B2C 제품개발</h3><p>소재의 특성과 소비자 요구를 고려해 식품·음료·건강 관련 제품을 기획합니다. 자체 브랜드와 파트너사의 제품개발을 통해 연구를 일상으로 연결합니다.</p><Button href="/business/product-development">B2C 제품개발</Button></article></div></div></section>
 <section id="ceo" className="section"><div className="shell ceo-layout"><Photo src="/assets/ceo.webp" alt="주식회사 기운찬 박종례 대표" className="ceo-portrait"/><div><Title eyebrow="MESSAGE FROM CEO" title="버섯의 무한한 가능성을\n책임 있는 연구로 이어갑니다"/><p>처음 버섯균사체를 마주했을 때, 작은 생명체 안에 건강한 삶을 위한 가능성이 있다고 믿었습니다. 그 믿음으로 10년이 넘는 시간 동안 연구하고 실험하며 근거를 쌓아왔습니다.</p><p>기운찬은 속도보다 깊이를, 유행보다 근거를 중요하게 생각합니다. 연구의 원리를 살피고 확인된 정보의 범위 안에서 소통하겠습니다.</p><p>이제 연구·개발한 소재를 기업의 원료와 소비자의 제품으로 연결하고자 합니다. 더 많은 사람이 일상에서 자연의 가치를 경험할 수 있도록 노력하겠습니다.</p><p>연구 결과와 판매제품을 구분하고, 필요한 정보를 정확하게 전달하는 책임 있는 사업을 이어가겠습니다.</p><b>주식회사 기운찬 대표 박종례</b></div></div></section>
 <section id="information" className="section warm"><div className="shell"><Title eyebrow="COMPANY FACTS" title="회사 기본정보"/><Facts rows={[['회사명','주식회사 기운찬'],['영문명','Giunchan Co., Ltd.'],['대표자','박종례'],['설립연도','2015년 · 기존 회사 소개자료 기준'],['주요 분야','천연물 바이오소재 연구·개발 / B2B 원료사업 / B2C 제품개발'],['핵심 소재','GMK® 복합버섯균사체'],['소재지','충남 천안시 동남구 충절로 252, 2F']]}/></div></section>
 <section id="location" className="section"><div className="shell"><Title eyebrow="LOCATION" title="오시는 길" copy="충남 천안시 동남구 충절로 252, 2F"/><div className="location-grid"><iframe title="주식회사 기운찬 위치 지도" src={'https://maps.google.com/maps?q='+encodeURIComponent('충남 천안시 동남구 충절로 252')+'&output=embed'} loading="lazy" referrerPolicy="no-referrer-when-downgrade"/><div><h3>방문 안내</h3><p>길찾기에서 위 도로명 주소를 검색해 주세요. 방문 전 전화로 일정을 확인하시면 안내해 드립니다.</p><p>대표전화 <a href="tel:0415792203">041-579-2203</a><br/>팩스 041-585-2203<br/><a href="mailto:guc2203@guc.co.kr">guc2203@guc.co.kr</a></p><a className="text-link" href={'https://map.naver.com/p/search/'+encodeURIComponent('충남 천안시 동남구 충절로 252')} target="_blank" rel="noreferrer">네이버 지도에서 길찾기 ↗</a></div></div></div></section>
 <section id="contact" className="section sage"><div className="shell"><Title eyebrow="CONTACT GIUNCHAN" title="문의하기" copy="GMK® 원료, B2C 제품개발, 제품·유통, 국내외 사업 등 문의 목적을 선택해 주세요."/><p className="notice">현재 문의 폼은 작성 시연용이며 전송·저장되지 않습니다. 실제 상담은 <a href="mailto:guc2203@guc.co.kr">guc2203@guc.co.kr</a> 또는 <a href="tel:0415792203">041-579-2203</a>로 연락해 주세요.</p><ContactForm/></div></section>
 </>}
function Company(){
 void CompanyLegacy;
 const history:{year:string;title:string;items:string[]}[]=[
  {year:'2015',title:'설립과 연구의 시작',items:['2015년 10월 12일 주식회사 기운찬 법인 설립','충남테크노파크 입주']},
  {year:'2016',title:'연구조직과 제조기술 기반 구축',items:['버섯균사체 제조방법 관련 국내 특허 등록','기업부설연구소 설립']},
  {year:'2017',title:'생산 및 사업 기반 확대',items:['제품개발과 사업화 기반 확대','전국 농수산식품 창업 콘테스트 식품 부문 4위']},
  {year:'2019',title:'브랜드와 산업 인증',items:['농촌융복합산업 인증','브랜드K 선정','서울어워드 우수상품 선정']},
  {year:'2020—2023',title:'지식재산 확장',items:['국내 특허 5건 등록','미국 특허 1건 등록']},
  {year:'2021—2026',title:'학술 근거 축적',items:['GMK 관련 SCIE급 국제학술지 논문 4편 발표']},
  {year:'2026',title:'인체적용시험과 인정 절차',items:['GMK® 관련 원료 인체적용시험 완료','인지기능 분야 건강기능식품 개별인정형 원료 인정 신청']},
 ];
 return <>
 <section id="about" className="section company-overview"><div className="shell"><SectionHeader eyebrow="WHO WE ARE" title="연구에서 시작해 원료와 제품으로"/><div className="company-copy"><div><p>{companyDefinition}</p><p>{gmkDefinition} 기운찬은 공개된 연구 근거와 지식재산권을 축적하고 기업용 원료 공급과 소비자 제품개발로 연결합니다.</p></div><ul className="company-summary"><li>버섯균사체 기반 바이오소재 연구</li><li>공개 연구 근거 축적</li><li>기업용 원료사업</li><li>소비자 제품개발</li></ul></div><Button href="/technology">연구성과 확인하기</Button></div></section>
 <section className="section company-research-spectrum"><div className="wide-shell"><SectionHeader eyebrow="RESEARCH SPECTRUM" title="다양한 버섯에서 가능성을 탐구합니다" copy="버섯은 종류에 따라 서로 다른 특성과 연구 가능성을 지니고 있습니다. 기운찬은 여러 종류의 버섯과 버섯균사체를 폭넓게 살펴보고, 소재로 활용할 수 있는 가능성을 연구해 왔습니다."/><p>개별 버섯의 알려진 특성을 단순히 나열하거나 혼합하는 데 머무르지 않고, 균사체의 생장과 배양 과정에서 나타나는 변화를 관찰하고 연구합니다.</p><figure className="company-spectrum"><Photo src="/assets/research-mushroom-spectrum.jpg" alt="연구실에서 관찰하는 다양한 버섯 표본과 연구 장비"/><figcaption>기운찬은 다양한 버섯과 버섯균사체의 소재 가능성을 폭넓게 연구합니다.</figcaption></figure></div></section>
 <section className="section company-origin"><div className="shell"><ImageTextSplit image="/assets/ceo-park-jongrye-lab-portrait.jpg" alt="기운찬 연구실에 있는 박종례 대표"><SectionHeader eyebrow="OUR BEGINNING" title="자연에서 발견한 가능성, 연구로 이어온 시간"/><p>기운찬은 자연이 가진 가능성을 안정적이고 일관된 소재로 구현하는 방법을 연구해 왔습니다.</p><p>{gmkDefinition} 세부 제조 노하우는 공개하지 않으며, 공개된 연구와 권리정보의 범위 안에서 원료사업과 제품개발을 이어갑니다.</p></ImageTextSplit></div></section>
 <section className="section company-purpose"><div className="shell"><SectionHeader eyebrow="MISSION & VISION" title="자연의 가능성을 책임 있게 연결합니다"/><div className="purpose-grid"><article><small>MISSION</small><h3>연구의 가능성을 산업과 일상의 가치로</h3><p>자연 유래 소재의 가능성을 과학적 근거로 확인하고 기업의 원료와 소비자의 제품으로 연결합니다.</p></article><article><small>VISION</small><h3>복합버섯균사체 분야에서 신뢰받는 식품바이오 소재기업</h3><p>축적된 배양·발효기술과 책임 있는 연구를 바탕으로 국내외 기업과 연구기관이 신뢰할 수 있는 바이오소재 파트너로 성장합니다.</p></article></div><ol className="principle-list"><li><b>01</b><span><strong>연구의 깊이</strong>유행이나 과장보다 반복 가능한 연구와 축적된 근거를 중요하게 생각합니다.</span></li><li><b>02</b><span><strong>책임 있는 소통</strong>연구단계, 원료와 완제품을 구분하고 확인된 정보의 범위 안에서 소통합니다.</span></li><li><b>03</b><span><strong>산업과 일상의 연결</strong>연구한 소재가 기업의 제품개발과 소비자의 일상으로 이어질 수 있도록 사업화합니다.</span></li></ol></div></section>
 <section id="ceo" className="section company-ceo"><div className="shell"><ImageTextSplit image="/assets/ceo-park-jongrye-lab-material.jpg" alt="주식회사 기운찬 박종례 대표가 연구실에서 연구 소재를 들고 있는 모습" reverse><SectionHeader eyebrow="MESSAGE FROM CEO" title={'버섯의 가능성을\n책임 있는 연구로 이어갑니다'}/><p>처음 버섯균사체를 접했을 때, 이 작은 생명체 안에 건강한 삶을 위한 새로운 가능성이 있다고 생각했습니다. 그 가능성을 확인하기 위해 10년이 넘는 시간 동안 다양한 버섯을 살펴보고, 연구하고, 실험하며 근거를 쌓아왔습니다.</p><p>기운찬은 속도보다 깊이를, 유행보다 근거를 중요하게 생각합니다. 연구의 가능성과 한계를 함께 살피고 확인된 정보의 범위 안에서 책임 있게 소통하겠습니다.</p><p>앞으로도 연구·개발한 소재를 기업의 원료와 소비자의 제품으로 연결하며 자연의 가치가 건강한 일상에 닿을 수 있도록 노력하겠습니다.</p><p className="ceo-signature">주식회사 기운찬 대표 <strong>박종례</strong></p></ImageTextSplit></div></section>
 <section className="section company-history"><div className="shell"><SectionHeader eyebrow="HISTORY" title="연구로 쌓아온 기운찬의 시간"/><ol>{history.map(item=><li key={item.year}><time>{item.year}</time><div><h3>{item.title}</h3>{item.items.map(text=><p key={text}>{text}</p>)}</div></li>)}</ol><p className="history-note">2026년 현재 식품의약품안전처의 심사 절차가 진행 중이며, 개별인정형 원료로 인정이 완료된 상태는 아닙니다.</p><Button href="/technology">특허와 연구성과 자세히 보기</Button></div></section>
 <section className="section company-rnd"><div className="wide-shell"><SectionHeader eyebrow="GIUNCHAN R&D" title="연구가 기운찬의 시작이자 중심입니다" copy="기운찬은 제품 판매에서 출발한 회사가 아니라 다양한 버섯과 버섯균사체의 가능성을 연구하는 과정에서 시작한 식품바이오 기업입니다. 기업부설연구소를 중심으로 균사체 배양·발효, 소재 특성, 활용 가능성과 품질에 관한 연구를 축적해 왔습니다."/><p className="rnd-copy">연구결과를 특허와 학술자료로 남기고 대학·의료기관과의 협력을 통해 근거를 확장합니다. 이렇게 축적한 기술과 연구 경험은 GMK® 원료사업과 소비자 제품개발의 기반이 됩니다.</p><figure><Photo src="/assets/giunchan-rnd-team.jpg" alt="주식회사 기운찬 기업부설연구소 연구진"/><figcaption>다양한 버섯과 버섯균사체의 가능성을 연구하는 기운찬 기업부설연구소 연구진</figcaption></figure></div></section>
 <section className="section company-gallery"><div className="wide-shell"><SectionHeader eyebrow="INSIDE THE LAB" title="연구실에서 이어지는 관찰과 검토"/><div className="research-gallery"><figure className="is-feature"><Photo src="/assets/giunchan-research-sample-review.jpg" alt="기운찬 연구원이 플라스크 속 연구 시료를 확인하는 모습"/><figcaption>연구 시료의 상태를 관찰하고 기록하는 과정</figcaption></figure><figure><Photo src="/assets/giunchan-culture-research.jpg" alt="무균 작업 환경에서 배양 시료를 다루는 연구 장면"/><figcaption>배양 시료를 세심하게 관리하는 연구 과정</figcaption></figure><figure><Photo src="/assets/mushroom-mycelia-research.jpg" alt="버섯 표본과 균사체 배양 상태를 함께 관찰하는 연구 장면"/><figcaption>버섯과 균사체의 특성을 비교하고 관찰하는 연구</figcaption></figure></div></div></section>
 <section className="section company-capabilities"><div className="shell"><SectionHeader eyebrow="OUR CAPABILITIES" title="연구를 사업으로 연결하는 역량"/><ol>{[
  ['연구개발','다양한 버섯과 버섯균사체를 살펴보고 배양·발효를 기반으로 소재의 특성과 활용 가능성을 연구합니다.','/technology'],
  ['지식재산','GMK® 생산방법과 활용기술에 관한 국내 특허 9건과 미국 특허 1건을 확보했습니다.','/technology/patents'],
  ['학술 협력','대학 및 의료기관과 공동연구를 진행하고 연구결과를 국제학술지에 발표해 왔습니다.','/technology/publications'],
  ['원료 사업화','기업의 제품기획에 맞춰 원료 상담, 규격자료, 샘플 검토와 적용 가능성을 협의합니다.','/business/ingredient'],
  ['제품개발','연구한 소재와 식품개발 경험을 바탕으로 소비자가 일상에서 접할 수 있는 제품을 개발합니다.','/business/product-development']
 ].map(([title,copy,href],i)=><li key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{copy}</p><a href={href}>자세히 보기 →</a></div></li>)}</ol><a className="text-link capability-clinical" href="/technology/clinical-study">인체적용시험 확인하기 →</a></div></section>
 <section className="section company-business"><div className="shell"><SectionHeader eyebrow="OUR BUSINESS" title="연구에서 원료로, 원료에서 제품으로"/><div className="route-split"><a href="/business/ingredient"><small>B2B · INGREDIENT</small><h3>GMK® 원료사업</h3><p>GMK®를 기반으로 기업의 제품기획과 적용 목적에 맞는 원료 상담, 규격자료, 샘플 검토와 공동개발을 진행합니다.</p><span>GMK® 원료사업 알아보기 <ArrowRight/></span></a><a href="/business/product-development"><small>B2C · PRODUCT DEVELOPMENT</small><h3>소비자 제품개발</h3><p>연구한 소재와 식품개발 경험을 바탕으로 음료, 젤리, 농축액 등 소비자가 일상에서 접할 수 있는 제품을 개발합니다.</p><span>제품개발 알아보기 <ArrowRight/></span></a></div></div></section>
 <section id="information" className="section company-information"><div className="shell"><SectionHeader eyebrow="COMPANY FACTS" title="회사 기본정보"/><dl className="company-facts"><div><dt>회사명</dt><dd>주식회사 기운찬</dd></div><div><dt>영문명</dt><dd>Giunchan Co., Ltd.</dd></div><div><dt>대표자</dt><dd>박종례</dd></div><div><dt>설립일</dt><dd>2015년 10월 12일</dd></div><div><dt>소재지</dt><dd>충남 천안시 동남구 충절로 252, 2F</dd></div><div><dt>주요 사업</dt><dd>천연물 바이오소재 연구개발, B2B 원료사업, B2C 제품개발</dd></div><div><dt>핵심 소재</dt><dd>GMK® 복합버섯균사체</dd></div><div><dt>연구조직</dt><dd>기업부설연구소</dd></div><div><dt>대표전화</dt><dd><a href="tel:+82415792203">041-579-2203</a></dd></div><div><dt>팩스</dt><dd>041-585-2203</dd></div><div><dt>이메일</dt><dd><a href="mailto:guc2203@guc.co.kr">guc2203@guc.co.kr</a></dd></div></dl></div></section>
 <section id="location" className="section company-location"><div className="shell"><SectionHeader eyebrow="LOCATION" title="기운찬으로 오시는 길" copy="충남 천안시 동남구 충절로 252, 2F"/><div className="location-grid"><iframe title="주식회사 기운찬 위치 지도" src={'https://maps.google.com/maps?q='+encodeURIComponent('충남 천안시 동남구 충절로 252')+'&output=embed'} loading="lazy" referrerPolicy="no-referrer-when-downgrade"/><div><h3>방문 안내</h3><p>방문 상담이 필요하신 경우 대표전화 또는 이메일로 일정을 먼저 확인해 주세요.</p><a href="tel:+82415792203">대표전화 041-579-2203</a><span>팩스 041-585-2203</span><a href="mailto:guc2203@guc.co.kr">guc2203@guc.co.kr</a><a href={'https://map.naver.com/p/search/'+encodeURIComponent('충남 천안시 동남구 충절로 252')} target="_blank" rel="noreferrer">네이버 지도에서 길찾기 ↗</a></div></div></div></section>
 <section id="contact" className="section company-contact"><div className="shell"><SectionHeader eyebrow="CONTACT GIUNCHAN" title="연구와 사업의 가능성을 이야기해 주세요" copy="GMK® 원료, 제품개발, 유통과 국내외 사업 협력에 관한 문의를 기다립니다."/><ContactForm/><div className="inline-actions"><a className="button orange" href="mailto:guc2203@guc.co.kr">이메일 문의하기 <ArrowRight size={16}/></a><a className="button light" href="tel:+82415792203">전화 문의하기 <ArrowRight size={16}/></a><a className="text-link" href="/business/ingredient">GMK® 원료사업 문의 →</a></div></div></section>
 </>;
}
function Facts({rows}:{rows:string[][]}){return <div className="table-wrap"><table className="facts-table"><tbody>{rows.map(([key,value])=><tr key={key}><th scope="row">{key}</th><td>{value}</td></tr>)}</tbody></table></div>}
function ResearchNotice(){return <p className="research-disclaimer">{researchDisclaimer}</p>}
function Technology({path}:{path:string}) {
 if(path==='/technology/patents')return <div className="technology-detail patent-page"><SectionHeader eyebrow="INTELLECTUAL PROPERTY" title="IP 현황" copy="기운찬이 보유한 국내외 특허·상표·디자인 등록 현황과 공개 가능한 등록특허 정보를 안내합니다."/><section className="ip-summary-section"><h2>지식재산권 등록 현황</h2><div className="table-wrap"><table className="research-table ip-summary-table"><caption>기운찬 국내외 지식재산권 등록 현황</caption><thead><tr><th scope="col">권리 구분</th><th scope="col">등록 국가</th><th scope="col">등록 건수</th><th scope="col">상태</th></tr></thead><tbody>{ipRegistrationSummary.map(item=><tr key={`${item.category}-${item.country}`}><th scope="row">{item.category}</th><td>{item.country}</td><td>{item.count}건</td><td>{item.status}</td></tr>)}</tbody><tfoot><tr><th scope="row" colSpan={2}>전체 등록</th><td>{ipRegistrationSummary.reduce((sum,item)=>sum+item.count,0)}건</td><td>등록</td></tr></tfoot></table></div></section><section><h2>등록특허 목록</h2><p className="review-meta">등록증 자료 기준일: {patentPortfolio.sourceAsOf.replaceAll('-','.')}</p><div className="patent-records">{publicPatentRecords.map(record=><article key={record.number}><span>{record.country} · {record.status}</span><h3>{record.title}</h3><dl><div><dt>등록번호</dt><dd>{record.number}</dd></div><div><dt>등록일</dt><dd>{record.registeredAt}</dd></div><div><dt>권리자</dt><dd>{record.owner}</dd></div></dl><a href={record.url} target="_blank" rel="noreferrer">등록공보 확인 ↗</a></article>)}</div><div className="external-links"><a href="https://www.kipris.or.kr/" target="_blank" rel="noreferrer">KIPRIS 특허정보검색 ↗</a><a href="https://ppubs.uspto.gov/pubwebapp/" target="_blank" rel="noreferrer">USPTO Patent Public Search ↗</a></div></section><p className="notice">등록 여부는 제공된 등록증과 공개정보를 기준으로 정리했습니다. 특허등록은 기술적 권리의 확보를 의미하며 제품의 기능성 승인이나 효능 보증을 의미하지 않습니다.</p><Button href={inquiryHref('기술자료')}>기술자료 문의</Button></div>;
 if(path==='/technology/publications')return <div className="technology-detail"><SectionHeader eyebrow="PUBLICATIONS" title="국제학술지 논문 4편" copy="기운찬은 대학 연구팀과 함께 복합버섯균사체 및 관련 추출물에 관한 세포·동물 전임상 연구를 수행하고 국제학술지에 연구결과를 발표했습니다."/><p className="notice">아래 연구는 전임상 단계의 연구로, 사람의 질병 예방·치료 효과나 완제품의 효능을 의미하지 않습니다.</p><div className="publication-list">{publicPublications.map(p=><article key={p.doi}><time>{p.year}</time><div><span className="stage-badge">{p.stage}</span><h2>{p.title}</h2><p><b>{p.journal}</b></p><p>{p.summary}</p><a href={'https://doi.org/'+p.doi} target="_blank" rel="noreferrer">논문 원문 보기 ↗</a></div></article>)}</div><ResearchNotice/><p className="review-meta">자료 검토: 주식회사 기운찬 기업부설연구소 · 최종 수정일: 2026년 9월 5일</p><Button href={inquiryHref('연구자료')}>연구자료 문의</Button></div>;
 if(path==='/technology/clinical-study')return <div className="technology-detail clinical-page"><SectionHeader eyebrow="HUMAN STUDY" title={clinicalStudyPublic.title} copy={clinicalStudyPublic.summary}/><section><h2>시험 개요</h2><Facts rows={[["연구시료",clinicalStudyPublic.material],["수행기관",clinicalStudyPublic.sites.join(' · ')],["대상",clinicalStudyPublic.population],["기간",clinicalStudyPublic.duration],["설계",clinicalStudyPublic.design],["평가지표",clinicalStudyPublic.primaryOutcome]]}/></section><section><h2>공개된 결과와 현재 절차</h2><p>{clinicalStudyPublic.publicResult}</p><p>{clinicalStudyPublic.reviewNotice}</p><ul className="source-list">{clinicalStudyPublic.sources.map(source=><li key={source.url}><a href={source.url} target="_blank" rel="noreferrer">{source.label} ↗</a></li>)}</ul></section><section><h2>해석 범위</h2><ResearchNotice/><p>인체적용시험은 의약품 임상시험과 구분됩니다.</p></section><p className="review-meta">자료 검토: 주식회사 기운찬 기업부설연구소 · 최종 수정일: 2026년 9월 6일</p><Button href={inquiryHref('인체적용시험 자료')}>연구자료 문의</Button></div>;
 const principles=['시료와 연구목적의 명확한 구분','연구단계에 맞는 결과 해석','산학협력을 통한 근거 축적','연구원료와 판매제품의 분리','확인된 범위 안에서의 책임 있는 소통'];
 const gmkProcess=[['균주 선별','연구 목적에 맞는 균주를 선별합니다.'],['동시 접종','선별한 균주를 동시에 접종합니다.'],['복합배양','접종한 균주를 함께 배양합니다.'],['건조 GMK®','복합배양물을 건조해 기본 원료로 만듭니다.'],['추출·농축','적용 목적에 따라 추출하고 농축합니다.'],['원료화','기본 원료와 파생 원료 형태로 구분합니다.'],['제품 적용','제품 목적과 제형에 맞춰 적용을 검토합니다.']] as const;
 const framework=[['연구 대상 탐색','버섯균사체의 특성과 소재 가능성을 살펴봅니다.'],['배양기술 연구','독자적인 복합배양 기술을 연구하고 공개 가능한 범위에서 기술 근거를 축적합니다.'],['원료 형태 개발','연구와 적용 목적에 따라 기본 원료와 액상·분말 파생 원료를 구분합니다.'],['특성 및 품질 확인','연구 목적에 맞는 시료를 설정하고 소재 특성과 품질의 일관성을 확인합니다.'],['전임상 연구','세포 및 동물모델을 활용해 연구시료의 가능성과 연구가설을 검토합니다.'],['인체적용 및 사업화','특정 연구시료의 인체적용시험을 수행하고 원료 인정 절차와 사업화를 검토합니다.']];
 const history=[['2015','연구개발 기반 구축',['연구개발'],'복합버섯균사체 관련 연구개발을 시작했습니다.'],['2016~2019','기술권리와 연구체계 확대',['특허','연구체계'],'국내 지식재산권과 기업부설연구소를 기반으로 연구체계를 확대했습니다.'],['2021','국제학술지 연구 발표',['세포실험','동물실험','논문'],'복합버섯균사체 관련 전임상 연구결과를 국제학술지에 발표했습니다.'],['2022','미국 특허 등록',['특허'],'GMK® 복합배양 기술 관련 미국 특허를 확보했습니다.'],['2023~2026','전임상 연구 축적',['세포실험','동물실험','논문'],'복합버섯균사체 및 관련 추출물의 전임상 연구결과를 국제학술지에 발표했습니다.'],['2026','인체적용시험과 인정 절차',['인체적용시험','절차 진행 중'],'GMK® 관련 원료의 인체적용시험을 완료하고 식약처 개별인정형 원료 인정 절차를 진행하고 있습니다.']];
 return <div className="technology-hub"><SectionHeader eyebrow="RESEARCH PRINCIPLES" title="가능성을 주장하기 전에, 단계별로 확인합니다" copy="기운찬은 자연 유래 소재라는 이유만으로 가능성을 단정하지 않습니다. 연구 목적에 맞는 시료를 설정하고 세포실험, 동물실험과 인체적용시험을 통해 단계적으로 근거를 축적합니다."/><p>각 연구결과는 사용한 시료, 연구모델과 조건 안에서 해석합니다. 연구용 원료와 판매제품을 구분하고, 확인된 정보의 범위 안에서 책임 있게 소통합니다.</p><ol className="research-principles">{principles.map((x,i)=><li key={x}><span>0{i+1}</span>{x}</li>)}</ol>
 <section><SectionHeader eyebrow="RESEARCH FOCUS" title="복합버섯균사체의 가능성을 연구합니다"/><p>{gmkDefinition}</p><p>{gmkResearchStatement}</p><p>연구자료를 읽을 때에는 기본 원료, 파생 원료와 소비자 완제품을 서로 구분해야 합니다.</p><Button href="/insight/mycelia">버섯균사체 알아보기</Button></section>
 <section className="gmk-process-section"><SectionHeader eyebrow="GMK® PROCESS" title="균주 선별에서 제품 적용까지"/><ProcessInfographic steps={gmkProcess} label="GMK® 제조 및 적용 과정"/></section>
 <section><SectionHeader eyebrow="MATERIAL CLASSIFICATION" title="연구와 적용 목적에 따라 구분되는 GMK® 원료" copy="GMK®와 파생 원료는 같은 형태가 아닙니다. 명칭과 형태를 구분해야 연구자료와 제품 적용 범위를 정확하게 이해할 수 있습니다."/><div className="table-wrap"><table className="research-table"><caption>GMK® 원료 형태 비교</caption><thead><tr>{['구분','정의','형태','일반적인 적용 검토'].map(x=><th key={x} scope="col">{x}</th>)}</tr></thead><tbody>{publicIngredientForms.map(row=><tr key={row.name}><th scope="row">{row.name}</th><td>{row.definition}</td><td>{row.form}</td><td>{row.use}</td></tr>)}</tbody></table></div></section>
 <section><SectionHeader eyebrow="RESEARCH FRAMEWORK" title="소재 탐색부터 인체적용 연구까지"/><ol className="framework-list">{framework.map(([t,c],i)=><li key={t}><span>0{i+1}</span><div><h3>{t}</h3><p>{c}</p></div></li>)}</ol><p className="notice">연구 흐름은 과제 목적에 따라 달라질 수 있으며, 전임상 결과가 사람에서의 효능을 자동으로 입증하지 않습니다.</p></section>
 <section><SectionHeader eyebrow="R&D HISTORY" title="정부 R&D와 산학협력으로 축적한 연구" copy="기운찬은 정부 R&D 지원사업과 대학·연구기관과의 협력을 통해 다양한 버섯균사체 연구를 단계적으로 수행해 왔습니다."/><ol className="research-history">{history.map(([y,t,badges,c])=><li key={y as string}><time>{y}</time><div><div className="stage-badges">{(badges as string[]).map(b=><span key={b}>{b}</span>)}</div><h3>{t}</h3><p>{c}</p></div></li>)}</ol></section>
 <section><SectionHeader eyebrow="EVIDENCE LEVELS" title="연구결과는 연구단계에 따라 다르게 해석됩니다"/><div className="table-wrap"><table className="research-table"><caption>연구단계별 확인 내용과 해석 범위</caption><thead><tr><th>연구단계</th><th>확인하는 내용</th><th>해석 범위</th></tr></thead><tbody>{[['세포실험','특정 세포환경에서 나타나는 반응','사람에게 동일하게 적용된다고 단정할 수 없음'],['동물실험','생체 모델에서 나타나는 변화와 연구 가능성','인체 효능을 직접 의미하지 않음'],['안전성 평가','정해진 시험조건에서의 독성 관련 지표','모든 섭취조건에서의 절대적 안전을 의미하지 않음'],['인체적용시험','특정 대상자와 조건에서의 유효성·안전성 지표','시험물질·대상·기간·평가지표 범위에서 해석'],['제품 적용','식품 기준에 맞춘 원료 및 제품개발','연구결과와 판매제품의 표시·광고는 별도로 판단']].map(r=><tr key={r[0]}>{r.map((x,i)=>i===0?<th scope="row" key={x}>{x}</th>:<td key={x}>{x}</td>)}</tr>)}</tbody></table></div></section>
 <section><SectionHeader eyebrow="RESEARCH EVIDENCE" title="연구로 축적한 근거"/><div className="evidence-links"><a href="/technology/patents"><strong>{patentPortfolio.registeredTotal}</strong><h3>국내외 등록 특허</h3><p>공식 권리 현황</p></a><a href="/technology/publications"><strong>{publicPublications.length}</strong><h3>국제학술지 논문</h3><p>전임상 연구와 DOI 원문</p></a><a href="/technology/clinical-study"><strong>완료</strong><h3>인체적용시험</h3><p>{clinicalStudyPublic.shortStatus}</p></a></div><ResearchNotice/></section><p className="review-meta">자료 검토: 주식회사 기운찬 기업부설연구소 · 최종 수정일: 2026년 9월 5일</p><Button href={inquiryHref('공동연구·기술자료')}>공동연구·기술자료 문의</Button></div>;
}
const cooperationSteps=[['상담 접수','목표 제품, 제형, 예상 수량, 판매지역과 희망 일정을 확인합니다.'],['요구사항 검토','원료 형태, 적용 가능성, 생산방식 및 필요한 자료 범위를 검토합니다.'],['원료·제품 방향 제안','제품 목적에 맞는 원료와 제형, 개발 및 생산 방향을 제안합니다.'],['샘플 및 시제품 검토','상담과 필요한 절차를 거쳐 원료 샘플 또는 시제품을 검토합니다.'],['견적·계약 및 생산 협의','규격, 수량, 생산방법, 납기와 공급조건을 협의합니다.'],['생산·공급 또는 완제품 납품','자체 생산 또는 OEM·ODM 협력 생산을 통해 원료나 완제품을 공급합니다.']];
const businessFaq=[{q:'기운찬은 어떤 사업을 하나요?',a:'기운찬은 GMK® 원료 공급, 제품기획, 배합·시제품, 관능평가, 제조사 연결과 완제품 납품을 지원합니다. 자체 브랜드 제품 판매와 해외 원료·완제품 협력 상담도 진행합니다.'},{q:'기운찬은 제품개발의 어느 단계까지 지원하나요?',a:'제품 콘셉트와 원료 선정부터 배합, 시제품, 관능평가, 표시사항 검토, 제조사 연결과 완제품 납품까지 협의할 수 있습니다. 범위는 제품 유형과 생산조건에 따라 정합니다.'},{q:'자체 생산과 OEM·ODM 생산이 모두 가능한가요?',a:'버섯한스푼 시리즈 등 일부 제품은 자체 생산합니다. 제품 유형과 설비 요건에 따라 전문 OEM·ODM 협력 제조사와 함께 생산합니다.'},{q:'완제품으로 납품받을 수 있나요?',a:'가능합니다. 제품기획과 생산조건을 협의한 뒤 자체 또는 협력 생산방식으로 완제품 납품을 진행할 수 있습니다.'},{q:'해외 원료공급이나 수출 협력이 가능한가요?',a:'외부 전문 협력체계와 해외 네트워크를 통해 원료 공급, 완제품 수출과 유통 파트너 상담을 진행합니다. 대상 국가와 제품 유형에 따라 필요한 자료와 협력방식을 검토합니다.'},{q:'판매 중인 제품은 어디에서 구매할 수 있나요?',a:'도두On 제품 페이지에서 전체 제품을 확인할 수 있으며 구매는 기운찬 공식 네이버 스마트스토어로 연결됩니다.',href:'/brands/dodoon/products',link:'전체 제품 보기'}];
const ingredientFaq=[{q:'GMK® 원료는 기업이 구매할 수 있나요?',a:'GMK®, GMK 추출액과 GMK 추출물은 기업에 공급 가능합니다. 사용 목적과 예상 수량을 확인한 후 공급조건을 협의합니다.'},{q:'GMK®와 GMK 추출액, GMK 추출물은 어떻게 다른가요?',a:'GMK®는 건조한 기본 원료이고, GMK 추출액은 이를 열수 추출한 갈색 액상입니다. GMK 추출물은 추출액을 농축·동결건조한 분말 원료입니다.'},{q:'어떤 제품에 적용할 수 있나요?',a:'분말·고형·차류에는 GMK® 또는 GMK 추출물을, 액상차·음료·소스류에는 GMK 추출액을 우선 검토할 수 있습니다. 최종 형태는 맛, 색, 가공조건과 목표 규격을 함께 검토해 결정합니다.'},{q:'원료 샘플을 요청할 수 있나요?',a:'상담 후 원료 샘플 제공 조건과 범위를 안내합니다. 비용과 수량 등 구체적인 조건은 홈페이지에 고정하지 않고 개별 협의합니다.'},{q:'최소주문수량과 포장단위는 어떻게 되나요?',a:'포장단위와 최소주문수량은 원료 형태, 개발 목적과 예상 사용량에 따라 협의합니다. 초기 문의에서는 예상 수량을 미정으로 남겨도 됩니다.'},{q:'NDA 체결 후 어떤 자료를 받을 수 있나요?',a:'필요성과 공개 범위를 검토해 상세 사양, 샘플 조건, 내부 분석자료, 적용자료와 비공개 시험자료 등을 안내할 수 있습니다. 제조공정 관련 자료는 제공 가능한 범위가 별도로 정해집니다.'},{q:'연구기관도 시료를 문의할 수 있나요?',a:'대학과 연구기관도 연구 목적, 시료 형태와 필요 수량을 기재해 문의할 수 있습니다. 제공 여부와 조건은 연구 목적 및 자료 범위를 검토한 뒤 협의합니다.'}];
const developmentFaq=[{q:'제품 아이디어만 있어도 상담할 수 있나요?',a:'가능합니다. 목표 소비자, 유통채널과 섭취 상황을 확인해 제품 콘셉트와 개발 방향부터 함께 검토합니다.'},{q:'배합과 시제품 개발도 가능한가요?',a:'원료의 맛·향·색과 목표 제형을 고려해 배합과 시제품을 검토합니다. 구체적인 범위와 횟수는 상담 후 협의합니다.'},{q:'관능평가와 표시사항 검토를 지원하나요?',a:'맛·향·색·식감과 섭취 편의성을 검토하고, 제품 유형과 사용 원료에 따른 표시정보 검토를 지원합니다. 최종 품목제조보고와 표시사항은 생산 제조사의 관련 기준에 따라 확정됩니다.'},{q:'제조사를 정하지 않은 상태에서도 상담할 수 있나요?',a:'가능합니다. 제품 유형과 생산설비 요건에 맞는 OEM·ODM 협력 제조사 연결을 검토할 수 있습니다.'},{q:'기운찬이 직접 생산하나요?',a:'버섯한스푼 시리즈 등 일부 제품은 기운찬이 자체 생산합니다. 그 밖의 제품은 유형과 생산설비 요건에 따라 전문 협력 제조사와 생산합니다.'},{q:'완제품 납품이 가능한가요?',a:'생산조건과 납기를 협의해 자체 생산 또는 OEM·ODM 협력 생산 후 완제품으로 공급할 수 있습니다.'}];
function BusinessProducts(){return <div className="business-product-grid gmk-product-gallery">{Array.from({length:27},(_,index)=>{const number=index+1;return <figure key={number}><Photo src={`/assets/gmk-products/${number}.jpg`} alt={`GMK® 원료로 만든 제품 ${number}`}/></figure>})}</div>}
function Business({path}:{path:string}){
 if(path==='/business/ingredient')return <div className="business-page ingredient-business"><div className="hero-inline-actions"><Button href={inquiryHref('GMK® 원료 공급')}>원료 상담하기</Button><Button href={inquiryHref('원료 샘플')} tone="light">샘플 문의하기</Button></div><section><SectionHeader eyebrow="INGREDIENT FORMS" title="목적에 따라 선택하는 세 가지 원료 형태" copy={gmkDefinition}/><div className="ingredient-cards">{publicIngredientForms.map(item=><article key={item.name}><h2>{item.name}</h2><p>{item.definition}</p><b>형태</b><p>{item.form}</p><b>일반적인 적용 검토</b><p>{item.use}</p></article>)}</div><p className="notice">원료 형태와 판매제품은 서로 구분됩니다. 연구자료가 모든 적용 제품의 기능성을 의미하지 않습니다.</p></section><section><SectionHeader eyebrow="SUPPLY CONDITIONS" title="공급조건과 자료 제공 범위"/><p>GMK®, GMK® 추출액과 GMK® 추출물은 기업에 공급 가능합니다. 포장단위와 최소주문수량은 원료 형태, 개발 목적과 예상 사용량에 따라 협의합니다.</p><p>원료 샘플과 비공개 기술자료는 상담 및 NDA 체결 후 제공 조건과 범위를 안내합니다.</p><div className="disclosure-grid"><article><h3>홈페이지 공개자료</h3><ul>{['원료 형태와 일반적인 적용 분야','공개된 특허 권리 현황','발표된 전임상 논문과 DOI','인체적용시험 완료 및 현재 절차','기업 및 연구소 정보'].map(x=><li key={x}>{x}</li>)}</ul></article><article><h3>상담 또는 NDA 이후</h3><ul>{['상세 사양과 거래 조건','샘플 제공 조건','내부 분석 및 적용자료','비공개 시험자료','제조기술 관련 제공 가능 자료'].map(x=><li key={x}>{x}</li>)}</ul></article></div><div className="inline-actions"><Button href={inquiryHref('원료 샘플')}>원료 샘플 문의</Button><Button href={inquiryHref('NDA 및 기술자료')} tone="light">NDA 및 기술자료 문의</Button><a className="text-link" href={inquiryHref('GMK® 원료 공급')}>제품 적용 상담 →</a></div></section><section><SectionHeader eyebrow="SELECTION GUIDE" title="어떤 GMK® 원료를 선택해야 하나요?"/><ul className="selection-guide"><li>제품 유형과 목표 제형에 맞는 원료 형태를 검토합니다.</li><li>맛·향·색과 가공조건, 표시사항 및 목표 규격을 함께 확인합니다.</li><li>연구 목적의 시료는 연구설계와 공개 가능한 자료 범위를 먼저 협의합니다.</li><li>최종 적용 형태와 조건은 상담 및 검토 후 결정합니다.</li></ul></section><section><SectionHeader eyebrow="PRACTICAL GUIDE" title="원료사업 자주 묻는 질문"/><FAQ items={ingredientFaq}/></section></div>;
 if(path==='/business/product-development')return <div className="business-page development-business"><div className="hero-inline-actions"><Button href={inquiryHref('제품개발')}>제품개발 상담</Button><Button href="/brands/dodoon/products" tone="light">개발 제품 보기</Button></div><section><SectionHeader eyebrow="DEVELOPMENT SUPPORT" title="제품기획부터 완제품 납품까지"/><div className="service-cards">{[['제품기획','소비자, 유통채널과 섭취 상황을 고려한 제품 콘셉트 설정'],['배합·시제품','원료 특성과 목표 제형에 맞는 배합 및 시제품 검토'],['관능평가','맛·향·색·식감과 섭취 편의성 검토'],['표시사항 검토','제품 유형과 사용 원료에 따른 표시정보 검토'],['제조사 연결','생산설비와 제품 유형에 적합한 OEM·ODM 협력사 연계'],['완제품 납품','생산조건 협의부터 완제품 공급까지 진행']].map(([t,c],i)=><article key={t}><span>0{i+1}</span><h3>{t}</h3><p>{c}</p></article>)}</div><p className="notice">최종 제품의 품목제조보고와 표시사항은 제품 유형, 제조방법 및 생산 제조사의 관련 기준에 따라 확정됩니다.</p></section><section><SectionHeader eyebrow="PRODUCT FIELDS" title="개발 가능 분야"/><div className="field-tags">{['차·음료','분말·스틱','젤리·간식','고형제품','소스 및 일반식품','선물용 제품','기관·단체용 제품','지역 농산물 및 특화소재 결합 제품'].map(x=><span key={x}>{x}</span>)}</div></section><section><SectionHeader eyebrow="PROCESS" title="일곱 단계 제품개발 절차"/><ol className="business-process">{['개발 상담','제품 콘셉트 설정','원료·제형 검토','배합 및 시제품','관능·표시사항 검토','자체 또는 협력 생산','완제품 납품'].map((x,i)=><li key={x}><span>0{i+1}</span>{x}</li>)}</ol><p>기운찬은 버섯한스푼 시리즈 등 일부 제품을 자체 생산하며, 제품의 유형과 생산설비 요건에 따라 전문 OEM·ODM 협력 제조사와 함께 제품을 생산합니다.</p></section><section><SectionHeader eyebrow="GMK® PRODUCTS" title="GMK를 원료로 만든 제품" copy="GMK®는 제품에 차별성과 버섯의 영양을 더해, 한층 더 프리미엄한 제품을 만들고자 하는 분들이 선택하는 원료입니다."/><BusinessProducts/></section><section><SectionHeader eyebrow="PRACTICAL GUIDE" title="제품개발 자주 묻는 질문"/><FAQ items={developmentFaq}/></section></div>;
 const areas=[['GMK® 원료사업','GMK®, GMK 추출액, GMK 추출물 등 제품 목적에 맞는 원료 형태를 기업에 공급하고 적용 방향을 협의합니다.','/business/ingredient','원료사업 보기'],['제품개발 및 공동개발','제품 콘셉트 기획부터 배합, 시제품, 관능평가, 표시사항 검토와 제조사 연계까지 제품개발 전반을 지원합니다.','/business/product-development','제품개발 보기'],['자체 제품 및 브랜드','연구개발한 소재를 소비자가 일상에서 경험할 수 있도록 자체 브랜드와 다양한 제품을 개발·판매합니다.','/brands/dodoon/products','전체 제품 보기'],['해외사업 협력','외부 전문 협력체계와 해외 네트워크를 활용해 원료와 완제품의 해외 공급 및 유통 파트너 협의를 진행합니다.',inquiryHref('해외 원료공급'),'해외사업 문의']];
 return <div className="business-page business-hub"><div className="hero-inline-actions"><Button href="/business/ingredient">GMK® 원료 협력</Button><Button href="/business/product-development" tone="light">제품개발 상담</Button></div><section><SectionHeader eyebrow="BUSINESS AREAS" title="연구에서 공급과 제품화까지"/><div className="business-area-grid">{areas.map(([t,c,h,l],i)=><article key={t}><span>0{i+1}</span><h2>{t}</h2><p>{c}</p><a href={h}>{l} →</a></article>)}</div></section><section><SectionHeader eyebrow="PARTNERS & SUPPORT" title="함께할 수 있는 대상과 지원 범위"/><div className="partner-support"><article><h3>협력 대상</h3><ul>{['식품·음료 제조기업','소비자 제품 브랜드사','OEM·ODM 제조기업','원료 유통사','국내외 유통 및 수출 파트너','대학·연구기관','지역특화소재를 보유한 기업·기관','공동 제품개발을 원하는 기업·단체'].map(x=><li key={x}>{x}</li>)}</ul></article><article><h3>지원 범위</h3><ul>{['제품 콘셉트 및 기획','원료 선정과 적용 검토','배합 설계와 시제품 개발','관능평가와 표시사항 검토','제조사 연결','자체 또는 협력 생산','완제품 납품과 원료 공급','국내외 사업 협력'].map(x=><li key={x}>{x}</li>)}</ul></article></div><p className="notice">최종 제품의 품목제조보고와 표시사항은 제품 유형, 제조방법 및 생산 제조사의 관련 기준에 따라 확정됩니다.</p></section><section className="production-split"><div><SectionHeader eyebrow="PRODUCTION" title="자체 생산과 협력 생산"/><p>기운찬은 버섯한스푼 시리즈 등 일부 제품을 자체 생산하며, 제품의 유형과 생산설비 요건에 따라 전문 OEM·ODM 협력 제조사와 함께 제품을 생산합니다.</p><p>원료와 제품 특성에 따라 자체 생산 또는 협력 생산방식을 적용하고, 제품기획부터 완제품 납품까지 개발과정을 관리합니다.</p></div><Photo src="/assets/product-mushroom-spoon.jpg" alt="기운찬이 자체 생산하는 버섯한스푼 제품"/></section><section><SectionHeader eyebrow="COOPERATION PROCESS" title="협력은 이렇게 진행됩니다"/><ol className="cooperation-steps">{cooperationSteps.map(([t,c],i)=><li key={t}><span>0{i+1}</span><div><h3>{t}</h3><p>{c}</p></div></li>)}</ol></section><section className="global-business"><SectionHeader eyebrow="GLOBAL COOPERATION" title="국내에서 세계로 이어지는 사업협력"/><p>기운찬은 다양한 해외 네트워크와 외부 전문 협력체계를 활용해 GMK® 원료와 완제품의 해외 공급, 수출 실무 및 유통 파트너 상담을 진행합니다. 대상 국가와 제품 유형에 따라 필요한 자료와 협력방식을 검토합니다.</p><ul>{['GMK® 원료 해외 공급 상담','완제품 수출 상담','해외 바이어 및 유통 파트너 협력','국가별 제품·자료 검토','영문 사업자료 제공 협의','외부 전문 네트워크를 통한 수출업무 연계'].map(x=><li key={x}>{x}</li>)}</ul><div className="inline-actions"><Button href={inquiryHref('해외 원료공급')}>해외 원료공급 문의</Button><Button href={inquiryHref('완제품 수출')} tone="light">완제품 수출 문의</Button><a className="text-link" href={inquiryHref('해외 유통협력')}>해외 유통협력 문의 →</a></div></section><section><SectionHeader eyebrow="RESEARCH FOUNDATION" title="연구 경험을 바탕으로 지원합니다"/><p>기운찬은 국내외 특허, 동료평가 논문, 안전성 연구와 인체적용시험으로 이어진 연구 경험을 바탕으로 원료와 제품개발 협력을 지원합니다.</p><div className="inline-actions"><a className="text-link" href="/technology/patents">특허 →</a><a className="text-link" href="/technology/publications">연구논문 →</a><a className="text-link" href="/technology/clinical-study">인체적용시험 →</a><a className="text-link" href="/technology">Technology 전체 보기 →</a></div></section><section><SectionHeader eyebrow="PRACTICAL GUIDE" title="사업협력 자주 묻는 질문"/><FAQ items={businessFaq}/></section></div>;
}
function ProductList(){return <><div className="product-grid">{products.map(item=><ProductCard item={item} key={item.slug}/>)}</div><p className="notice">판매 여부·원재료·영양정보·섭취방법·주의사항은 공식 판매처와 제품 포장의 최신 정보를 확인해 주세요.</p><Button href={shop}>공식 쇼핑몰</Button></>}
function BrandStory(){return <><article className="dodoon-story" aria-labelledby="dodoon-title">
 <p className="dodoon-eyebrow">● BRAND STORY</p>
 <div className="dodoon-brand-heading"><div><div className="dodoon-wordmark" aria-label="도두On"><span>도</span><span>두</span><span>On</span></div><p className="dodoon-english">dodoon</p>
 <h2 id="dodoon-title">매일의 건강을 <span>돋우다.</span><br/>기운을 다시 세우는 하루.</h2>
 </div><Image className="dodoon-brand-logo" src="/assets/dodoon-official-logo.jpg" alt="도두On 브랜드 로고" width={900} height={1100} unoptimized/></div>
 <p className="dodoon-intro">가라앉은 기운을 다시 세우고, 흐릿해진 컨디션을 또렷하게 끌어올리는 일. <strong>도두On</strong>은 ‘돋우다’에서 시작된 이름입니다. ‘온’으로 읽는 <strong>‘On’</strong>에는 온(溫)의 따뜻함을 담아, 몰아치지 않고 매일 조금씩 더하는 건강을 지향합니다.</p>
 <ol className="dodoon-values">
  <li><span className="dodoon-number">01</span><div><h3>근거 있는 건강</h3><p>좋다고 알려진 것이 아니라, 왜 좋은지 설명할 수 있는 것만 담습니다.</p></div></li>
  <li><span className="dodoon-number">02</span><div><h3>매일 지킬 수 있는 건강</h3><p>부담 없이 반복할 수 있도록, 먹기 쉽고 챙기기 쉬운 형태를 고민합니다.</p></div></li>
  <li><span className="dodoon-number">03</span><div><h3>사람을 향한 건강</h3><p>성분 그 자체보다, 그것이 누군가의 하루를 어떻게 바꾸는지를 먼저 생각합니다.</p></div></li>
 </ol>
 <div className="dodoon-signoff"><p>매일, 건강을 <span>돋우다.</span></p><div>건강을 돋우는 종합 건강 브랜드<br/><strong>기운찬</strong> · 도두On</div></div>
 </article><div className="inline-actions"><Button href="/brands/dodoon/products">도두On 제품 보기</Button><a className="text-link" href={inquiryHref('제품·유통')}>제품·유통 문의 →</a></div></>}
const gmkFaq=[{q:'GMK®는 무엇인가요?',a:'기운찬이 연구·개발한 복합버섯균사체 바이오소재입니다. 연구와 원료사업의 핵심 소재를 가리키는 명칭입니다.'},{q:'GMK®와 GMK® 추출물은 같은 뜻인가요?',a:'GMK®는 소재의 명칭이며 추출물은 해당 소재에서 추출한 성분을 포함하는 연구·활용 대상을 말합니다. 연구를 읽을 때는 원료명과 시료 형태를 구분해야 합니다.'},{q:'연구 결과는 판매제품에도 그대로 적용되나요?',a:'그렇지 않습니다. 연구 시료, 사용량, 시험 대상과 판매제품의 원료 구성·섭취 조건은 다를 수 있습니다. 연구원료의 결과를 개별 완제품의 효능으로 연결하지 않습니다.'}];
function InsightContent({mycelia=false}:{mycelia?:boolean}){return mycelia?<article className="article-detail"><h2>균사체와 자실체는 무엇이 다른가요?</h2><p>균사체는 가느다란 균사가 모여 형성한 몸체입니다. 우리가 흔히 버섯이라고 부르는 눈에 보이는 부분은 포자를 만드는 자실체를 가리키는 경우가 많습니다. 두 용어는 같은 구조를 뜻하지 않습니다.</p><h2>생활사 속 균사체</h2><p>일반적으로 포자가 적합한 환경에서 발아하면 균사가 자라 균사체를 형성합니다. 균사체는 주변 환경에서 영양분을 이용하며 성장하고, 종과 환경에 따라 자실체를 형성할 수 있습니다.</p><h2>연구 소재로 이해하기</h2><p>균사체라는 명칭만으로 성분이나 기능이 모두 같다고 볼 수 없습니다. 원료와 연구 시료의 정의, 시험 방법을 구분해 살펴야 합니다.</p><FAQ items={[{q:'균사체는 버섯의 뿌리인가요?',a:'식물의 뿌리와는 다른 균류의 구조입니다. 이해를 돕는 비유로 쓰일 수 있지만 과학적으로 같은 기관은 아닙니다.'},{q:'모든 균사체가 동일한 특성을 가지나요?',a:'아닙니다. 종류와 성장환경에 따라 달라질 수 있으며 한 연구의 결과를 모든 균사체에 일반화하면 안 됩니다.'}]}/></article>:<article className="article-detail"><h2>GMK®의 공식 정의</h2><p>GMK®는 주식회사 기운찬이 연구·개발한 복합버섯균사체 바이오소재입니다. 연구·개발과 기업의 원료 활용을 연결하는 기운찬의 핵심 소재입니다.</p><h2>소재, 추출물, 완제품을 구분합니다</h2><p>연구자료를 읽을 때에는 GMK® 소재 자체인지, 추출물인지, 소비자에게 판매되는 완제품인지 먼저 확인해야 합니다. 각각의 정의와 사용 목적이 다르므로 같은 대상으로 간주하지 않습니다.</p><div id="faq"><FAQ items={gmkFaq}/></div><p className="notice">특허·논문·인체적용시험은 TECHNOLOGY에서 확인할 수 있습니다. 비공개 기술정보는 홈페이지에서 제공하지 않습니다.</p><Button href="/technology">공식 연구성과 보기</Button></article>}
function PageBody({path}:{path:string}){
 if(path.startsWith('/technology'))return <Technology path={path}/>;
 if(path.startsWith('/business'))return <Business path={path}/>;
 if(path==='/brands'||path==='/brands/dodoon')return <BrandStory/>;
 if(path==='/brands/dodoon/products')return <ProductList/>;
 const product=publicProductFacts.find(x=>path==='/brands/dodoon/products/'+x.slug);
 if(product)return <article className="product-detail"><Photo className="full-image" src={product.image} alt={`${product.name} 제품 이미지`}/><div><Title eyebrow="DODOON PRODUCT" title={product.name} copy={product.summary}/><dl className="brand-detail-list"><div><dt>식품유형</dt><dd>{product.foodType}</dd></div><div><dt>구분</dt><dd>{product.classification}</dd></div><div><dt>내용량</dt><dd>{product.amount}</dd></div><div><dt>원료 안내</dt><dd>{product.gmk}</dd></div>{product.manufacturer&&<div><dt>제조원</dt><dd>{product.manufacturer}</dd></div>}<div><dt>이용방법</dt><dd>{product.method||'제품 포장의 최신 안내를 확인해 주세요.'}</dd></div><div><dt>보관방법</dt><dd>{product.storage||'제품 포장의 최신 안내를 확인해 주세요.'}</dd></div></dl><p className="notice">원재료, 영양정보, 섭취방법과 주의사항은 제품 포장 및 공식 판매처의 최신 표시사항을 확인해 주세요.</p><Button href={shop}>공식 쇼핑몰에서 확인</Button></div></article>;
 if(path==='/insight')return <InsightCards/>;
 if(path.startsWith('/insight/gmk'))return <InsightContent/>;
 if(path.startsWith('/insight/mycelia'))return <InsightContent mycelia/>;
 if(path==='/newsroom/issues')return <><Title eyebrow="INDUSTRY & RESEARCH" title="산업·연구 이슈" copy="버섯균사체·천연물 바이오소재 산업의 정책, 시장과 주요 연구 발표를 다룹니다."/><div className="notice"><h3>현재 공개된 산업·연구 이슈가 없습니다.</h3><p>출처가 확인된 내용을 ‘발표 내용 → 기운찬과의 관련성 → 해석 → 원문 출처’ 순서로 정리해 게시합니다.</p></div><Button href="/newsroom/news">기운찬 뉴스 보기</Button></>;
 if(path==='/newsroom'||path==='/newsroom/news')return <>{path==='/newsroom'&&<div className="inline-actions section-link"><a className="text-link" href="/newsroom/news">기운찬 뉴스</a><a className="text-link" href="/newsroom/issues">산업·연구 이슈</a></div>}<NewsList/></>;
 return null;
}
export function SitePage({path}:{path:string}){
 if(path==='/')return <Home/>;
 if(path==='/brands')return <Layout><BrandsPage/></Layout>;
 if(path==='/insight'||path==='/newsroom'||path.startsWith('/insight/')||path.startsWith('/newsroom/'))return <Layout><ContentPage path={path}/></Layout>;
 const product=products.find(x=>path==='/brands/dodoon/products/'+x.slug);
 const insight=insights.find(x=>x.href===path);
 const info=pages[path]||(product?{section:'BRANDS · PRODUCTS',title:product.name,lead:product.summary,image:product.image}:insight?{section:'INSIGHT · '+insight.category,title:insight.title,lead:insight.desc,image:insight.image}:null);
 if(!info){if(path==='/privacy'||path==='/terms')return <Layout><main className="section"><div className="shell"><Title eyebrow="INFORMATION" title="홈페이지 이용 및 개인정보 안내"/><p>현재 문의 폼은 시연용이며 작성 내용이 서버에 저장되거나 전송되지 않습니다. 실제 문의는 이메일 또는 전화로 연락해 주세요.</p><p>실제 온라인 접수 기능을 도입할 때 수집 항목·목적·보유기간·담당자 등 정식 처리방침을 별도로 안내합니다.</p><Button href={contactHref}>문의 안내</Button></div></main></Layout>;notFound();}
 const domain=path.split('/')[1]||'company';
 const routeClass=' route-'+path.slice(1).replaceAll('/','-');
 return <Layout><main className={'subpage page-'+domain+routeClass}><Hero {...info} path={path}/><nav className="breadcrumb shell" aria-label="현재 위치"><a href="/">HOME</a><span>/</span><span>{info.section}</span></nav>{path==='/company'?<Company/>:<section className="section subpage-content"><div className="shell"><PageBody path={path}/></div></section>}</main></Layout>
}
