import Image from 'next/image';
import { getHeroImages } from '@/lib/hero-images';
import { notFound } from 'next/navigation';
import { ArrowRight } from 'lucide-react';
import { Header, FAQ, ContactForm } from './site-client';
import { companyDefinition, contactHref, inquiryHref, insights, news, pages, products, stats, type PageInfo } from '@/lib/site-data';

const shop='https://smartstore.naver.com/gucmall';
const researchNotice='연구원료와 판매제품은 구분됩니다. 연구 결과는 개별 판매제품의 효능 또는 질병의 진단·예방·치료를 의미하지 않습니다.';
function Photo({src,alt,className='',priority=false}:{src:string;alt:string;className?:string;priority?:boolean}) {
 return <Image src={src} alt={alt} width={1920} height={1080} className={className} priority={priority} unoptimized/>;
}
function Button({href,children}:{href:string;children:React.ReactNode}) {return <a className="button dark" href={href}>{children}<ArrowRight size={16}/></a>}
function Title({eyebrow,title,copy}:{eyebrow:string;title:string;copy?:string}) {return <div className="section-title"><small>{eyebrow}</small><h2>{title}</h2>{copy&&<p>{copy}</p>}</div>}
function Footer(){return <footer><div className="shell footer-grid"><div><Photo src="/assets/giunchan-logo.png" alt="주식회사 기운찬"/><p>주식회사 기운찬<br/>Giunchan Co., Ltd.</p></div><div><b>CONTACT</b><p>충남 천안시 동남구 충절로 252, 2F<br/>T 041-579-2203 · F 041-585-2203</p><a href="mailto:guc2203@guc.co.kr">guc2203@guc.co.kr</a></div><div><b>COMPANY</b><a href="/company#information">회사 기본정보</a><a href="/company#location">오시는 길</a><a href="/privacy">개인정보 안내</a></div><div><Button href={contactHref}>문의하기</Button><a href={shop} target="_blank" rel="noreferrer">공식 쇼핑몰 ↗</a></div></div><div className="shell copyright">© 2026 Giunchan Co., Ltd. All rights reserved.</div></footer>}
function Layout({children}:{children:React.ReactNode}){return <><Header/>{children}<Footer/></>}
function Hero({section,title,lead,image,home=false,path='/'}:PageInfo&{home?:boolean;path?:string}){const hero=getHeroImages(path);return <section className={'hero '+(home?'home-hero':'')}><picture className="responsive-hero"><source media="(max-width: 680px)" srcSet={hero.mobile}/><Image src={hero.desktop} alt="" width={1920} height={home?900:620} priority unoptimized/></picture><div className="hero-shade"/><div className="shell hero-copy"><small>{section}</small><h1>{title.split('\n').map(line=><span key={line}>{line}</span>)}</h1><p>{lead}</p>{home&&<div className="hero-actions"><a className="button light" href="/company">기운찬 알아보기 <ArrowRight size={16}/></a><a className="button ghost" href={inquiryHref('GMK® 원료')}>GMK® 원료사업 문의</a></div>}</div></section>}
function Stats(){return <div className="stats final-stats">{stats.map(item=><a href={item.href} key={item.label}><strong>{item.value}<em>{item.value==='175'?'명':item.value==='4'?'편':'건'}</em></strong><b>{item.label}</b><span>{item.note}</span><span className="stat-link">연구 근거 보기 →</span></a>)}</div>}
function InsightCards(){return <div className="card-grid final-two">{insights.map(item=><a className="article-card" href={item.href} key={item.href}><Photo src={item.image} alt=""/><small>{item.category}</small><h3>{item.title}</h3><p>{item.desc}</p></a>)}</div>}
function NewsList({compact=false}:{compact?:boolean}){return <div className="news-list">{news.slice(0,compact?3:news.length).map(item=><article key={item.href}><span>{item.source} · {item.date}</span><h2>{item.title}</h2><p>{item.summary}</p>{!compact&&<p><b>기운찬과의 관련성 · 해석</b><br/>{item.meaning}</p>}<a className="text-link" href={item.href} target="_blank" rel="noreferrer">기존 홈페이지에 게재된 원문 출처 ↗</a></article>)}</div>}
function InquiryCta(){return <section className="section contact-band compact-cta"><div className="shell"><small>BUSINESS INQUIRY</small><h2>함께할 가능성을 이야기해 주세요.</h2><p>GMK® 원료 공급, 제품개발, 국내외 사업 협력을 위한 문의를 기다립니다.</p><a className="button orange" href={contactHref}>사업 문의하기 <ArrowRight size={16}/></a></div></section>}
function Home(){return <Layout><main>
 <Hero home section="NATURAL BIO MATERIAL COMPANY" title={'자연을 이해하는 섬세함,\n가능성을 증명하는 과학'} lead="기운찬은 버섯균사체의 가능성을 연구하고 사람의 건강한 일상으로 연결합니다." image="/assets/forest-mycelia.webp"/>
 <section className="section home-definition"><div className="shell"><Title eyebrow="GIUNCHAN" title={companyDefinition}/></div></section>
 <section className="section research-summary"><div className="shell"><Title eyebrow="RESEARCH EVIDENCE" title="10년 이상, 근거를 쌓아온 연구"/><Stats/></div></section>
 <section className="section warm"><div className="shell"><Title eyebrow="FROM RESEARCH TO LIFE" title="연구에서 원료로, 원료에서 일상으로"/><div className="pillar-grid">{[['TECHNOLOGY','근거를 쌓는 연구','/technology'],['B2B BUSINESS','연구에서 원료사업으로','/business/ingredient'],['도두On','연구에서 일상으로','/brands/dodoon']].map(([name,desc,href],i)=><a key={href} href={href}><span>0{i+1}</span><h3>{name}</h3><p>{desc}</p><ArrowRight/></a>)}</div></div></section>
 <section className="section"><div className="shell split"><Photo className="feature-image full-image" src="/assets/gmk-landscape-dark.webp" alt="기운찬 핵심 바이오소재 GMK®"/><div><Title eyebrow="CORE MATERIAL" title="GMK® 복합버섯균사체" copy="GMK®는 주식회사 기운찬이 연구·개발한 복합버섯균사체 바이오소재입니다. 기운찬의 연구와 원료사업을 연결하는 핵심 소재입니다."/><div className="inline-actions"><Button href="/insight/gmk">GMK® 알아보기</Button><a className="text-link" href="/business/ingredient">B2B 원료사업 →</a></div></div></div></section>
 <section className="section sage"><div className="shell"><Title eyebrow="LATEST INSIGHT" title="GMK®와 버섯균사체를 이해하다"/><InsightCards/></div></section>
 <section className="section"><div className="shell"><Title eyebrow="LATEST NEWSROOM" title="기운찬의 새로운 소식"/><NewsList compact/><div className="section-link"><Button href="/newsroom/news">기운찬 뉴스 더 보기</Button></div></div></section>
 <InquiryCta/>
 </main></Layout>}
function Company(){return <>
 <section id="about" className="section"><div className="shell"><Title eyebrow="WHO WE ARE" title="기운찬은 어떤 회사인가" copy={companyDefinition}/><div className="article-detail wide-copy"><p>핵심 소재 GMK®를 중심으로 연구 근거를 축적하고, 기업의 원료 활용과 소비자 제품개발을 연결합니다. 자연의 가능성을 관찰하는 태도와 공개 가능한 근거를 바탕으로 책임 있게 소통합니다.</p><a className="text-link" href="/technology">특허·논문·인체적용시험 연구 근거 →</a></div></div></section>
 <section className="section warm"><div className="shell"><Title eyebrow="OUR BUSINESS" title="두 가지 방향, 하나의 연구 기반"/><div className="business-weighted"><article><small>B2B INGREDIENT</small><h3>B2B 원료사업</h3><p>복합버섯균사체 소재 GMK®를 기반으로 기업의 연구와 제품기획에 맞는 원료 협력을 추진합니다. 식품·음료 적용, 공동기획, 국내외 공급과 유통 가능성을 함께 검토합니다.</p><Button href="/business/ingredient">B2B 원료사업</Button></article><article><small>B2C DEVELOPMENT</small><h3>B2C 제품개발</h3><p>소재의 특성과 소비자 요구를 고려해 식품·음료·건강 관련 제품을 기획합니다. 자체 브랜드와 파트너사의 제품개발을 통해 연구를 일상으로 연결합니다.</p><Button href="/business/product-development">B2C 제품개발</Button></article></div></div></section>
 <section id="ceo" className="section"><div className="shell ceo-layout"><Photo src="/assets/ceo.webp" alt="주식회사 기운찬 박종례 대표" className="ceo-portrait"/><div><Title eyebrow="MESSAGE FROM CEO" title="버섯의 무한한 가능성을\n책임 있는 연구로 이어갑니다"/><p>처음 버섯균사체를 마주했을 때, 작은 생명체 안에 건강한 삶을 위한 가능성이 있다고 믿었습니다. 그 믿음으로 10년이 넘는 시간 동안 연구하고 실험하며 근거를 쌓아왔습니다.</p><p>기운찬은 속도보다 깊이를, 유행보다 근거를 중요하게 생각합니다. 연구의 원리를 살피고 확인된 정보의 범위 안에서 소통하겠습니다.</p><p>이제 연구·개발한 소재를 기업의 원료와 소비자의 제품으로 연결하고자 합니다. 더 많은 사람이 일상에서 자연의 가치를 경험할 수 있도록 노력하겠습니다.</p><p>연구 결과와 판매제품을 구분하고, 필요한 정보를 정확하게 전달하는 책임 있는 사업을 이어가겠습니다.</p><b>주식회사 기운찬 대표 박종례</b></div></div></section>
 <section id="information" className="section warm"><div className="shell"><Title eyebrow="COMPANY FACTS" title="회사 기본정보"/><Facts rows={[['회사명','주식회사 기운찬'],['영문명','Giunchan Co., Ltd.'],['대표자','박종례'],['설립연도','2015년 · 기존 회사 소개자료 기준'],['주요 분야','천연물 바이오소재 연구·개발 / B2B 원료사업 / B2C 제품개발'],['핵심 소재','GMK® 복합버섯균사체'],['소재지','충남 천안시 동남구 충절로 252, 2F']]}/></div></section>
 <section id="location" className="section"><div className="shell"><Title eyebrow="LOCATION" title="오시는 길" copy="충남 천안시 동남구 충절로 252, 2F"/><div className="location-grid"><iframe title="주식회사 기운찬 위치 지도" src={'https://maps.google.com/maps?q='+encodeURIComponent('충남 천안시 동남구 충절로 252')+'&output=embed'} loading="lazy" referrerPolicy="no-referrer-when-downgrade"/><div><h3>방문 안내</h3><p>길찾기에서 위 도로명 주소를 검색해 주세요. 방문 전 전화로 일정을 확인하시면 안내해 드립니다.</p><p>대표전화 <a href="tel:0415792203">041-579-2203</a><br/>팩스 041-585-2203<br/><a href="mailto:guc2203@guc.co.kr">guc2203@guc.co.kr</a></p><a className="text-link" href={'https://map.naver.com/p/search/'+encodeURIComponent('충남 천안시 동남구 충절로 252')} target="_blank" rel="noreferrer">네이버 지도에서 길찾기 ↗</a></div></div></div></section>
 <section id="contact" className="section sage"><div className="shell"><Title eyebrow="CONTACT GIUNCHAN" title="문의하기" copy="GMK® 원료, B2C 제품개발, 제품·유통, 국내외 사업 등 문의 목적을 선택해 주세요."/><p className="notice">현재 문의 폼은 작성 시연용이며 전송·저장되지 않습니다. 실제 상담은 <a href="mailto:guc2203@guc.co.kr">guc2203@guc.co.kr</a> 또는 <a href="tel:0415792203">041-579-2203</a>로 연락해 주세요.</p><ContactForm/></div></section>
 </>}
function Facts({rows}:{rows:string[][]}){return <div className="table-wrap"><table className="facts-table"><tbody>{rows.map(([key,value])=><tr key={key}><th scope="row">{key}</th><td>{value}</td></tr>)}</tbody></table></div>}
function Technology({path}:{path:string}) {
 if(path==='/technology/patents')return <><Title eyebrow="INTELLECTUAL PROPERTY" title="국내 9건 · 미국 1건" copy="회사 공개자료 기준 총 10건의 특허를 보유하고 있습니다."/><Facts rows={[['공개 확인 사항','GMK® 관련 원천기술의 미국 특허등록 결정 소식 · 2022년 8월'],['등록 국가','대한민국 / 미국'],['개별 특허명·등록번호·일자·상태','등록증과 원문 확인 후 공개할 항목입니다. 현재는 총 보유 건수와 공개된 보도 범위만 안내합니다.'],['공개 범위','버섯 종류, 균주, 배합, 배양조건, 상세 제조공정은 게시하지 않습니다.']]}/><p className="notice">특허는 기술 권리에 대한 정보이며 제품의 기능성 승인이나 효능 보증을 뜻하지 않습니다.</p><Button href={inquiryHref('GMK® 원료')}>특허 관련 공개자료 문의</Button></>;
 if(path==='/technology/publications')return <><Title eyebrow="PUBLICATIONS" title="SCIE급 국제학술지 논문 4편" copy="회사에서 공개한 연구성과를 연구 유형과 함께 소개합니다."/><Facts rows={[['2025년 · Cells','건양대학교 의과대학 연구팀과 신경세포 관련 공동연구 발표 · 세포 기반 전임상 연구'],['2023년 및 이전 연구','GMK® 관련 전임상 공동연구 소식이 공개돼 있습니다. 개별 논문 원문을 기준으로 확인해야 합니다.'],['논문명·DOI·기관·발표일','정확한 서지정보와 원문을 확인한 뒤 공개할 항목입니다. 확인되지 않은 DOI를 임의로 기재하지 않습니다.']]}/><p className="notice">{researchNotice}</p><a className="text-link" href="https://www.guc.co.kr/forum/view/355080" target="_blank" rel="noreferrer">2025년 공동연구 보도 출처 ↗</a></>;
 if(path==='/technology/clinical-study')return <><Title eyebrow="HUMAN STUDY" title="175명 대상 인체적용시험 완료" copy="회사 공개자료에서 확인되는 범위와 추가 확인이 필요한 항목을 구분합니다."/><Facts rows={[['연구 목적','GMK® 관련 인체적용 근거 확인 · 상세 평가 목적은 시험자료 확인 필요'],['대상자 수','175명 · 회사 공개자료 기준'],['진행 단계','시험 완료 · 회사 공개자료 기준'],['시험 설계·기관·기간','공개 가능한 시험보고서 확인 후 안내'],['확인 결과·안전성','결과 수치 및 안전성 평가는 현재 제공된 자료에서 확인되지 않아 기재하지 않습니다.']]}/><p className="notice">{researchNotice} 시험 완료 사실만으로 특정 효과나 안전성을 단정하지 않습니다.</p><Button href={inquiryHref('GMK® 원료')}>인체적용시험 공개자료 문의</Button></>;
 return <><Title eyebrow="RESEARCH MILESTONES" title="연구를 이어온 기록" copy="공개된 회사 자료와 주요 보도를 기준으로 정리했습니다."/><ol className="timeline">{[['10년 이상','버섯균사체 연구','기운찬은 장기간 버섯균사체의 소재 가능성을 연구해 왔습니다.'],['2021','원료 사업화 기반','GMK®의 대량 생산 관련 소식과 산학 공동연구 성과가 공개됐습니다.'],['2022','미국 특허등록 결정','GMK® 관련 원천기술의 미국 특허등록 결정 소식을 발표했습니다.'],['2023','산학 공동연구','건양대학교 의과대학 연구팀과 GMK® 전임상 연구 성과를 발표했습니다.'],['2024','인체적용시험 추진','GMK W20 인체적용시험 추진 소식이 보도됐습니다.'],['2025','국제학술지 연구 발표','Cells에 신경세포 관련 공동연구가 발표됐습니다.'],['현재 공개자료','175명 대상 시험 완료','국내외 특허 10건, SCIE급 논문 4편, 인체적용시험 완료를 안내하고 있습니다.']].map(([year,title,text])=><li key={year}><b>{year}</b><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol><div className="inline-actions"><Button href="/technology/patents">특허</Button><Button href="/technology/publications">연구논문</Button><Button href="/technology/clinical-study">인체적용시험</Button></div><p className="notice">{researchNotice}</p></>;
}
function Business({path}:{path:string}){
 const b2c=path==='/business/product-development';
 const b2b=<><Title eyebrow="B2B INGREDIENT BUSINESS" title="GMK®를 기반으로 기업의 가능성을 넓힙니다" copy="주식회사 기운찬은 복합버섯균사체 소재 GMK®를 기반으로 기업의 연구, 제품기획 및 사업 목적에 맞는 원료 협력을 추진합니다."/><ul className="service-list">{['GMK® 원료 공급','식품·음료 적용 검토','제품 공동기획 및 개발','국내외 공급·유통 협력','연구 및 사업자료 제공'].map(x=><li key={x}>{x}</li>)}</ul><p className="notice">홈페이지에는 원료의 성격과 협력 가능 분야만 공개합니다. 세부 제조공정, 배합·배양조건, 내부 품질규격, 원료 단가와 거래조건, 비공개 시험자료는 상담 후 필요한 범위에서 제공합니다.</p><Button href={inquiryHref('GMK® 원료')}>GMK® 원료사업 문의</Button></>;
 const consumer=<><Title eyebrow="B2C PRODUCT DEVELOPMENT" title="연구한 소재를 일상의 제품으로" copy="단순한 판매를 넘어 소재 특성과 소비자 요구를 고려한 식품·음료·건강 관련 제품을 기획하고 개발합니다."/><ul className="service-list">{['소비자 요구를 고려한 제품기획','원료 특성에 맞는 제형 검토','자체 브랜드 제품개발','파트너사와의 공동 제품개발'].map(x=><li key={x}>{x}</li>)}</ul><div className="inline-actions"><Button href={inquiryHref('B2C 제품개발')}>제품개발 문의</Button><a className="text-link" href="/brands/dodoon">도두On 브랜드 보기 →</a></div></>;
 return path==='/business'?<div className="business-overview"><div>{b2b}</div><aside><Title eyebrow="B2C DEVELOPMENT" title="소비자의 일상으로"/><p>연구한 소재를 식품·음료·건강 관련 제품으로 기획하고 개발합니다. 자체 브랜드와 파트너 협력을 통해 소비자와 만납니다.</p><Button href="/business/product-development">B2C 제품개발</Button></aside></div>:b2c?consumer:b2b;
}
function ProductList(){return <><div className="product-grid">{products.map(item=><a href={'/brands/dodoon/products/'+item.slug} key={item.slug}><Photo src={item.image} alt={item.name}/><small>GIUNCHAN PRODUCT</small><h3>{item.name}</h3><p>{item.summary}</p></a>)}</div><p className="notice">판매 여부·원재료·영양정보·섭취방법·주의사항은 공식 판매처와 제품 포장의 최신 정보를 확인해 주세요.</p><Button href={shop}>공식 쇼핑몰</Button></>}
function BrandStory(){return <><article className="dodoon-story" aria-labelledby="dodoon-title">
 <p className="dodoon-eyebrow">● BRAND STORY</p>
 <div className="dodoon-wordmark" aria-label="도두온 dodoon"><span>도</span><span>두</span><span>온</span></div><p className="dodoon-english">dodoon</p>
 <h2 id="dodoon-title">매일의 건강을 <span>돋우다.</span><br/>기운을 다시 세우는 하루.</h2>
 <p className="dodoon-intro">가라앉은 기운을 다시 세우고, 흐릿해진 컨디션을 또렷하게 끌어올리는 일. <strong>도두온</strong>은 ‘돋우다’에서 시작된 이름입니다. 끝 글자 <strong>‘온(溫)’</strong>에는 따뜻함을 담아, 몰아치지 않고 매일 조금씩 더하는 건강을 지향합니다.</p>
 <ol className="dodoon-values">
  <li><span className="dodoon-number">01</span><div><h3>근거 있는 건강</h3><p>좋다고 알려진 것이 아니라, 왜 좋은지 설명할 수 있는 것만 담습니다.</p></div></li>
  <li><span className="dodoon-number">02</span><div><h3>매일 지킬 수 있는 건강</h3><p>부담 없이 반복할 수 있도록, 먹기 쉽고 챙기기 쉬운 형태를 고민합니다.</p></div></li>
  <li><span className="dodoon-number">03</span><div><h3>사람을 향한 건강</h3><p>성분 그 자체보다, 그것이 누군가의 하루를 어떻게 바꾸는지를 먼저 생각합니다.</p></div></li>
 </ol>
 <div className="dodoon-signoff"><p>매일, 건강을 <span>돋우다.</span></p><div>건강을 돋우는 종합 건강 브랜드<br/><strong>기운찬</strong> · 도두온</div></div>
 </article><div className="inline-actions"><Button href="/brands/dodoon/products">도두온 제품 보기</Button><a className="text-link" href={inquiryHref('제품·유통')}>제품·유통 문의 →</a></div></>}
const gmkFaq=[{q:'GMK®는 무엇인가요?',a:'기운찬이 연구·개발한 복합버섯균사체 바이오소재입니다. 연구와 원료사업의 핵심 소재를 가리키는 명칭입니다.'},{q:'GMK®와 GMK® 추출물은 같은 뜻인가요?',a:'GMK®는 소재의 명칭이며 추출물은 해당 소재에서 추출한 성분을 포함하는 연구·활용 대상을 말합니다. 연구를 읽을 때는 원료명과 시료 형태를 구분해야 합니다.'},{q:'연구 결과는 판매제품에도 그대로 적용되나요?',a:'그렇지 않습니다. 연구 시료, 사용량, 시험 대상과 판매제품의 원료 구성·섭취 조건은 다를 수 있습니다. 연구원료의 결과를 개별 완제품의 효능으로 연결하지 않습니다.'}];
function InsightContent({mycelia=false}:{mycelia?:boolean}){return mycelia?<article className="article-detail"><h2>균사체와 자실체는 무엇이 다른가요?</h2><p>균사체는 가느다란 균사가 모여 형성한 몸체입니다. 우리가 흔히 버섯이라고 부르는 눈에 보이는 부분은 포자를 만드는 자실체를 가리키는 경우가 많습니다. 두 용어는 같은 구조를 뜻하지 않습니다.</p><h2>생활사 속 균사체</h2><p>일반적으로 포자가 적합한 환경에서 발아하면 균사가 자라 균사체를 형성합니다. 균사체는 주변 환경에서 영양분을 이용하며 성장하고, 종과 환경에 따라 자실체를 형성할 수 있습니다.</p><h2>연구 소재로 이해하기</h2><p>균사체라는 명칭만으로 성분이나 기능이 모두 같다고 볼 수 없습니다. 원료와 연구 시료의 정의, 시험 방법을 구분해 살펴야 합니다.</p><FAQ items={[{q:'균사체는 버섯의 뿌리인가요?',a:'식물의 뿌리와는 다른 균류의 구조입니다. 이해를 돕는 비유로 쓰일 수 있지만 과학적으로 같은 기관은 아닙니다.'},{q:'모든 균사체가 동일한 특성을 가지나요?',a:'아닙니다. 종류와 성장환경에 따라 달라질 수 있으며 한 연구의 결과를 모든 균사체에 일반화하면 안 됩니다.'}]}/></article>:<article className="article-detail"><h2>GMK®의 공식 정의</h2><p>GMK®는 주식회사 기운찬이 연구·개발한 복합버섯균사체 바이오소재입니다. 연구·개발과 기업의 원료 활용을 연결하는 기운찬의 핵심 소재입니다.</p><h2>소재, 추출물, 완제품을 구분합니다</h2><p>연구자료를 읽을 때에는 GMK® 소재 자체인지, 추출물인지, 소비자에게 판매되는 완제품인지 먼저 확인해야 합니다. 각각의 정의와 사용 목적이 다르므로 같은 대상으로 간주하지 않습니다.</p><div id="faq"><FAQ items={gmkFaq}/></div><p className="notice">특허·논문·인체적용시험은 TECHNOLOGY에서 확인할 수 있습니다. 비공개 기술정보는 홈페이지에서 제공하지 않습니다.</p><Button href="/technology">공식 연구성과 보기</Button></article>}
function PageBody({path}:{path:string}){
 if(path.startsWith('/technology'))return <Technology path={path}/>;
 if(path.startsWith('/business'))return <Business path={path}/>;
 if(path==='/brands'||path==='/brands/dodoon')return <BrandStory/>;
 if(path==='/brands/dodoon/products')return <ProductList/>;
 const product=products.find(x=>path==='/brands/dodoon/products/'+x.slug);
 if(product)return <div className="product-detail"><Photo className="full-image" src={product.image} alt={product.name}/><div><Title eyebrow="PRODUCT INFORMATION" title={product.name} copy={product.summary}/><p>원재료, 영양정보, 섭취방법과 주의사항은 제품 포장 및 공식 판매처의 최신 표시사항을 확인해 주세요.</p><Button href={shop}>공식 쇼핑몰에서 확인</Button></div></div>;
 if(path==='/insight')return <InsightCards/>;
 if(path.startsWith('/insight/gmk'))return <InsightContent/>;
 if(path.startsWith('/insight/mycelia'))return <InsightContent mycelia/>;
 if(path==='/newsroom/issues')return <><Title eyebrow="INDUSTRY & RESEARCH" title="산업·연구 이슈" copy="버섯균사체·천연물 바이오소재 산업의 정책, 시장과 주요 연구 발표를 다룹니다."/><div className="notice"><h3>현재 공개된 산업·연구 이슈가 없습니다.</h3><p>출처가 확인된 내용을 ‘발표 내용 → 기운찬과의 관련성 → 해석 → 원문 출처’ 순서로 정리해 게시합니다.</p></div><Button href="/newsroom/news">기운찬 뉴스 보기</Button></>;
 if(path==='/newsroom'||path==='/newsroom/news')return <>{path==='/newsroom'&&<div className="inline-actions section-link"><a className="text-link" href="/newsroom/news">기운찬 뉴스</a><a className="text-link" href="/newsroom/issues">산업·연구 이슈</a></div>}<NewsList/></>;
 return null;
}
export function SitePage({path}:{path:string}){
 if(path==='/')return <Home/>;
 const product=products.find(x=>path==='/brands/dodoon/products/'+x.slug);
 const insight=insights.find(x=>x.href===path);
 const info=pages[path]||(product?{section:'BRANDS · PRODUCTS',title:product.name,lead:product.summary,image:product.image}:insight?{section:'INSIGHT · '+insight.category,title:insight.title,lead:insight.desc,image:insight.image}:null);
 if(!info){if(path==='/privacy'||path==='/terms')return <Layout><main className="section"><div className="shell"><Title eyebrow="INFORMATION" title="홈페이지 이용 및 개인정보 안내"/><p>현재 문의 폼은 시연용이며 작성 내용이 서버에 저장되거나 전송되지 않습니다. 실제 문의는 이메일 또는 전화로 연락해 주세요.</p><p>실제 온라인 접수 기능을 도입할 때 수집 항목·목적·보유기간·담당자 등 정식 처리방침을 별도로 안내합니다.</p><Button href={contactHref}>문의 안내</Button></div></main></Layout>;notFound();}
 return <Layout><main><Hero {...info} path={path}/><nav className="breadcrumb shell" aria-label="현재 위치"><a href="/">HOME</a><span>/</span><span>{info.section}</span></nav>{path==='/company'?<Company/>:<section className="section"><div className="shell"><PageBody path={path}/></div></section>}</main></Layout>
}

