'use client';
import { useState } from 'react';
import { Menu, X, ChevronDown, CheckCircle2 } from 'lucide-react';
import { nav } from '@/lib/site-data';

export function Header() { const [open,setOpen]=useState(false); return <header className="site-header"><div className="shell nav-row"><a className="brand" href="/" aria-label="기운찬 홈"><img src="/assets/giunchan-logo.png" alt="주식회사 기운찬" /></a><nav className="desktop-nav" aria-label="주 메뉴">{nav.map(item=><div className="nav-item" key={item.href}><a href={item.href}>{item.label}</a>{item.children.length>0&&<div className="mega"><b>{item.label}</b>{item.children.map(c=><a href={c.href} key={c.href}>{c.label}<span>→</span></a>)}</div>}</div>)}</nav><div className="nav-actions"><button className="lang" aria-label="언어 선택">KR <ChevronDown size={14}/></button><a className="contact-pill" href="/contact">CONTACT</a><button className="menu-toggle" aria-label={open?'메뉴 닫기':'메뉴 열기'} aria-expanded={open} onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></div>{open&&<nav className="mobile-nav" aria-label="모바일 주 메뉴">{nav.map(item=><details key={item.href}><summary><a href={item.href}>{item.label}</a>{item.children.length>0&&<ChevronDown size={16}/>}</summary>{item.children.map(c=><a href={c.href} key={c.href} onClick={()=>setOpen(false)}>{c.label}</a>)}</details>)}</nav>}</header> }
export function FAQ({items}:{items:{q:string;a:string}[]}) { return <div className="faq">{items.map((item,i)=><details key={item.q} open={i===0}><summary>{item.q}<span>+</span></summary><p>{item.a}</p></details>)}</div> }
export function CategoryFilter({categories}:{categories:string[]}) { const [active,setActive]=useState('전체'); return <div className="filters" aria-label="카테고리 필터">{['전체',...categories].map(c=><button className={active===c?'active':''} onClick={()=>setActive(c)} key={c}>{c}</button>)}</div> }
export function ContactForm() { const [done,setDone]=useState(false); if(done)return <div className="form-success"><CheckCircle2/><h2>문의가 접수되었습니다.</h2><p>현재 화면은 전송 흐름을 확인하는 시연용입니다. 실제 메일 또는 CRM에는 저장되지 않습니다.</p><button onClick={()=>setDone(false)} className="button dark">새 문의 작성</button></div>; return <form className="contact-form" onSubmit={e=>{e.preventDefault();setDone(true)}}><div className="field full"><label htmlFor="type">문의 유형 *</label><select id="type" required defaultValue=""><option value="" disabled>문의 유형을 선택해 주세요</option><option>GMK® 원료 문의</option><option>제품 공동개발 문의</option><option>국내외 공급·수출 문의</option><option>도두On 제품·유통 문의</option><option>일반 문의</option></select></div><div className="field"><label htmlFor="company">회사명 *</label><input id="company" required /></div><div className="field"><label htmlFor="name">담당자명 *</label><input id="name" required /></div><div className="field"><label htmlFor="email">이메일 *</label><input id="email" type="email" required /></div><div className="field"><label htmlFor="phone">연락처 *</label><input id="phone" required /></div><div className="field full"><label htmlFor="country">국가</label><input id="country" /></div><div className="field full"><label htmlFor="message">문의 내용 *</label><textarea id="message" rows={7} required /></div><label className="consent"><input type="checkbox" required/> 개인정보 수집 및 이용에 동의합니다. *</label><button className="button orange" type="submit">문의 보내기</button></form> }

