import Image from 'next/image';
import { getHeroImages } from '@/lib/hero-images';
import { notFound } from 'next/navigation';
import { ArrowRight } from 'lucide-react';
import { Header, FAQ, ContactForm } from './site-client';
import { companyDefinition, contactHref, inquiryHref, insights, news, pages, products, type PageInfo } from '@/lib/site-data';

const shop='https://smartstore.naver.com/gucmall';
const researchNotice='연구원료와 판매제품은 구분됩니다. 연구 결과는 개별 판매제품의 효능 또는 질병의 진단·예방·치료를 의미하지 않습니다.';
function Photo({src,alt,className='',priority=false}:{src:string;alt:string;className?:string;priority?:boolean}) {
 return <Image src={src} alt={alt} width={1920} height={1080} className={className} priority={priority} unoptimized/>;
}
function Button({href,children,tone='dark'}:{href:string;children:React.ReactNode;tone?:'dark'|'light'|'orange'|'ghost'}) {return <a className={'button '+tone} href={href}>{children}<ArrowRight size={16}/></a>}
function SectionHeader({eyebrow,title,copy,align='left'}:{eyebrow:string;title:string;copy?:string;align?:'left'|'split'}) {return <div className={'section-title section-title--'+align}><small>{eyebrow}</small><h2>{title}</h2>{copy&&<p>{copy}</p>}</div>}
const Title=SectionHeader;
function ImageTextSplit({image,alt,children,reverse=false,className=''}:{image:string;alt:string;children:React.ReactNode;reverse?:boolean;className?:string}){return <div className={'image-text-split '+(reverse?'is-reverse ':'')+className}><div className="image-text-split__media"><Photo src={image} alt={alt}/></div><div className="image-text-split__body">{children}</div></div>}
function ProductCard({item,feature=false}:{item:(typeof products)[number];feature?:boolean}){const content=<><Photo src={item.image} alt={`${item.name} 제품 이미지`}/><div><small>도두On PRODUCT</small><h3>{item.name}</h3><p>{item.summary}</p>{feature&&<dl className="product-facts"><div><dt>제품 유형</dt><dd>음료</dd></div><div><dt>브랜드</dt><dd>도두On</dd></div><div><dt>개발사</dt><dd>주식회사 기운찬</dd></div><div><dt>구매 안내</dt><dd>공식 쇼핑몰</dd></div></dl>}{feature?<><a className="text-link product-detail-link" href={'/brands/dodoon/products/'+item.slug}>제품 자세히 보기 <ArrowRight size={16}/></a><a className="button dark product-all-link" href="/brands/dodoon/products">도두On 제품 전체 보기 <ArrowRight size={16}/></a></>:<span>제품 보기 <ArrowRight size={16}/></span>}</div></>;return feature?<article className="product-card is-feature">{content}</article>:<a className="product-card" href={'/brands/dodoon/products/'+item.slug}>{content}</a>}
function ArticleCard({item,feature=false}:{item:(typeof insights)[number];feature?:boolean}){return <article className={'editorial-card '+(feature?'is-feature':'')}><Photo src={item.image} alt=""/><div><small>{item.category}</small><h3>{item.title}</h3><p>{item.desc}</p><time dateTime={item.date}>{item.date}</time><a className="text-link" href={item.href}>{item.linkLabel} <ArrowRight size={16}/></a></div></article>}
function Footer(){return <footer><div className="shell footer-grid"><div><Photo src="/assets/giunchan-logo-trimmed.png" alt="주식회사 기운찬"/><p>주식회사 기운찬<br/>Giunchan Co., Ltd.</p></div><div><b>CONTACT</b><p>충남 천안시 동남구 충절로 252, 2F<br/>T 041-579-2203 · F 041-585-2203</p><a href="mailto:guc2203@guc.co.kr">guc2203@guc.co.kr</a></div><div><b>COMPANY</b><a href="/company#information">회사 기본정보</a><a href="/company#location">오시는 길</a><a href="/privacy">개인정보 안내</a></div><div><Button href={contactHref}>문의하기</Button><a href={shop} target="_blank" rel="noreferrer">공식 쇼핑몰 ↗</a></div></div><div className="shell copyright">© 2026 Giunchan Co., Ltd. All rights reserved.</div></footer>}
function Layout({children}:{children:React.ReactNode}){return <><Header/>{children}<Footer/></>}
function Hero({section,title,lead,image:_image,home=false,path='/'}:PageInfo&{home?:boolean;path?:string}){const hero=getHeroImages(path);return <section className={'hero '+(home?'home-hero':'')}><picture className="responsive-hero"><source media="(max-width: 680px)" srcSet={hero.mobile}/><Image src={hero.desktop} alt="" width={1920} height={home?900:620} priority unoptimized/></picture><div className="hero-shade"/><div className="shell hero-copy"><small>{section}</small>{home?<><p className="home-hero-display">{title.split('\n').map(line=><span key={line}>{line}</span>)}</p><h1>복합버섯균사체 바이오소재 전문기업 기운찬</h1></>:<h1>{title.split('\n').map(line=><span key={line}>{line}</span>)}</h1>}<p>{lead}</p>{home&&<div className="hero-actions"><a className="button light" href="/company">기운찬 알아보기 <ArrowRight size={16}/></a><a className="button ghost" href={inquiryHref('GMK® 원료')}>GMK® 원료사업 문의</a></div>}</div></section>}
function InsightCards(){return <div className="editorial-grid">{insights.map((item,i)=><ArticleCard item={item} feature={i===0} key={item.href}/>)}</div>}
function NewsList({compact=false}:{compact?:boolean}){return <div className="news-list">{news.slice(0,compact?3:news.length).map(item=><article key={item.href}><span>{item.source} · {item.date}</span><h2>{item.title}</h2><p>{item.summary}</p>{!compact&&<p><b>기운찬과의 관련성 · 해석</b><br/>{item.meaning}</p>}<a className="text-link" href={item.href} target="_blank" rel="noreferrer">기존 홈페이지에 게재된 원문 출처 ↗</a></article>)}</div>}
function InquiryCta(){return <section className="section contact-band compact-cta"><div className="shell"><small>BUSINESS INQUIRY</small><h2>GMK®와 함께할 가능성을 이야기해 주세요.</h2><p>GMK® 원료 공급, 기술자료, 샘플 검토, 제품 적용, 공동연구 및 국내외 사업 협력에 관한 문의를 기다립니다.</p><a className="button orange" href={inquiryHref('GMK® 원료')}>사업 문의하기 <ArrowRight size={16}/></a></div></section>}
function Home(){const featuredProduct=products[2];const metrics=[{value:'2015',label:'법인 설립',href:'/company#information'},{value:'10',label:'국내 9건·미국 1건 특허',href:'/technology/patents'},{value:'4',label:'GMK 관련 SCIE급 논문',href:'/technology/publications'},{value:'175',label:'인체적용시험 대상자',href:'/technology/clinical-study'}];return <Layout><main className="home-page">
 <Hero home section="NATURAL BIO MATERIAL COMPANY" title={'자연을 이해하는 섬세함,\n가능성을 증명하는 과학'} lead="기운찬은 다양한 버섯 균사체를 곡물 배지에서 복합배양·발효해 핵심 바이오소재 GMK®를 연구·개발하고, 이를 기업용 원료와 소비자 제품으로 연결합니다." image="/assets/forest-mycelia.webp"/>
 <section className="hero-metrics" aria-label="기운찬 핵심 성과"><div className="shell">{metrics.map(item=><a href={item.href} key={item.label}><strong>{item.value}</strong><span>{item.label}</span><i aria-hidden="true">↗</i></a>)}</div><p>연구·지식재산 현황은 2026년 8월 기준입니다.</p></section>
 <section className="section home-gmk"><div className="wide-shell"><ImageTextSplit image="/assets/ingredient-plates.webp" alt="기운찬의 바이오소재 연구 이미지"><SectionHeader eyebrow="GIUNCHAN · CORE MATERIAL" title="버섯의 가능성을 하나의 소재로"/><p>주식회사 기운찬은 학술 연구가 축적된 다양한 버섯의 균사체를 곡물 배지에서 함께 복합배양·발효하는 독자 기술을 기반으로 천연물 바이오소재를 연구·개발하는 식품바이오 기업입니다.</p><p>이 기술로 개발한 GMK®는 기운찬의 연구개발과 기업용 원료사업을 연결하는 핵심 바이오소재입니다. GMK®는 소비자에게 직접 판매되는 완제품명이 아니라 연구와 제품개발에 활용되는 소재·원료 브랜드입니다.</p><p className="gmk-emphasis">다양한 버섯 균사체를 곡물 배지에서 복합배양·발효합니다.</p><ol className="process-line" aria-label="GMK 연구 및 적용 과정"><li>01 균주 및 원료 관리</li><li>02 복합배양·발효</li><li>03 연구 및 품질 검증</li><li>04 원료 적용·제품화</li></ol><div className="inline-actions"><Button href="/insight/gmk">GMK® 자세히 알아보기</Button><a className="text-link" href="/technology">연구성과 보기 →</a><a className="text-link" href="/company">회사소개 →</a></div></ImageTextSplit></div></section>
 <section className="section research-evidence"><div className="shell"><SectionHeader eyebrow="RESEARCH EVIDENCE" title="연구로 쌓아온 근거" copy="기운찬은 독자 기술과 소재의 가능성을 확인하기 위해 특허, 학술 연구, 전임상 연구와 인체적용시험을 단계적으로 진행해 왔습니다."/><div className="evidence-list"><article><strong>10</strong><div><h3>국내외 특허</h3><p>GMK® 생산방법과 활용기술에 관한 국내 특허 9건과 미국 특허 1건을 확보했습니다.</p><a href="/technology/patents">특허 확인하기 →</a></div></article><article><strong>4</strong><div><h3>SCIE급 국제학술지 논문</h3><p>GMK 및 GMK 추출물과 관련한 연구결과를 SCIE급 국제학술지 논문 4편으로 발표했습니다.</p><a href="/technology/publications">연구논문 확인하기 →</a></div></article><article><strong>175</strong><div><h3>인체적용시험</h3><p>2024년 12월부터 2026년 1월까지 고려대학교 구로병원과 김천의료원에서 경도인지장애자 175명을 대상으로 다기관·무작위배정·이중눈가림·위약대조 방식의 인체적용시험을 진행했습니다.</p><a href="/technology/clinical-study">시험 개요 확인하기 →</a></div></article></div><p className="research-disclaimer">소개된 연구결과는 GMK 또는 특정 GMK 추출물에 관한 연구이며, 모든 GMK 적용 제품의 효능을 의미하지 않습니다. 세부 연구대상·방법·결과와 한계는 각 연구 페이지에서 확인할 수 있습니다.</p></div></section>
 <section className="section route-section"><div className="shell"><SectionHeader eyebrow="FROM RESEARCH TO LIFE" title="연구에서 원료로, 원료에서 일상으로" align="split"/><div className="route-split"><a href="/business/ingredient"><small>B2B · INGREDIENT</small><h3>기업을 위한<br/>GMK® 원료사업</h3><p>식품과 건강 관련 제품을 기획하는 기업을 대상으로 GMK® 원료 상담, 규격자료 제공, 샘플 검토, 제품 적용 협의와 공동개발을 진행합니다.</p><b>원료 상담 · 규격자료 · 샘플 검토 · 공동개발</b><span>GMK® 원료사업 알아보기 <ArrowRight/></span></a><a href="/business/product-development"><small>B2C · PRODUCT DEVELOPMENT</small><h3>일상을 위한<br/>제품개발</h3><p>기운찬이 연구·개발한 소재를 음료, 젤리, 농축액 등 소비자가 일상에서 접하기 쉬운 형태의 제품으로 개발합니다.</p><b>음료 · 젤리 · 농축액 · 생활 건강 제품</b><span>제품개발 알아보기 <ArrowRight/></span></a></div></div></section>
 <section className="section product-spotlight"><div className="wide-shell"><SectionHeader eyebrow="DODOON · DAILY WELLNESS" title="과학에서 시작해, 따뜻한 일상으로" copy="도두On은 주식회사 기운찬이 연구한 소재와 식품개발 경험을 소비자의 건강한 일상으로 연결하는 종합 건강 브랜드입니다."/><ProductCard item={featuredProduct} feature/></div></section>
 <section className="section editorial-section"><div className="shell"><SectionHeader eyebrow="LATEST INSIGHT" title="GMK®와 버섯균사체를 이해하다" align="split"/><div className="editorial-grid">{insights.map((item,i)=><ArticleCard item={item} feature={i===0} key={item.href}/>)}</div></div></section>
 <section className="section home-faq"><div className="shell"><SectionHeader eyebrow="PRACTICAL GUIDE" title="자주 묻는 질문"/><FAQ items={[{q:'GMK®는 완제품인가요?',a:'GMK®는 소비자에게 직접 판매되는 완제품명이 아니라 기운찬의 연구와 기업용 원료사업에 활용되는 바이오소재 브랜드입니다. GMK 관련 소재가 적용된 소비자 제품은 별도의 브랜드와 제품명으로 판매됩니다.'},{q:'GMK®에는 어떤 연구 근거가 있나요?',a:'GMK®의 생산방법과 활용기술에 관한 국내외 특허, SCIE급 국제학술지 논문, 전임상 연구와 175명 대상 인체적용시험 자료가 있습니다. 세부 내용은 연구개발 페이지에서 확인할 수 있습니다.',href:'/technology',link:'연구개발 확인하기'},{q:'기업이 GMK® 원료를 공급받을 수 있나요?',a:'적용 목적, 제품 유형, 필요 규격과 수량을 확인한 후 원료 공급, 샘플 검토, 기술자료 제공과 공동개발 가능성을 협의할 수 있습니다.',href:'/business/ingredient',link:'원료 공급 알아보기'},{q:'기운찬의 소비자 제품은 어디에서 확인할 수 있나요?',a:'도두On 제품 페이지와 기운찬 공식 쇼핑몰에서 제품별 특징과 구매 정보를 확인할 수 있습니다.',href:'/brands/dodoon/products',link:'도두On 제품 확인하기'}]}/></div></section>
 <section className="section newsroom-home"><div className="shell"><SectionHeader eyebrow="LATEST NEWSROOM" title="기운찬의 새로운 소식" align="split"/><div className="news-editorial">{news.slice(0,3).map((item,i)=><article className={i===0?'is-feature':''} key={item.href}><span>{item.source} · {item.date}</span><h3>{item.title}</h3><p>{item.summary}</p><a href={item.href} target="_blank" rel="noreferrer">원문 보기 <ArrowRight size={16}/></a></article>)}</div><div className="section-link"><Button href="/newsroom/news">기운찬 뉴스 더 보기</Button></div></div></section>
 <InquiryCta/>
 </main></Layout>}
function CompanyLegacy(){return <>
 <section id="about" className="section"><div className="shell"><Title eyebrow="WHO WE ARE" title="기운찬은 어떤 회사인가" copy={companyDefinition}/><div className="article-detail wide-copy"><p>핵심 소재 GMK®를 중심으로 연구 근거를 축적하고, 기업의 원료 활용과 소비자 제품개발을 연결합니다. 자연의 가능성을 관찰하는 태도와 공개 가능한 근거를 바탕으로 책임 있게 소통합니다.</p><a className="text-link" href="/technology">특허·논문·인체적용시험 연구 근거 →</a></div></div></section>
 <section className="section warm"><div className="shell"><Title eyebrow="OUR BUSINESS" title="두 가지 방향, 하나의 연구 기반"/><div className="business-weighted"><article><small>B2B INGREDIENT</small><h3>B2B 원료사업</h3><p>복합버섯균사체 소재 GMK®를 기반으로 기업의 연구와 제품기획에 맞는 원료 협력을 추진합니다. 식품·음료 적용, 공동기획, 국내외 공급과 유통 가능성을 함께 검토합니다.</p><Button href="/business/ingredient">B2B 원료사업</Button></article><article><small>B2C DEVELOPMENT</small><h3>B2C 제품개발</h3><p>소재의 특성과 소비자 요구를 고려해 식품·음료·건강 관련 제품을 기획합니다. 자체 브랜드와 파트너사의 제품개발을 통해 연구를 일상으로 연결합니다.</p><Button href="/business/product-development">B2C 제품개발</Button></article></div></div></section>
 <section id="ceo" className="section"><div className="shell ceo-layout"><Photo src="/assets/ceo.webp" alt="주식회사 기운찬 박종례 대표" className="ceo-portrait"/><div><Title eyebrow="MESSAGE FROM CEO" title="버섯의 무한한 가능성을\n책임 있는 연구로 이어갑니다"/><p>처음 버섯균사체를 마주했을 때, 작은 생명체 안에 건강한 삶을 위한 가능성이 있다고 믿었습니다. 그 믿음으로 10년이 넘는 시간 동안 연구하고 실험하며 근거를 쌓아왔습니다.</p><p>기운찬은 속도보다 깊이를, 유행보다 근거를 중요하게 생각합니다. 연구의 원리를 살피고 확인된 정보의 범위 안에서 소통하겠습니다.</p><p>이제 연구·개발한 소재를 기업의 원료와 소비자의 제품으로 연결하고자 합니다. 더 많은 사람이 일상에서 자연의 가치를 경험할 수 있도록 노력하겠습니다.</p><p>연구 결과와 판매제품을 구분하고, 필요한 정보를 정확하게 전달하는 책임 있는 사업을 이어가겠습니다.</p><b>주식회사 기운찬 대표 박종례</b></div></div></section>
 <section id="information" className="section warm"><div className="shell"><Title eyebrow="COMPANY FACTS" title="회사 기본정보"/><Facts rows={[['회사명','주식회사 기운찬'],['영문명','Giunchan Co., Ltd.'],['대표자','박종례'],['설립연도','2015년 · 기존 회사 소개자료 기준'],['주요 분야','천연물 바이오소재 연구·개발 / B2B 원료사업 / B2C 제품개발'],['핵심 소재','GMK® 복합버섯균사체'],['소재지','충남 천안시 동남구 충절로 252, 2F']]}/></div></section>
 <section id="location" className="section"><div className="shell"><Title eyebrow="LOCATION" title="오시는 길" copy="충남 천안시 동남구 충절로 252, 2F"/><div className="location-grid"><iframe title="주식회사 기운찬 위치 지도" src={'https://maps.google.com/maps?q='+encodeURIComponent('충남 천안시 동남구 충절로 252')+'&output=embed'} loading="lazy" referrerPolicy="no-referrer-when-downgrade"/><div><h3>방문 안내</h3><p>길찾기에서 위 도로명 주소를 검색해 주세요. 방문 전 전화로 일정을 확인하시면 안내해 드립니다.</p><p>대표전화 <a href="tel:0415792203">041-579-2203</a><br/>팩스 041-585-2203<br/><a href="mailto:guc2203@guc.co.kr">guc2203@guc.co.kr</a></p><a className="text-link" href={'https://map.naver.com/p/search/'+encodeURIComponent('충남 천안시 동남구 충절로 252')} target="_blank" rel="noreferrer">네이버 지도에서 길찾기 ↗</a></div></div></div></section>
 <section id="contact" className="section sage"><div className="shell"><Title eyebrow="CONTACT GIUNCHAN" title="문의하기" copy="GMK® 원료, B2C 제품개발, 제품·유통, 국내외 사업 등 문의 목적을 선택해 주세요."/><p className="notice">현재 문의 폼은 작성 시연용이며 전송·저장되지 않습니다. 실제 상담은 <a href="mailto:guc2203@guc.co.kr">guc2203@guc.co.kr</a> 또는 <a href="tel:0415792203">041-579-2203</a>로 연락해 주세요.</p><ContactForm/></div></section>
 </>}
function Company(){
 void CompanyLegacy;
 const history:{year:string;title:string;items:string[]}[]=[
  {year:'2015',title:'설립과 연구의 시작',items:['2015년 10월 12일 주식회사 기운찬 법인 설립','충남테크노파크 입주']},
  {year:'2016',title:'연구조직과 제조기술 기반 구축',items:['버섯균사체 제조방법 관련 국내 특허 등록','기업부설연구소 설립']},
  {year:'2017',title:'생산 및 사업 기반 확대',items:['미국 FDA 공장 등록 및 관련 제품 안전성 테스트 통과','전국 농수산식품 창업 콘테스트 식품 부문 4위']},
  {year:'2019',title:'브랜드와 산업 인증',items:['농촌융복합산업 인증','브랜드K 선정','서울어워드 우수상품 선정']},
  {year:'2020—2023',title:'지식재산 확장',items:['국내 특허 5건 등록','미국 특허 1건 등록']},
  {year:'2021—2026',title:'학술 근거 축적',items:['GMK 관련 SCIE급 국제학술지 논문 4편 발표']},
  {year:'2024.12—2026.01',title:'인체적용시험',items:['고려대학교 구로병원·김천의료원','경도인지장애자 175명 대상 다기관 인체적용시험 완료']},
 ];
 return <>
 <section id="about" className="section company-overview"><div className="shell"><SectionHeader eyebrow="WHO WE ARE" title="연구에서 시작해 원료와 제품으로"/><div className="company-copy"><div><p>주식회사 기운찬은 2015년 충남 천안에서 설립된 천연물 바이오소재 전문기업입니다. 다양한 버섯과 버섯균사체를 연구하고, 곡물 배지에서 복합배양·발효하는 독자 기술을 기반으로 핵심 바이오소재 GMK®를 개발했습니다.</p><p>기운찬은 소재를 개발하는 데 그치지 않고 연구 근거 축적, 지식재산권 확보, 기업용 원료 공급과 소비자 제품개발까지 연결합니다. 연구결과와 판매제품을 명확히 구분하고 확인된 정보의 범위 안에서 책임 있게 소통하는 것을 원칙으로 합니다.</p></div><ul className="company-summary"><li>다양한 버섯과 버섯균사체 연구</li><li>복합배양·발효기술</li><li>바이오소재의 규격화와 사업화</li><li>B2B 원료와 B2C 제품개발</li></ul></div><Button href="/technology">연구성과 확인하기</Button></div></section>
 <section className="section company-research-spectrum"><div className="wide-shell"><SectionHeader eyebrow="RESEARCH SPECTRUM" title="다양한 버섯에서 가능성을 탐구합니다" copy="버섯은 종류에 따라 서로 다른 특성과 연구 가능성을 지니고 있습니다. 기운찬은 여러 종류의 버섯과 버섯균사체를 폭넓게 살펴보고, 소재로 활용할 수 있는 가능성을 연구해 왔습니다."/><p>개별 버섯의 알려진 특성을 단순히 나열하거나 혼합하는 데 머무르지 않고, 균사체의 생장과 배양 과정에서 나타나는 변화를 관찰하고 연구합니다.</p><figure className="company-spectrum"><Photo src="/assets/research-mushroom-spectrum.jpg" alt="연구실에서 관찰하는 다양한 버섯 표본과 연구 장비"/><figcaption>기운찬은 다양한 버섯과 버섯균사체의 소재 가능성을 폭넓게 연구합니다.</figcaption></figure></div></section>
 <section className="section company-origin"><div className="shell"><ImageTextSplit image="/assets/ceo-park-jongrye-lab-portrait.jpg" alt="기운찬 연구실에 있는 박종례 대표"><SectionHeader eyebrow="OUR BEGINNING" title="자연에서 발견한 가능성, 연구로 이어온 시간"/><p>기운찬은 자연이 가진 다양한 가능성을 보다 안정적이고 일관된 소재로 구현하는 방법을 고민해 왔습니다. 그 출발점에서 버섯의 자실체뿐 아니라 생장과 영양 흡수의 중심이 되는 균사체와 배양 과정에 주목했습니다.</p><p>다양한 버섯과 버섯균사체를 연구하고, 곡물 배지에서 함께 복합배양·발효하는 기술을 발전시키며 기운찬만의 연구 기반을 쌓았습니다. 이러한 연구는 GMK®라는 핵심 바이오소재와 기업용 원료사업, 소비자 제품개발로 이어지고 있습니다.</p></ImageTextSplit></div></section>
 <section className="section company-purpose"><div className="shell"><SectionHeader eyebrow="MISSION & VISION" title="자연의 가능성을 책임 있게 연결합니다"/><div className="purpose-grid"><article><small>MISSION</small><h3>연구의 가능성을 산업과 일상의 가치로</h3><p>자연 유래 소재의 가능성을 과학적 근거로 확인하고 기업의 원료와 소비자의 제품으로 연결합니다.</p></article><article><small>VISION</small><h3>복합버섯균사체 분야에서 신뢰받는 식품바이오 소재기업</h3><p>축적된 배양·발효기술과 책임 있는 연구를 바탕으로 국내외 기업과 연구기관이 신뢰할 수 있는 바이오소재 파트너로 성장합니다.</p></article></div><ol className="principle-list"><li><b>01</b><span><strong>연구의 깊이</strong>유행이나 과장보다 반복 가능한 연구와 축적된 근거를 중요하게 생각합니다.</span></li><li><b>02</b><span><strong>책임 있는 소통</strong>연구단계, 원료와 완제품을 구분하고 확인된 정보의 범위 안에서 소통합니다.</span></li><li><b>03</b><span><strong>산업과 일상의 연결</strong>연구한 소재가 기업의 제품개발과 소비자의 일상으로 이어질 수 있도록 사업화합니다.</span></li></ol></div></section>
 <section id="ceo" className="section company-ceo"><div className="shell"><ImageTextSplit image="/assets/ceo-park-jongrye-lab-material.jpg" alt="주식회사 기운찬 박종례 대표가 연구실에서 연구 소재를 들고 있는 모습" reverse><SectionHeader eyebrow="MESSAGE FROM CEO" title={'버섯의 가능성을\n책임 있는 연구로 이어갑니다'}/><p>처음 버섯균사체를 접했을 때, 이 작은 생명체 안에 건강한 삶을 위한 새로운 가능성이 있다고 생각했습니다. 그 가능성을 확인하기 위해 10년이 넘는 시간 동안 다양한 버섯을 살펴보고, 연구하고, 실험하며 근거를 쌓아왔습니다.</p><p>기운찬은 속도보다 깊이를, 유행보다 근거를 중요하게 생각합니다. 연구의 가능성과 한계를 함께 살피고 확인된 정보의 범위 안에서 책임 있게 소통하겠습니다.</p><p>앞으로도 연구·개발한 소재를 기업의 원료와 소비자의 제품으로 연결하며 자연의 가치가 건강한 일상에 닿을 수 있도록 노력하겠습니다.</p><p className="ceo-signature">주식회사 기운찬 대표 <strong>박종례</strong></p></ImageTextSplit></div></section>
 <section className="section company-history"><div className="shell"><SectionHeader eyebrow="HISTORY" title="연구로 쌓아온 기운찬의 시간"/><ol>{history.map(item=><li key={item.year}><time>{item.year}</time><div><h3>{item.title}</h3>{item.items.map(text=><p key={text}>{text}</p>)}</div></li>)}</ol><p className="history-note">FDA 공장 등록은 미국 식품의약국의 제품 승인 또는 기능성 인정을 의미하지 않습니다.</p><Button href="/technology">특허와 연구성과 자세히 보기</Button></div></section>
 <section className="section company-rnd"><div className="wide-shell"><SectionHeader eyebrow="GIUNCHAN R&D" title="연구가 기운찬의 시작이자 중심입니다" copy="기운찬은 제품 판매에서 출발한 회사가 아니라 다양한 버섯과 버섯균사체의 가능성을 연구하는 과정에서 시작한 식품바이오 기업입니다. 기업부설연구소를 중심으로 균사체 배양·발효, 소재 특성, 활용 가능성과 품질에 관한 연구를 축적해 왔습니다."/><p className="rnd-copy">연구결과를 특허와 학술자료로 남기고 대학·의료기관과의 협력을 통해 근거를 확장합니다. 이렇게 축적한 기술과 연구 경험은 GMK® 원료사업과 소비자 제품개발의 기반이 됩니다.</p><figure><Photo src="/assets/giunchan-rnd-team.jpg" alt="주식회사 기운찬 기업부설연구소 연구진"/><figcaption>다양한 버섯과 버섯균사체의 가능성을 연구하는 기운찬 기업부설연구소 연구진</figcaption></figure></div></section>
 <section className="section company-gallery"><div className="wide-shell"><SectionHeader eyebrow="INSIDE THE LAB" title="연구실에서 이어지는 관찰과 검토"/><div className="research-gallery"><figure className="is-feature"><Photo src="/assets/giunchan-research-sample-review.jpg" alt="기운찬 연구원이 플라스크 속 연구 시료를 확인하는 모습"/><figcaption>연구 시료의 상태를 관찰하고 기록하는 과정</figcaption></figure><figure><Photo src="/assets/giunchan-culture-research.jpg" alt="무균 작업 환경에서 배양 시료를 다루는 연구 장면"/><figcaption>배양 시료를 세심하게 관리하는 연구 과정</figcaption></figure><figure><Photo src="/assets/mushroom-mycelia-research.jpg" alt="버섯 표본과 균사체 배양 상태를 함께 관찰하는 연구 장면"/><figcaption>버섯과 균사체의 특성을 비교하고 관찰하는 연구</figcaption></figure></div></div></section>
 <section className="section company-capabilities"><div className="shell"><SectionHeader eyebrow="OUR CAPABILITIES" title="연구를 사업으로 연결하는 역량"/><ol>{[
  ['연구개발','다양한 버섯과 버섯균사체를 살펴보고 배양·발효를 기반으로 소재의 특성과 활용 가능성을 연구합니다.','/technology'],
  ['지식재산','GMK® 생산방법과 활용기술에 관한 국내 특허 9건과 미국 특허 1건을 확보했습니다.','/technology/patents'],
  ['학술 협력','대학 및 의료기관과 공동연구를 진행하고 연구결과를 국제학술지에 발표해 왔습니다.','/technology/publications'],
  ['원료 사업화','기업의 제품기획에 맞춰 원료 상담, 규격자료, 샘플 검토와 적용 가능성을 협의합니다.','/business/ingredient'],
  ['제품개발','연구한 소재와 식품개발 경험을 바탕으로 소비자가 일상에서 접할 수 있는 제품을 개발합니다.','/business/product-development']
 ].map(([title,copy,href],i)=><li key={title}><span>0{i+1}</span><div><h3>{title}</h3><p>{copy}</p><a href={href}>자세히 보기 →</a></div></li>)}</ol><a className="text-link capability-clinical" href="/technology/clinical-study">인체적용시험 확인하기 →</a></div></section>
 <section className="section company-business"><div className="shell"><SectionHeader eyebrow="OUR BUSINESS" title="연구에서 원료로, 원료에서 제품으로"/><div className="route-split"><a href="/business/ingredient"><small>B2B · INGREDIENT</small><h3>GMK® 원료사업</h3><p>GMK®를 기반으로 기업의 제품기획과 적용 목적에 맞는 원료 상담, 규격자료, 샘플 검토와 공동개발을 진행합니다.</p><span>GMK® 원료사업 알아보기 <ArrowRight/></span></a><a href="/business/product-development"><small>B2C · PRODUCT DEVELOPMENT</small><h3>소비자 제품개발</h3><p>연구한 소재와 식품개발 경험을 바탕으로 음료, 젤리, 농축액 등 소비자가 일상에서 접할 수 있는 제품을 개발합니다.</p><span>제품개발 알아보기 <ArrowRight/></span></a></div></div></section>
 <section id="information" className="section company-information"><div className="shell"><SectionHeader eyebrow="COMPANY FACTS" title="회사 기본정보"/><dl className="company-facts"><div><dt>회사명</dt><dd>주식회사 기운찬</dd></div><div><dt>영문명</dt><dd>Giunchan Co., Ltd.</dd></div><div><dt>대표자</dt><dd>박종례</dd></div><div><dt>설립일</dt><dd>2015년 10월 12일</dd></div><div><dt>소재지</dt><dd>충남 천안시 동남구 충절로 252, 2F</dd></div><div><dt>주요 사업</dt><dd>천연물 바이오소재 연구개발, B2B 원료사업, B2C 제품개발</dd></div><div><dt>핵심 소재</dt><dd>GMK® 복합버섯균사체</dd></div><div><dt>연구조직</dt><dd>기업부설연구소</dd></div><div><dt>사업자등록번호</dt><dd>289-81-00204</dd></div><div><dt>대표전화</dt><dd><a href="tel:+82415792203">041-579-2203</a></dd></div><div><dt>팩스</dt><dd>041-585-2203</dd></div><div><dt>이메일</dt><dd><a href="mailto:guc2203@guc.co.kr">guc2203@guc.co.kr</a></dd></div></dl></div></section>
 <section id="location" className="section company-location"><div className="shell"><SectionHeader eyebrow="LOCATION" title="기운찬으로 오시는 길" copy="충남 천안시 동남구 충절로 252, 2F"/><div className="location-grid"><iframe title="주식회사 기운찬 위치 지도" src={'https://maps.google.com/maps?q='+encodeURIComponent('충남 천안시 동남구 충절로 252')+'&output=embed'} loading="lazy" referrerPolicy="no-referrer-when-downgrade"/><div><h3>방문 안내</h3><p>방문 상담이 필요하신 경우 대표전화 또는 이메일로 일정을 먼저 확인해 주세요.</p><a href="tel:+82415792203">대표전화 041-579-2203</a><span>팩스 041-585-2203</span><a href="mailto:guc2203@guc.co.kr">guc2203@guc.co.kr</a><a href={'https://map.naver.com/p/search/'+encodeURIComponent('충남 천안시 동남구 충절로 252')} target="_blank" rel="noreferrer">네이버 지도에서 길찾기 ↗</a></div></div></div></section>
 <section id="contact" className="section company-contact"><div className="shell"><SectionHeader eyebrow="CONTACT GIUNCHAN" title="연구와 사업의 가능성을 이야기해 주세요" copy="GMK® 원료, 제품개발, 유통과 국내외 사업 협력에 관한 문의를 기다립니다."/><div className="inline-actions"><a className="button orange" href="mailto:guc2203@guc.co.kr">이메일 문의하기 <ArrowRight size={16}/></a><a className="button light" href="tel:+82415792203">전화 문의하기 <ArrowRight size={16}/></a><a className="text-link" href="/business/ingredient">GMK® 원료사업 문의 →</a></div></div></section>
 </>;
}
function Facts({rows}:{rows:string[][]}){return <div className="table-wrap"><table className="facts-table"><tbody>{rows.map(([key,value])=><tr key={key}><th scope="row">{key}</th><td>{value}</td></tr>)}</tbody></table></div>}
function TechnologyLegacy({path}:{path:string}) {
 if(path==='/technology/patents')return <><Title eyebrow="INTELLECTUAL PROPERTY" title="국내 9건 · 미국 1건" copy="회사 공개자료 기준 총 10건의 특허를 보유하고 있습니다."/><Facts rows={[['공개 확인 사항','GMK® 관련 원천기술의 미국 특허등록 결정 소식 · 2022년 8월'],['등록 국가','대한민국 / 미국'],['개별 특허명·등록번호·일자·상태','등록증과 원문 확인 후 공개할 항목입니다. 현재는 총 보유 건수와 공개된 보도 범위만 안내합니다.'],['공개 범위','버섯 종류, 균주, 배합, 배양조건, 상세 제조공정은 게시하지 않습니다.']]}/><p className="notice">특허는 기술 권리에 대한 정보이며 제품의 기능성 승인이나 효능 보증을 뜻하지 않습니다.</p><Button href={inquiryHref('GMK® 원료')}>특허 관련 공개자료 문의</Button></>;
 if(path==='/technology/publications')return <><Title eyebrow="PUBLICATIONS" title="SCIE급 국제학술지 논문 4편" copy="회사에서 공개한 연구성과를 연구 유형과 함께 소개합니다."/><Facts rows={[['2025년 · Cells','건양대학교 의과대학 연구팀과 신경세포 관련 공동연구 발표 · 세포 기반 전임상 연구'],['2023년 및 이전 연구','GMK® 관련 전임상 공동연구 소식이 공개돼 있습니다. 개별 논문 원문을 기준으로 확인해야 합니다.'],['논문명·DOI·기관·발표일','정확한 서지정보와 원문을 확인한 뒤 공개할 항목입니다. 확인되지 않은 DOI를 임의로 기재하지 않습니다.']]}/><p className="notice">{researchNotice}</p><a className="text-link" href="https://www.guc.co.kr/forum/view/355080" target="_blank" rel="noreferrer">2025년 공동연구 보도 출처 ↗</a></>;
 if(path==='/technology/clinical-study')return <><Title eyebrow="HUMAN STUDY" title="175명 대상 인체적용시험 완료" copy="회사 공개자료에서 확인되는 범위와 추가 확인이 필요한 항목을 구분합니다."/><Facts rows={[['연구 목적','GMK® 관련 인체적용 근거 확인 · 상세 평가 목적은 시험자료 확인 필요'],['대상자 수','175명 · 회사 공개자료 기준'],['진행 단계','시험 완료 · 회사 공개자료 기준'],['시험 설계·기관·기간','공개 가능한 시험보고서 확인 후 안내'],['확인 결과·안전성','결과 수치 및 안전성 평가는 현재 제공된 자료에서 확인되지 않아 기재하지 않습니다.']]}/><p className="notice">{researchNotice} 시험 완료 사실만으로 특정 효과나 안전성을 단정하지 않습니다.</p><Button href={inquiryHref('GMK® 원료')}>인체적용시험 공개자료 문의</Button></>;
 return <><Title eyebrow="RESEARCH MILESTONES" title="연구를 이어온 기록" copy="공개된 회사 자료와 주요 보도를 기준으로 정리했습니다."/><ol className="timeline">{[['10년 이상','버섯균사체 연구','기운찬은 장기간 버섯균사체의 소재 가능성을 연구해 왔습니다.'],['2021','원료 사업화 기반','GMK®의 대량 생산 관련 소식과 산학 공동연구 성과가 공개됐습니다.'],['2022','미국 특허등록 결정','GMK® 관련 원천기술의 미국 특허등록 결정 소식을 발표했습니다.'],['2023','산학 공동연구','건양대학교 의과대학 연구팀과 GMK® 전임상 연구 성과를 발표했습니다.'],['2024','인체적용시험 추진','GMK W20 인체적용시험 추진 소식이 보도됐습니다.'],['2025','국제학술지 연구 발표','Cells에 신경세포 관련 공동연구가 발표됐습니다.'],['현재 공개자료','175명 대상 시험 완료','국내외 특허 10건, SCIE급 논문 4편, 인체적용시험 완료를 안내하고 있습니다.']].map(([year,title,text])=><li key={year}><b>{year}</b><div><h3>{title}</h3><p>{text}</p></div></li>)}</ol><div className="inline-actions"><Button href="/technology/patents">특허</Button><Button href="/technology/publications">연구논문</Button><Button href="/technology/clinical-study">인체적용시험</Button></div><p className="notice">{researchNotice}</p></>;
}
const publications=[
 {year:'2021',title:'Water Extract of Mixed Mushroom Mycelia Grown on a Solid Barley Medium Is Protective against Experimental Focal Cerebral Ischemia',journal:'Current Issues in Molecular Biology · 43(1), 365–383',doi:'10.3390/cimb43010030',type:'세포 및 동물모델 전임상 연구',summary:'세포와 동물모델에서 연구시료와 신경세포 손상 관련 지표의 변화를 관찰한 연구입니다.'},
 {year:'2023',title:'Mixed Medicinal Mushroom Mycelia Attenuates Alzheimer’s Disease Pathologies In Vitro and In Vivo',journal:'Current Issues in Molecular Biology · 45, 6775–6789',doi:'10.3390/cimb45080428',type:'세포 및 동물모델 전임상 연구',summary:'세포와 동물모델에서 연구시료와 산화스트레스·신경염증 관련 지표를 관찰한 연구입니다.'},
 {year:'2025',title:'Neuroprotective Effect of Mixed Mushroom Mycelia Extract on Neurotoxicity and Neuroinflammation via Regulation of ROS-Induced Oxidative Stress in PC12 and BV2 Cells',journal:'Cells · 14(13), 977',doi:'10.3390/cells14130977',type:'세포 기반 전임상 연구',summary:'PC12 및 BV2 세포모델에서 연구시료와 산화스트레스·신경염증 관련 지표를 살펴본 연구입니다.'},
 {year:'2026',title:'A Water Extract of Mixed Mushroom Mycelia Mitigates Cognitive Deficit and Oxidative Stress After Global Cerebral Ischemia–Reperfusion Injury',journal:'Current Issues in Molecular Biology · 48(2), 151',doi:'10.3390/cimb48020151',type:'세포 및 동물모델 전임상 연구',summary:'허혈·재관류 동물모델에서 연구시료와 인지·산화스트레스 관련 지표를 관찰한 연구입니다.'},
];
const materialRows=[['GMK®','복합배양물을 건조한 기본 원료','분태·분말','차류 및 건식 제품 원료','기운찬의 기본 복합버섯균사체 소재'],['GMK 추출액','건조 GMK®를 열수 추출한 원료','갈색 액상','액상차·소스 등 습식 제품 원료','제품 적용을 위한 액상 형태'],['GMK 추출물','GMK 추출액을 농축·동결건조한 원료','분말','연구 및 분말형 원료 적용','인체적용시험에 사용된 원료']];
function ResearchNotice(){return <p className="research-disclaimer">연구성과는 각 연구에 사용된 시료와 연구조건에 관한 결과입니다. 개별 판매제품의 효능이나 질병의 진단·예방·치료를 의미하지 않습니다.</p>}
function Technology({path}:{path:string}) {
 void TechnologyLegacy;
 if(path==='/technology/patents')return <div className="technology-detail"><SectionHeader eyebrow="INTELLECTUAL PROPERTY" title="국내 9건·미국 1건, 총 10건" copy="기운찬은 정부 R&D 지원사업과 자체 연구, 산학협력을 통해 복합버섯균사체의 생산 및 활용기술을 연구하고 국내외 지식재산권을 축적해 왔습니다."/><div className="technology-stats"><div><strong>9</strong><span>국내 특허</span></div><div><strong>1</strong><span>미국 특허</span></div><div><strong>10</strong><span>총 등록 특허</span></div></div><section><h2>기술영역별 지식재산</h2><div className="ip-fields">{['복합버섯균사체 생산기술','배양·발효 관련 기술','소재 활용기술','식품 적용기술'].map(x=><span key={x}>{x}</span>)}</div><p>공식 특허정보는 각국 특허 데이터베이스에서 확인할 수 있습니다.</p><div className="external-links"><a href="https://www.kipris.or.kr/" target="_blank" rel="noreferrer">KIPRIS 특허정보검색 ↗</a><a href="https://patents.google.com/" target="_blank" rel="noreferrer">Google Patents 검색 ↗</a><a href="https://ppubs.uspto.gov/pubwebapp/" target="_blank" rel="noreferrer">USPTO Patent Public Search ↗</a></div></section><p className="notice">특허는 기술에 관한 권리정보이며 개별 제품의 기능성 승인이나 효능 보증을 의미하지 않습니다.</p><Button href={inquiryHref('기술자료')}>기술자료 문의</Button></div>;
 if(path==='/technology/publications')return <div className="technology-detail"><SectionHeader eyebrow="PUBLICATIONS" title="SCIE급 국제학술지 논문 4편" copy="기운찬은 대학 연구진과의 산학협력을 통해 GMK 및 GMK 추출물을 세포와 동물모델에서 연구하고 결과를 국제학술지에 발표해 왔습니다."/><div className="publication-list">{publications.map(p=><article key={p.doi}><time>{p.year}</time><div><span className="stage-badge">{p.type}</span><h2>{p.title}</h2><p><b>{p.journal}</b></p><p>{p.summary}</p><a href={'https://doi.org/'+p.doi} target="_blank" rel="noreferrer">DOI {p.doi} · 학술지 원문 ↗</a></div></article>)}</div><ResearchNotice/><p className="review-meta">자료 검토: 주식회사 기운찬 기업부설연구소 · 최종 수정일: 2026년 9월 5일</p><Button href={inquiryHref('연구자료')}>연구자료 문의</Button></div>;
 if(path==='/technology/clinical-study')return <div className="technology-detail clinical-page"><SectionHeader eyebrow="HUMAN STUDY" title="GMK 추출물 인체적용시험" copy="GMK 추출물을 사용해 경도인지장애자 175명을 대상으로 진행한 다기관·무작위배정·이중눈가림·위약대조 인체적용시험의 설계와 공개 가능한 결과를 안내합니다."/><section><h2>시험물질</h2><p>시험물질은 GMK® 복합배양물을 열수 추출한 뒤 농축·동결건조한 분말 형태의 GMK 추출물입니다.</p></section><div className="table-wrap"><table className="research-table"><caption>GMK 추출물 인체적용시험 설계</caption><tbody>{[['연구유형','다기관·무작위배정·이중눈가림·위약대조 인체적용시험'],['시험기관','고려대학교 구로병원·김천의료원'],['시험기간','2024년 12월~2026년 1월'],['대상','경도인지장애자'],['대상자 수','175명'],['섭취·관찰기간','16주'],['시험물질','GMK 추출물'],['1차 유효성 평가지표','K-MMSE'],['진행 상태','시험 완료']].map(([k,v])=><tr key={k}><th scope="row">{k}</th><td>{v}</td></tr>)}</tbody></table></div><section className="study-results"><h2>공개 결과</h2><p>16주간의 인체적용시험 결과, 1차 유효성 평가지표인 K-MMSE 점수가 시험군에서 유의하게 개선됐습니다(<i>p</i>&lt;0.05).</p><p>시험기간 중 중대한 이상반응은 보고되지 않았습니다.</p></section><section><h2>해석 범위</h2><p>본 결과는 GMK 추출물, 경도인지장애자, 16주 섭취와 해당 시험설계 및 평가지표에 따른 인체적용시험 결과입니다. 모든 GMK® 원료 또는 판매제품의 효능을 의미하지 않으며, 질병의 진단·예방·치료를 위한 정보가 아닙니다.</p><p className="notice">인체적용시험 완료는 건강기능식품 개별인정형 원료 등록 완료를 의미하지 않습니다.</p></section><p className="review-meta">자료 검토: 주식회사 기운찬 기업부설연구소 · 최종 수정일: 2026년 9월 5일</p><Button href={inquiryHref('인체적용시험 자료')}>연구자료 문의</Button></div>;
 const principles=['시료와 연구목적의 명확한 구분','연구단계에 맞는 결과 해석','산학협력을 통한 근거 축적','연구원료와 판매제품의 분리','확인된 범위 안에서의 책임 있는 소통'];
 const framework=[['연구 대상 탐색','다양한 버섯과 버섯균사체의 특성, 성장과 소재 가능성을 살펴봅니다.'],['배양·발효 연구','곡물 배지에서 다양한 버섯 균사체를 함께 배양하고 발효하는 기술을 연구합니다.'],['원료 형태 개발','연구와 적용 목적에 따라 건조 원료, 열수 추출액과 동결건조 추출물로 구분해 소재를 개발합니다.'],['특성 및 품질 확인','연구 목적에 맞는 시료를 설정하고 소재 특성, 지표성분과 품질의 일관성을 확인합니다.'],['전임상 연구','세포 및 동물모델을 활용해 연구시료의 작용 가능성, 안전성과 연구가설을 검토합니다.'],['인체적용 및 사업화','사람을 대상으로 특정 연구시료의 유효성과 안전성 관련 지표를 평가하고 원료 및 제품 적용 가능성을 검토합니다.']];
 const history=[['2015','초기 세포 기반 연구',['세포실험','초기 탐색연구'],'복합버섯균사체 연구시료를 활용한 세포 기반 연구로 소재 가능성 탐색을 시작했습니다.'],['2016~2017','대사 관련 전임상 연구',['세포실험','동물실험'],'세포 및 동물모델에서 복합버섯균사체 연구시료의 대사 관련 지표와 활용 가능성을 검토했습니다.'],['2018','간 관련 연구',['세포실험','동물실험','특허'],'세포 및 동물모델에서 간 관련 지표와 항산화 효소 발현 등 연구 가능성을 검토했습니다.'],['2019','안전성 연구',['안전성 평가'],'복귀돌연변이·소핵·염색체이상·단회 및 28일·90일 반복투여 독성시험을 수행했습니다.'],['2020~2025','인지기능 및 신경 관련 전임상 연구',['세포실험','동물실험','산학협력','논문'],'GMK 및 GMK 추출물을 활용해 신경세포 손상, 산화스트레스, 신경염증과 인지기능 관련 지표를 연구했습니다.'],['2021','폐 관련 전임상 연구',['세포실험','동물실험'],'복합버섯균사체 연구시료의 폐 관련 연구지표와 활용 가능성을 검토했습니다.'],['2024~2026','GMK 추출물 인체적용시험',['인체적용시험','시험 완료'],'고려대학교 구로병원과 김천의료원에서 경도인지장애자 175명을 대상으로 연구를 완료했습니다.']];
 return <div className="technology-hub"><SectionHeader eyebrow="RESEARCH PRINCIPLES" title="가능성을 주장하기 전에, 단계별로 확인합니다" copy="기운찬은 자연 유래 소재라는 이유만으로 가능성을 단정하지 않습니다. 연구 목적에 맞는 시료를 설정하고 세포실험, 동물실험과 인체적용시험을 통해 단계적으로 근거를 축적합니다."/><p>각 연구결과는 사용한 시료, 연구모델과 조건 안에서 해석합니다. 연구용 원료와 판매제품을 구분하고, 확인된 정보의 범위 안에서 책임 있게 소통합니다.</p><ol className="research-principles">{principles.map((x,i)=><li key={x}><span>0{i+1}</span>{x}</li>)}</ol>
 <section><SectionHeader eyebrow="RESEARCH FOCUS" title="다양한 버섯을 연구하고, 균사체의 가능성에 집중합니다"/><p>버섯은 종류에 따라 서로 다른 특성과 연구 가능성을 지니고 있습니다. 기운찬은 다양한 버섯과 버섯균사체를 폭넓게 살펴보고, 균사체의 생장과 배양 과정에서 나타나는 변화를 연구합니다.</p><p>이러한 연구를 바탕으로 다양한 버섯 균사체를 곡물 배지에서 함께 복합배양·발효하고, 이를 건조하거나 연구 목적에 맞게 추출해 소재의 활용 가능성을 확인합니다.</p><Button href="/insight/mycelia">버섯균사체 알아보기</Button></section>
 <section><SectionHeader eyebrow="MATERIAL CLASSIFICATION" title="연구와 적용 목적에 따라 구분되는 GMK 원료" copy="GMK®와 GMK 추출물은 동일한 형태의 원료가 아닙니다. 기본 건조 원료와 이를 열수 추출해 만든 액상·분말 원료를 구분해야 연구결과와 제품 적용 범위를 정확하게 이해할 수 있습니다."/><div className="table-wrap"><table className="research-table"><caption>GMK 원료 형태 비교</caption><thead><tr>{['구분','제조 개요','형태','주요 용도','연구관계'].map(x=><th key={x} scope="col">{x}</th>)}</tr></thead><tbody>{materialRows.map(row=><tr key={row[0]}>{row.map((x,i)=>i===0?<th scope="row" key={x}>{x}</th>:<td key={x}>{x}</td>)}</tr>)}</tbody></table></div><p>GMK 추출물은 GMK® 복합배양물을 건조한 뒤 열수 추출하고, 추출액을 농축·동결건조해 분말화한 원료입니다. 이번 인체적용시험에는 GMK 추출물을 사용했습니다.</p></section>
 <section><SectionHeader eyebrow="RESEARCH FRAMEWORK" title="소재 탐색부터 인체적용 연구까지"/><ol className="framework-list">{framework.map(([t,c],i)=><li key={t}><span>0{i+1}</span><div><h3>{t}</h3><p>{c}</p></div></li>)}</ol><p className="notice">연구 흐름은 과제 목적에 따라 달라질 수 있으며, 전임상 결과가 사람에서의 효능을 자동으로 입증하지 않습니다.</p></section>
 <section><SectionHeader eyebrow="R&D HISTORY" title="정부 R&D와 산학협력으로 축적한 연구" copy="기운찬은 정부 R&D 지원사업과 대학·연구기관과의 협력을 통해 다양한 버섯균사체 연구를 단계적으로 수행해 왔습니다."/><ol className="research-history">{history.map(([y,t,badges,c])=><li key={y as string}><time>{y}</time><div><div className="stage-badges">{(badges as string[]).map(b=><span key={b}>{b}</span>)}</div><h3>{t}</h3><p>{c}</p></div></li>)}</ol></section>
 <section><SectionHeader eyebrow="EVIDENCE LEVELS" title="연구결과는 연구단계에 따라 다르게 해석됩니다"/><div className="table-wrap"><table className="research-table"><caption>연구단계별 확인 내용과 해석 범위</caption><thead><tr><th>연구단계</th><th>확인하는 내용</th><th>해석 범위</th></tr></thead><tbody>{[['세포실험','특정 세포환경에서 나타나는 반응','사람에게 동일하게 적용된다고 단정할 수 없음'],['동물실험','생체 모델에서 나타나는 변화와 연구 가능성','인체 효능을 직접 의미하지 않음'],['안전성 평가','정해진 시험조건에서의 독성 관련 지표','모든 섭취조건에서의 절대적 안전을 의미하지 않음'],['인체적용시험','특정 대상자와 조건에서의 유효성·안전성 지표','시험물질·대상·기간·평가지표 범위에서 해석'],['제품 적용','식품 기준에 맞춘 원료 및 제품개발','연구결과와 판매제품의 표시·광고는 별도로 판단']].map(r=><tr key={r[0]}>{r.map((x,i)=>i===0?<th scope="row" key={x}>{x}</th>:<td key={x}>{x}</td>)}</tr>)}</tbody></table></div></section>
 <section><SectionHeader eyebrow="RESEARCH EVIDENCE" title="연구로 축적한 근거"/><div className="evidence-links"><a href="/technology/patents"><strong>10</strong><h3>국내외 특허</h3><p>국내 9건·미국 1건</p></a><a href="/technology/publications"><strong>4</strong><h3>SCIE급 논문</h3><p>논문과 DOI 원문</p></a><a href="/technology/clinical-study"><strong>175</strong><h3>인체적용시험</h3><p>시험설계와 공개 결과</p></a></div><ResearchNotice/></section><p className="review-meta">자료 검토: 주식회사 기운찬 기업부설연구소 · 최종 수정일: 2026년 9월 5일</p><Button href={inquiryHref('공동연구·기술자료')}>공동연구·기술자료 문의</Button></div>;
}
function Business({path}:{path:string}){
 const b2c=path==='/business/product-development';
 const b2b=<><Title eyebrow="B2B INGREDIENT BUSINESS" title="GMK®를 기반으로 기업의 가능성을 넓힙니다" copy="주식회사 기운찬은 복합버섯균사체 소재 GMK®를 기반으로 기업의 연구, 제품기획 및 사업 목적에 맞는 원료 협력을 추진합니다."/><ul className="service-list">{['GMK® 원료 공급','식품·음료 적용 검토','제품 공동기획 및 개발','국내외 공급·유통 협력','연구 및 사업자료 제공'].map(x=><li key={x}>{x}</li>)}</ul><p className="notice">홈페이지에는 원료의 성격과 협력 가능 분야만 공개합니다. 세부 제조공정, 배합·배양조건, 내부 품질규격, 원료 단가와 거래조건, 비공개 시험자료는 상담 후 필요한 범위에서 제공합니다.</p><Button href={inquiryHref('GMK® 원료')}>GMK® 원료사업 문의</Button></>;
 const consumer=<><Title eyebrow="B2C PRODUCT DEVELOPMENT" title="연구한 소재를 일상의 제품으로" copy="단순한 판매를 넘어 소재 특성과 소비자 요구를 고려한 식품·음료·건강 관련 제품을 기획하고 개발합니다."/><ul className="service-list">{['소비자 요구를 고려한 제품기획','원료 특성에 맞는 제형 검토','자체 브랜드 제품개발','파트너사와의 공동 제품개발'].map(x=><li key={x}>{x}</li>)}</ul><div className="inline-actions"><Button href={inquiryHref('B2C 제품개발')}>제품개발 문의</Button><a className="text-link" href="/brands/dodoon">도두On 브랜드 보기 →</a></div></>;
 return path==='/business'?<div className="business-overview"><div>{b2b}</div><aside><Title eyebrow="B2C DEVELOPMENT" title="소비자의 일상으로"/><p>연구한 소재를 식품·음료·건강 관련 제품으로 기획하고 개발합니다. 자체 브랜드와 파트너 협력을 통해 소비자와 만납니다.</p><Button href="/business/product-development">B2C 제품개발</Button></aside></div>:b2c?consumer:b2b;
}
function ProductList(){return <><div className="product-grid">{products.map(item=><ProductCard item={item} key={item.slug}/>)}</div><p className="notice">판매 여부·원재료·영양정보·섭취방법·주의사항은 공식 판매처와 제품 포장의 최신 정보를 확인해 주세요.</p><Button href={shop}>공식 쇼핑몰</Button></>}
function BrandStory(){return <><article className="dodoon-story" aria-labelledby="dodoon-title">
 <p className="dodoon-eyebrow">● BRAND STORY</p>
 <div className="dodoon-brand-heading"><div><div className="dodoon-wordmark" aria-label="도두On"><span>도</span><span>두</span><span>On</span></div><p className="dodoon-english">dodoon</p>
 <h2 id="dodoon-title">매일의 건강을 <span>돋우다.</span><br/>기운을 다시 세우는 하루.</h2>
 </div><Image className="dodoon-brand-logo" src="/assets/dodoon-official-logo.jpg" alt="도두On 브랜드 로고" width={900} height={1100} unoptimized/></div>
 <p className="dodoon-intro">가라앉은 기운을 다시 세우고, 흐릿해진 컨디션을 또렷하게 끌어올리는 일. <strong>도두On</strong>은 ‘돋우다’에서 시작된 이름입니다. ‘온’으로 읽는 <strong>‘On’</strong>에는 온(溫)의 따뜻함을 담아, 몰아치지 않고 매일 조금씩 더하는 건강을 지향합니다.</p>
 <ol className="dodoon-values">
  <li><span className="dodoon-number">01</span><div><h3>근거 있는 건강</h3><p>좋다고 알려진 것이 아니라, 왜 좋은지 설명할 수 있는 것만 담습니다.</p></div></li>
  <li><span className="dodoon-number">02</span><div><h3>매일 지킬 수 있는 건강</h3><p>부담 없이 반복할 수 있도록, 먹기 쉽고 챙기기 쉬운 형태를 고민합니다.</p></div></li>
  <li><span className="dodoon-number">03</span><div><h3>사람을 향한 건강</h3><p>성분 그 자체보다, 그것이 누군가의 하루를 어떻게 바꾸는지를 먼저 생각합니다.</p></div></li>
 </ol>
 <div className="dodoon-signoff"><p>매일, 건강을 <span>돋우다.</span></p><div>건강을 돋우는 종합 건강 브랜드<br/><strong>기운찬</strong> · 도두On</div></div>
 </article><div className="inline-actions"><Button href="/brands/dodoon/products">도두On 제품 보기</Button><a className="text-link" href={inquiryHref('제품·유통')}>제품·유통 문의 →</a></div></>}
const gmkFaq=[{q:'GMK®는 무엇인가요?',a:'기운찬이 연구·개발한 복합버섯균사체 바이오소재입니다. 연구와 원료사업의 핵심 소재를 가리키는 명칭입니다.'},{q:'GMK®와 GMK® 추출물은 같은 뜻인가요?',a:'GMK®는 소재의 명칭이며 추출물은 해당 소재에서 추출한 성분을 포함하는 연구·활용 대상을 말합니다. 연구를 읽을 때는 원료명과 시료 형태를 구분해야 합니다.'},{q:'연구 결과는 판매제품에도 그대로 적용되나요?',a:'그렇지 않습니다. 연구 시료, 사용량, 시험 대상과 판매제품의 원료 구성·섭취 조건은 다를 수 있습니다. 연구원료의 결과를 개별 완제품의 효능으로 연결하지 않습니다.'}];
function InsightContent({mycelia=false}:{mycelia?:boolean}){return mycelia?<article className="article-detail"><h2>균사체와 자실체는 무엇이 다른가요?</h2><p>균사체는 가느다란 균사가 모여 형성한 몸체입니다. 우리가 흔히 버섯이라고 부르는 눈에 보이는 부분은 포자를 만드는 자실체를 가리키는 경우가 많습니다. 두 용어는 같은 구조를 뜻하지 않습니다.</p><h2>생활사 속 균사체</h2><p>일반적으로 포자가 적합한 환경에서 발아하면 균사가 자라 균사체를 형성합니다. 균사체는 주변 환경에서 영양분을 이용하며 성장하고, 종과 환경에 따라 자실체를 형성할 수 있습니다.</p><h2>연구 소재로 이해하기</h2><p>균사체라는 명칭만으로 성분이나 기능이 모두 같다고 볼 수 없습니다. 원료와 연구 시료의 정의, 시험 방법을 구분해 살펴야 합니다.</p><FAQ items={[{q:'균사체는 버섯의 뿌리인가요?',a:'식물의 뿌리와는 다른 균류의 구조입니다. 이해를 돕는 비유로 쓰일 수 있지만 과학적으로 같은 기관은 아닙니다.'},{q:'모든 균사체가 동일한 특성을 가지나요?',a:'아닙니다. 종류와 성장환경에 따라 달라질 수 있으며 한 연구의 결과를 모든 균사체에 일반화하면 안 됩니다.'}]}/></article>:<article className="article-detail"><h2>GMK®의 공식 정의</h2><p>GMK®는 주식회사 기운찬이 연구·개발한 복합버섯균사체 바이오소재입니다. 연구·개발과 기업의 원료 활용을 연결하는 기운찬의 핵심 소재입니다.</p><h2>소재, 추출물, 완제품을 구분합니다</h2><p>연구자료를 읽을 때에는 GMK® 소재 자체인지, 추출물인지, 소비자에게 판매되는 완제품인지 먼저 확인해야 합니다. 각각의 정의와 사용 목적이 다르므로 같은 대상으로 간주하지 않습니다.</p><div id="faq"><FAQ items={gmkFaq}/></div><p className="notice">특허·논문·인체적용시험은 TECHNOLOGY에서 확인할 수 있습니다. 비공개 기술정보는 홈페이지에서 제공하지 않습니다.</p><Button href="/technology">공식 연구성과 보기</Button></article>}
function PageBody({path}:{path:string}){
 if(path.startsWith('/technology'))return <Technology path={path}/>;
 if(path.startsWith('/business'))return <Business path={path}/>;
 if(path==='/brands'||path==='/brands/dodoon')return <BrandStory/>;
 if(path==='/brands/dodoon/products')return <ProductList/>;
 const product=products.find(x=>path==='/brands/dodoon/products/'+x.slug);
 if(product)return <div className="product-detail"><Photo className="full-image" src={product.image} alt={product.name}/><div><Title eyebrow="PRODUCT INFORMATION" title={product.name} copy={product.summary}/><p>원재료, 영양정보, 섭취방법과 주의사항은 제품 포장 및 공식 판매처의 최신 표시사항을 확인해 주세요.</p><Button href={shop}>공식 쇼핑몰에서 확인</Button></div></div>;
 if(path==='/insight')return <InsightCards/>;
 if(path.startsWith('/insight/gmk'))return <InsightContent/>;
 if(path.startsWith('/insight/mycelia'))return <InsightContent mycelia/>;
 if(path==='/newsroom/issues')return <><Title eyebrow="INDUSTRY & RESEARCH" title="산업·연구 이슈" copy="버섯균사체·천연물 바이오소재 산업의 정책, 시장과 주요 연구 발표를 다룹니다."/><div className="notice"><h3>현재 공개된 산업·연구 이슈가 없습니다.</h3><p>출처가 확인된 내용을 ‘발표 내용 → 기운찬과의 관련성 → 해석 → 원문 출처’ 순서로 정리해 게시합니다.</p></div><Button href="/newsroom/news">기운찬 뉴스 보기</Button></>;
 if(path==='/newsroom'||path==='/newsroom/news')return <>{path==='/newsroom'&&<div className="inline-actions section-link"><a className="text-link" href="/newsroom/news">기운찬 뉴스</a><a className="text-link" href="/newsroom/issues">산업·연구 이슈</a></div>}<NewsList/></>;
 return null;
}
export function SitePage({path}:{path:string}){
 if(path==='/')return <Home/>;
 const product=products.find(x=>path==='/brands/dodoon/products/'+x.slug);
 const insight=insights.find(x=>x.href===path);
 const info=pages[path]||(product?{section:'BRANDS · PRODUCTS',title:product.name,lead:product.summary,image:product.image}:insight?{section:'INSIGHT · '+insight.category,title:insight.title,lead:insight.desc,image:insight.image}:null);
 if(!info){if(path==='/privacy'||path==='/terms')return <Layout><main className="section"><div className="shell"><Title eyebrow="INFORMATION" title="홈페이지 이용 및 개인정보 안내"/><p>현재 문의 폼은 시연용이며 작성 내용이 서버에 저장되거나 전송되지 않습니다. 실제 문의는 이메일 또는 전화로 연락해 주세요.</p><p>실제 온라인 접수 기능을 도입할 때 수집 항목·목적·보유기간·담당자 등 정식 처리방침을 별도로 안내합니다.</p><Button href={contactHref}>문의 안내</Button></div></main></Layout>;notFound();}
 const domain=path.split('/')[1]||'company';
 const routeClass=' route-'+path.slice(1).replaceAll('/','-');
 return <Layout><main className={'subpage page-'+domain+routeClass}><Hero {...info} path={path}/><nav className="breadcrumb shell" aria-label="현재 위치"><a href="/">HOME</a><span>/</span><span>{info.section}</span></nav>{path==='/company'?<Company/>:<section className="section subpage-content"><div className="shell"><PageBody path={path}/></div></section>}</main></Layout>
}

