export type ProductFact={slug:string;name:string;category:string;foodType:string;classification:'일반식품'|'건강기능식품';summary:string;amount:string;gmk:string;ingredientForm?:string;manufacturer?:string;seller?:string;method?:string;allergen?:string;storage?:string;image:string;verificationStatus:'confirmed';disclosureStatus:'public'};
export const productFacts:ProductFact[]=[
{slug:'premium-gift',name:'기운찬',category:'매일의 영양',foodType:'기타가공품',classification:'일반식품',summary:'1회분씩 간편하게 이용할 수 있는 분말 제품',amount:'120g (2g × 60포)',gmk:'GMK® 적용',ingredientForm:'GMK® 분말',manufacturer:'㈜오투바이오',seller:'㈜기운찬',method:'제품 포장의 최신 섭취 안내를 확인해 주세요.',allergen:'우유 함유',storage:'직사광선을 피하고 실온에 보관',image:'/assets/product-gift.webp',verificationStatus:'confirmed',disclosureStatus:'public'},
{slug:'immune-mk',name:'기운찬이뮨MK',category:'매일의 영양',foodType:'건강기능식품',classification:'건강기능식품',summary:'비타민과 미네랄을 캡슐 형태로 섭취하는 건강기능식품',amount:'48g (400mg × 120캡슐)',gmk:'GMK® 관련 원료 적용',manufacturer:'우리바이오㈜',seller:'㈜기운찬',method:'1일 2회, 1회 2캡슐을 충분한 물과 함께 섭취',allergen:'우유·돼지고기·쇠고기 함유',storage:'직사광선과 고온다습한 곳을 피해 보관',image:'/assets/product-gmk.webp',verificationStatus:'confirmed',disclosureStatus:'public'},
{slug:'mushroom-tea',name:'버섯마시면기운차 15포',category:'마시는 일상',foodType:'침출차',classification:'일반식품',summary:'티백으로 간편하게 우려 마시는 침출차',amount:'15g (1g × 15개)',gmk:'GMK® 적용',ingredientForm:'GMK® 기본 원료',manufacturer:'다원바이오',seller:'㈜기운찬',method:'티백 1개를 물에 충분히 우려 이용',allergen:'땅콩·대두·메밀 사용 제품과 같은 제조시설에서 제조',storage:'직사광선과 고온다습한 곳을 피해 보관',image:'/assets/product-mushroom-tea.jpg',verificationStatus:'confirmed',disclosureStatus:'public'},
{slug:'mushroom-tea-gift',name:'버섯마시면기운차 30포',category:'마시는 일상',foodType:'침출차',classification:'일반식품',summary:'30개의 티백을 병 포장으로 구성한 침출차',amount:'30g (1g × 30개)',gmk:'GMK® 적용',ingredientForm:'GMK® 기본 원료',manufacturer:'다원바이오',seller:'㈜기운찬',method:'티백 1개를 물에 충분히 우려 이용',allergen:'땅콩·대두·메밀 사용 제품과 같은 제조시설에서 제조',storage:'직사광선과 고온다습한 곳을 피해 보관',image:'/assets/product-mushroom-tea-gift.jpg',verificationStatus:'confirmed',disclosureStatus:'public'},
{slug:'giunchan-drink',name:'마시면기운차',category:'마시는 일상',foodType:'액상차',classification:'일반식품',summary:'병 포장으로 간편하게 이용하는 액상차',amount:'340mL',gmk:'GMK® 관련 원료 적용',manufacturer:'(재)제주테크노파크 용암해수센터',seller:'㈜기운찬',method:'개봉 후 바로 음용',allergen:'공용 제조시설 알레르기 주의사항은 제품 포장 확인',storage:'직사광선을 피해 실온 보관하고 개봉 후 바로 섭취',image:'/assets/product-liquid.webp',verificationStatus:'confirmed',disclosureStatus:'public'},
{slug:'mushroom-spoon',name:'버섯한스푼 3종',category:'매일의 식탁',foodType:'기타가공품',classification:'일반식품',summary:'밥과 요리에 더해 사용하는 세 가지 분말 제품',amount:'각 50g',gmk:'제품별 표시사항 확인',manufacturer:'㈜기운찬',seller:'㈜기운찬',method:'제품별 포장의 사용 안내를 확인해 주세요.',allergen:'제품별 포장의 최신 알레르기 정보를 확인해 주세요.',storage:'직사광선과 고온다습한 곳을 피해 밀봉 보관',image:'/assets/product-mushroom-spoon.jpg',verificationStatus:'confirmed',disclosureStatus:'public'},
{slug:'smart-jelly',name:'똑똑젤리',category:'매일의 식탁',foodType:'기타가공품',classification:'일반식품',summary:'샤인머스캣 맛을 스틱으로 간편하게 즐기는 젤리',amount:'200g (20g × 10포)',gmk:'제품 표시사항 확인',method:'제품 포장의 최신 섭취 안내를 확인해 주세요.',allergen:'제품 포장의 최신 알레르기 정보를 확인해 주세요.',storage:'직사광선을 피해 실온 보관',image:'/assets/product-grape.webp',verificationStatus:'confirmed',disclosureStatus:'public'},
{slug:'giuncha-extract',name:'기운차 진액',category:'마시는 일상',foodType:'액상차',classification:'일반식품',summary:'취향에 맞게 이용할 수 있는 병 포장 진액 제품',amount:'500mL',gmk:'제품 표시사항 확인',method:'제품 포장의 최신 섭취 안내를 확인해 주세요.',allergen:'제품 포장의 최신 알레르기 정보를 확인해 주세요.',storage:'개봉 후 냉장 보관',image:'/assets/product-giuncha-extract.png',verificationStatus:'confirmed',disclosureStatus:'public'}];
export const publicProductFacts=productFacts.filter(item=>item.verificationStatus==='confirmed'&&item.disclosureStatus==='public');
