const make=(items:string[][])=>items.map(([label,href])=>({label,href}));
export const nav=[
 {label:'HOME',href:'/',children:[]},
 {label:'COMPANY',href:'/company',children:make([['회사소개','/company'],['대표 인사말','/company/ceo'],['기업철학','/company/philosophy'],['연혁·인증','/company/history'],['ESG 경영','/company/esg']])},
 {label:'TECHNOLOGY',href:'/technology',children:make([['기술 종합','/technology'],['GMK® 소개','/technology/gmk'],['기술 경쟁력','/technology/competitiveness'],['R&D','/technology/research'],['논문·특허','/technology/publications'],['인체적용시험','/technology/clinical-study'],['기술 FAQ','/technology/faq']])},
 {label:'BUSINESS',href:'/business',children:make([['B2B 사업 종합','/business'],['GMK® 원료소재','/business/ingredient'],['적용 분야','/business/applications'],['제품 공동개발','/business/co-development'],['품질관리','/business/quality'],['국내외 공급·수출','/business/global']])},
 {label:'BRANDS',href:'/brands',children:make([['브랜드 종합','/brands'],['도두On','/brands/dodoon'],['제품 목록','/brands/dodoon/products']])},
 {label:'INSIGHT',href:'/insight',children:make([['콘텐츠 허브','/insight'],['GMK® Inside','/insight/gmk'],['Mycelia Science','/insight/mycelia'],['Research Note','/insight/research'],['Business & ESG','/insight/business-esg'],['Giunchan Story','/insight/story']])},
 {label:'NEWSROOM',href:'/newsroom',children:make([['뉴스룸','/newsroom'],['보도자료','/newsroom/press'],['언론보도','/newsroom/media'],['기업소식','/newsroom/news'],['공지사항','/newsroom/notice']])},
 {label:'CONTACT',href:'/contact',children:make([['유형별 문의','/contact'],['오시는 길','/contact/location']])},
];
export const stats=[['9','국내특허'],['1','미국특허'],['4','SCIE급 논문'],['175','인체적용시험 대상자']];
export const products=[{slug:'grape-jelly',name:'도두On 제품 01',image:'/assets/product-grape.webp'},{slug:'gmk',name:'도두On 제품 02',image:'/assets/product-gmk.webp'},{slug:'liquid',name:'도두On 제품 03',image:'/assets/product-liquid.webp'},{slug:'gift',name:'도두On 제품 04',image:'/assets/product-gift.webp'}];
export const insights=[{category:'GMK® Inside',title:'GMK®는 무엇인가요?',desc:'복합버섯균사체 GMK®의 공식 정의와 연구 범위를 소개합니다.',image:'/assets/gmk-landscape-dark.webp',href:'/insight/gmk/what-is-gmk'},{category:'Mycelia Science',title:'버섯과 균사체는 어떻게 다를까요?',desc:'균사체의 개념을 기초 과학의 언어로 이해합니다.',image:'/assets/tree-mycelia.webp',href:'/insight/mycelia/mushroom-and-mycelia'},{category:'Research Note',title:'인체적용시험을 읽는 방법',desc:'연구 결과를 해석할 때 확인해야 할 기본 요소를 살펴봅니다.',image:'/assets/research-dish.webp',href:'/insight/research/reading-clinical-study'}];
export type PageInfo={section:string;title:string;lead:string;image:string};
const p=(section:string,title:string,lead:string,image:string):PageInfo=>({section,title,lead,image});
export const pages:Record<string,PageInfo>={
 '/company':p('COMPANY','자연의 가능성을\n사람의 삶으로 이어갑니다','기술과 사람을 연결하는 천연물 바이오소재 전문기업','/assets/lab-leaf.webp'),'/company/ceo':p('COMPANY','오래 바라본 자연의 가치를\n정직한 연구로 증명하겠습니다','주식회사 기운찬 대표 인사말','/assets/ceo.webp'),'/company/philosophy':p('COMPANY','자연을 존중하고\n과학에 책임을 더합니다','기운찬이 소재를 연구하고 사업을 이어가는 원칙','/assets/esg-sprout.webp'),'/company/history':p('COMPANY','한 걸음씩 쌓아온\n기운찬의 연구 여정','2015년 설립부터 이어진 기업의 기록','/assets/forest-mycelia.webp'),'/company/esg':p('COMPANY · ESG','더 나은 소재를 만드는 일은\n더 나은 내일을 생각하는 일입니다','환경·사람·책임을 고려하는 지속가능한 경영 방향','/assets/esg-sprout.webp'),
 '/technology':p('TECHNOLOGY','오래 바라보고,\n깊이 연구합니다','자연에서 발견한 가능성을 과학적으로 확인하고 사람의 삶에 이로운 바이오소재로 발전시킵니다.','/assets/field-research.webp'),'/technology/gmk':p('TECHNOLOGY','GMK®\n복합버섯균사체','기운찬의 복합배양·발효기술로 연구·개발한 핵심 바이오소재','/assets/gmk-landscape-dark.webp'),'/technology/competitiveness':p('TECHNOLOGY','연구에서 소재까지\n이어지는 기술 경쟁력','공개 가능한 범위에서 확인하는 기운찬의 기술 기반','/assets/biotech-graphic.webp'),'/technology/research':p('TECHNOLOGY','가능성을 확인하는\n지속적인 R&D','기초 연구에서 인체적용시험까지 이어지는 연구 체계','/assets/researcher-microscope.webp'),'/technology/publications':p('TECHNOLOGY','논문과 특허로\n축적한 연구의 기록','확인된 연구성과를 투명하게 안내합니다.','/assets/microscope.webp'),'/technology/clinical-study':p('TECHNOLOGY','사람을 향한 연구의\n근거를 확인합니다','경도인지장애자 175명 대상 인체적용시험 완료','/assets/quality-lab.webp'),'/technology/faq':p('TECHNOLOGY','GMK® 기술에 대해\n자주 묻는 질문','연구원료와 판매제품을 구분해 정확히 안내합니다.','/assets/culture-white.webp'),
 '/business':p('BUSINESS','연구된 소재를,\n함께 성장하는 사업으로','GMK® 원료소재를 중심으로 연결되는 소재·개발·공급의 가치사슬','/assets/ingredient-plates.webp'),'/business/ingredient':p('BUSINESS','GMK® 원료소재','기업의 제품 기획과 연구 목적에 맞춘 B2B 소재 협력','/assets/ingredient-forest.webp'),'/business/applications':p('BUSINESS','다양한 가능성을 여는\n적용 분야','확인된 범위 안에서 소재 적용 가능성을 함께 검토합니다.','/assets/applications.webp'),'/business/co-development':p('BUSINESS','아이디어를 제품으로\n함께 발전시킵니다','기획부터 소재 검토까지 이어지는 공동개발 협력','/assets/capsule-mushroom.webp'),'/business/quality':p('BUSINESS','신뢰를 만드는\n품질관리 원칙','정확한 정보와 책임 있는 관리 체계를 지향합니다.','/assets/quality-lab.webp'),'/business/global':p('BUSINESS','국내외 공급과\n사업 협력','원료 공급·수출 협력 가능성을 문의해 주세요.','/assets/lab-extract.webp'),
 '/brands':p('BRANDS','기운찬의 연구를\n생활 가까이','소비자 제품을 운영하는 B2C 브랜드 도두On','/assets/product-grape.webp'),'/brands/dodoon':p('BRANDS · 도두On','건강을 돋우다,\n기운을 돋우다','도두On은 주식회사 기운찬이 개발한 소비자 제품을 운영하는 B2C 제품 브랜드입니다.','/assets/product-premium.webp'),'/brands/dodoon/products':p('BRANDS · 도두On','도두On 제품','제품별 확인된 정보와 공식 구매 안내를 제공합니다.','/assets/product-pouches.webp'),
 '/insight':p('INSIGHT','자연의 깊은 지혜를,\n오늘의 과학으로','버섯균사체와 천연물 소재에 관한 연구와 정보를 기운찬의 시선으로 쉽고 정확하게 전합니다.','/assets/tree-mycelia.webp'),'/insight/gmk':p('INSIGHT · GMK® INSIDE','GMK®를 정확하게\n이해하는 출발점','정의, 연구원료와 제품의 차이, 자주 묻는 질문','/assets/gmk-landscape-dark.webp'),'/insight/mycelia':p('INSIGHT · MYCELIA SCIENCE','균사체의 세계를\n쉽고 깊게','버섯과 균사체에 관한 기초 과학','/assets/culture-white.webp'),'/insight/research':p('INSIGHT · RESEARCH NOTE','연구 결과를\n제대로 읽는 방법','논문과 인체적용시험의 의미를 차분히 해설합니다.','/assets/research-dish.webp'),'/insight/business-esg':p('INSIGHT · BUSINESS & ESG','소재 산업과\n책임 있는 성장','원료소재 산업, 공동개발, 품질관리와 ESG','/assets/esg-sprout.webp'),'/insight/story':p('INSIGHT · GIUNCHAN STORY','기운찬의 사람과\n연구 현장 이야기','창업, 기업문화, 브랜드를 기록합니다.','/assets/field-research.webp'),
 '/newsroom':p('NEWSROOM','기운찬의 오늘과\n새로운 소식을 전합니다','보도자료·언론보도·기업소식·공지사항','/assets/lab-extract.webp'),'/newsroom/press':p('NEWSROOM · PRESS RELEASE','보도자료','주식회사 기운찬이 공식 발표한 자료입니다.','/assets/lab-extract.webp'),'/newsroom/media':p('NEWSROOM · MEDIA','언론보도','외부 언론에 소개된 기운찬 관련 보도입니다.','/assets/microscope.webp'),'/newsroom/news':p('NEWSROOM · NEWS','기업소식','연구와 조직의 새로운 소식을 전합니다.','/assets/field-research.webp'),'/newsroom/notice':p('NEWSROOM · NOTICE','공지사항','이용에 필요한 안내를 확인하세요.','/assets/forest-mycelia.webp'),'/contact':p('CONTACT','기운찬과 함께할 가능성을\n이야기해 주세요','목적에 맞는 문의를 선택하면 담당 분야별 상담을 준비합니다.','/assets/quality-lab.webp'),'/contact/location':p('CONTACT','오시는 길','주식회사 기운찬은 충남 천안에 있습니다.','/assets/esg-sprout.webp')};

