export type ContentType='insight'|'newsroom';
export type SourceLink={label:string;url:string};
export type VerificationStatus='confirmed'|'needsVerification';
export type DisclosureStatus='public'|'limited'|'embargoed'|'confidential'|'internalOnly';
export type ContentEntry={title:string;originalTitle:string;slug:string;contentType:ContentType;category:string;summary:string;publishedAt:string;updatedAt:string;author:string;reviewer:string;thumbnail:string;thumbnailAlt:string;tags:string[];relatedEntities:string[];sourceLinks:SourceLink[];featured:boolean;draft:boolean;verificationStatus:VerificationStatus;disclosureStatus:DisclosureStatus;readingTime:number;answer:string;sections:{title:string;body:string}[];terms?:{term:string;definition:string}[];legacyPostId?:string;legacyUrl?:string;publisher?:string;reporter?:string;researchStage?:string;relatedMaterial?:string;relatedOrganizations?:string[];originalArticleUrl?:string;pastStatus?:string;currentStatus?:string;disclaimer?:string;migrationStatus?:string};
const author='주식회사 기운찬',reviewer='주식회사 기운찬 기업부설연구소';
const insight=(x:Partial<ContentEntry>&Pick<ContentEntry,'title'|'slug'|'category'|'summary'|'answer'|'sections'>):ContentEntry=>({originalTitle:x.title,contentType:'insight',publishedAt:'2026-09-05',updatedAt:'2026-09-06',author,reviewer,thumbnail:'/assets/research-dish.webp',thumbnailAlt:'기운찬 연구소의 배양 연구 이미지',tags:[],relatedEntities:['GMK®'],sourceLinks:[],featured:false,draft:false,verificationStatus:'confirmed',disclosureStatus:'public',readingTime:4,...x});
export const insightEntries:ContentEntry[]=[
 insight({title:'GMK®는 무엇인가요?',slug:'what-is-gmk',category:'GMK® 이해',summary:'기운찬의 B2B 원료 브랜드 GMK®와 소비자 완제품의 차이를 설명합니다.',answer:'GMK®는 주식회사 기운찬의 독자적인 복합배양 기술로 생산하는 복합버섯균사체 원료입니다. 소비자에게 직접 판매되는 완제품명과는 구분됩니다.',thumbnail:'/assets/culture-brown.webp',featured:true,tags:['GMK','원료 브랜드'],sections:[{title:'한 문장 정의',body:'GMK®는 주식회사 기운찬의 독자적인 복합배양 기술로 생산하는 복합버섯균사체 원료입니다. 기운찬은 GMK®의 생산기술과 활용 가능성에 관한 연구를 지속하고 있습니다.'},{title:'원료와 제품의 차이',body:'GMK®는 연구와 제품개발에 활용되는 원료이고, 도두On은 기운찬의 소비자 제품 브랜드입니다. 연구 시료와 판매제품도 같은 대상으로 해석하지 않습니다.'},{title:'공개 범위',body:'한 연구의 결과가 GMK®를 사용한 모든 완제품에 그대로 적용되는 것은 아닙니다. 구체적인 원료 조성, 배양조건과 상세 제조공정은 공개하지 않습니다.'}],terms:[{term:'GMK®',definition:'기운찬의 독자적인 복합배양 기술로 생산하는 복합버섯균사체 원료'},{term:'도두On',definition:'기운찬의 소비자 제품 브랜드'}]}),
 insight({title:'GMK®, GMK® 추출액, GMK® 추출물은 어떻게 다른가요?',slug:'gmk-material-forms',category:'원료 이야기',summary:'기본 원료, 액상 파생 원료, 분말 파생 원료를 제조 형태에 따라 구분합니다.',answer:'GMK®는 배양물을 건조한 기본 원료이며, GMK® 추출액은 이를 열수 추출한 액상 형태, GMK® 추출물은 추출액을 농축하고 동결건조한 분말 형태입니다.',thumbnail:'/assets/lab-extract.webp',featured:true,tags:['GMK','추출액','추출물'],sections:[{title:'핵심 차이',body:'세 이름은 같은 완제품을 뜻하지 않습니다. 원료가 어떤 공정을 거쳐 어떤 형태가 되었는지를 구분하는 명칭입니다.'},{title:'제품에서 확인하는 법',body:'제품명만으로 원료 형태를 추정하지 말고 포장지의 원재료명과 제품 설명을 확인해야 합니다.'},{title:'연구를 읽을 때',body:'논문이나 시험에서 사용한 시료가 기본 원료인지 추출액인지 추출물인지 먼저 확인해야 결과의 적용 범위를 올바르게 이해할 수 있습니다.'}]}),
 insight({title:'버섯과 균사체는 어떻게 다른가요?',slug:'mushroom-and-mycelia',category:'버섯과 균사체',summary:'눈에 보이는 자실체와 가느다란 균사가 모인 균사체의 역할을 구분합니다.',answer:'우리가 흔히 버섯이라고 부르는 부분은 포자를 만드는 자실체이고, 균사체는 가느다란 균사가 모여 형성한 균류의 몸체입니다.',thumbnail:'/assets/tree-mycelia.webp',featured:true,tags:['버섯','균사체','자실체'],sections:[{title:'생활사 속 역할',body:'포자가 적합한 환경에서 발아하면 균사가 자라고 균사체를 형성합니다. 종과 환경에 따라 균사체에서 자실체가 만들어질 수 있습니다.'},{title:'연구 소재로서의 균사체',body:'균사체는 배양 조건과 원료에 따라 특성이 달라질 수 있어 연구 시료의 정의와 시험방법을 함께 살펴야 합니다.'},{title:'오해하기 쉬운 점',body:'균사체를 식물의 뿌리와 같다고 설명하는 것은 이해를 돕는 비유일 뿐, 과학적으로 같은 기관은 아닙니다.'}]}),
 insight({title:'복합배양과 단순 혼합은 어떻게 다른가요?',slug:'co-culture-vs-mixing',category:'연구 쉽게 읽기',summary:'함께 배양하는 과정과 완성된 원료를 나중에 섞는 과정의 차이를 설명합니다.',answer:'복합배양은 둘 이상의 균사체가 같은 배지에서 함께 성장하는 과정이고, 단순 혼합은 각각 만든 원료를 배양 후에 섞는 방식입니다.',thumbnail:'/assets/ingredient-plates.webp',tags:['복합배양','혼합','배양'],sections:[{title:'과정의 차이',body:'복합배양에서는 성장 과정의 환경을 함께 관리합니다. 단순 혼합은 개별 생산된 원료를 정해진 목적에 맞춰 혼합합니다.'},{title:'왜 구분해야 하나요?',body:'제조 접근이 다르므로 시험 결과와 품질자료를 해석할 때 어떤 방식으로 만든 시료인지 확인해야 합니다.'},{title:'공개 범위',body:'기운찬은 복합배양 연구 방향을 공개하지만 구체적인 균주, 배합비, 배양조건과 상세 공정은 공개하지 않습니다.'}]}),
 insight({title:'배지는 버섯균사체 배양에서 어떤 역할을 하나요?',slug:'grain-medium-role',category:'버섯과 균사체',summary:'균사체가 자라는 환경이자 영양원인 배지의 기본 역할을 살펴봅니다.',answer:'배지는 버섯균사체가 성장할 수 있도록 영양과 물리적 환경을 제공하는 배양 기반입니다.',thumbnail:'/assets/gmk-landscape-light.webp',tags:['배지','배양'],sections:[{title:'배지의 역할',body:'배지는 균사체가 이용할 수 있는 영양분과 성장 공간을 제공합니다. 종류와 처리방법에 따라 배양 특성이 달라질 수 있습니다.'},{title:'연구에서 확인할 점',body:'같은 균류라도 배지와 배양 조건이 다르면 결과가 달라질 수 있으므로 연구방법을 함께 확인해야 합니다.'},{title:'공개 범위',body:'기운찬은 버섯균사체 배양 기술을 연구합니다. 원료 조성, 배합비, 균주와 상세 제조조건은 기술보호를 위해 공개하지 않습니다.'}]}),
 insight({title:'세포실험·동물실험·인체적용시험은 어떻게 다른가요?',slug:'research-stage-guide',category:'연구 쉽게 읽기',summary:'시험 대상과 해석 범위가 다른 연구단계를 한눈에 구분합니다.',answer:'세포실험은 세포 수준, 동물실험은 동물모델, 인체적용시험은 사람을 대상으로 합니다. 앞 단계의 결과를 사람의 효과로 곧바로 확대할 수 없습니다.',thumbnail:'/assets/researcher-microscope.webp',tags:['세포연구','동물연구','인체적용시험'],sections:[{title:'세포연구',body:'통제된 환경에서 세포 반응과 가능한 작용 경로를 살펴보는 초기 연구입니다.'},{title:'동물연구',body:'생체 수준에서 반응을 탐색하지만 동물모델의 결과가 사람에게 동일하게 나타난다고 단정할 수 없습니다.'},{title:'인체적용시험',body:'사람을 대상으로 식품 또는 원료의 적용 가능성을 정해진 설계로 평가합니다. 의약품 임상시험과 구분해 표현해야 합니다.'}]}),
 insight({title:'특허를 받았다는 것은 효능을 인정받았다는 뜻인가요?',slug:'patent-and-efficacy',category:'연구 쉽게 읽기',summary:'기술적 권리인 특허와 식품의 기능성 인정이 서로 다른 제도임을 설명합니다.',answer:'아닙니다. 특허는 발명의 신규성과 기술적 권리범위를 다루며, 특정 식품의 효능이나 정부의 기능성 인정을 의미하지 않습니다.',thumbnail:'/assets/heroes/patents-desktop.jpg',tags:['특허','기능성'],sections:[{title:'특허가 다루는 것',body:'특허는 발명에 대한 권리 확보 제도입니다. 등록번호, 국가, 권리상태와 청구범위를 확인해야 합니다.'},{title:'기능성 인정과의 차이',body:'식품의 기능성 표시는 별도의 법적 기준과 심사 절차를 따릅니다. 특허등록만으로 제품의 기능성을 표현할 수 없습니다.'},{title:'확인 방법',body:'기운찬의 특허 현황은 Technology 특허 페이지에서 공식 명칭과 등록정보를 확인할 수 있습니다.'}]}),
 insight({title:'연구논문 결과를 완제품 효능으로 볼 수 있나요?',slug:'paper-vs-product',category:'연구 쉽게 읽기',summary:'연구 시료와 판매제품의 동일성을 확인해야 하는 이유를 설명합니다.',answer:'일반적으로 그렇지 않습니다. 논문에서 사용한 시료, 용량, 연구모델과 판매제품의 구성·섭취조건이 다를 수 있기 때문입니다.',thumbnail:'/assets/heroes/papers-desktop.jpg',tags:['논문','완제품','연구 시료'],sections:[{title:'먼저 확인할 정보',body:'논문명, 연구단계, 사용 시료, 시험방법과 결과 범위를 확인해야 합니다.'},{title:'완제품과의 관계',body:'완제품에 같은 계열 원료가 사용돼도 논문의 결과가 그 제품의 효능을 직접 입증하는 것은 아닙니다.'},{title:'안전한 해석',body:'논문은 해당 조건에서 얻은 연구결과로 읽고, 제품 정보는 실제 포장과 공식 표시사항을 기준으로 확인합니다.'}]}),
 insight({title:'일반식품과 건강기능식품은 어떻게 다른가요?',slug:'food-vs-health-functional-food',category:'식품과 제품',summary:'일반식품과 건강기능식품의 표시·관리 체계 차이를 소비자 관점에서 설명합니다.',answer:'일반식품과 건강기능식품은 적용되는 기준과 표시 방법이 다릅니다. 제품 포장의 식품유형과 건강기능식품 표시를 확인하는 것이 가장 정확합니다.',thumbnail:'/assets/product-pouches.webp',tags:['일반식품','건강기능식품','표시사항'],sections:[{title:'제품 유형 확인',body:'제품 전면의 인상이나 원료명만으로 구분하지 말고 포장에 표시된 식품유형과 인증 표시를 확인해야 합니다.'},{title:'표현의 차이',body:'건강기능식품은 인정된 기능성 원료와 기준에 따라 표시할 수 있습니다. 일반식품에 같은 표현을 적용할 수 없습니다.'},{title:'구매 전 확인',body:'원재료, 내용량, 섭취 또는 이용방법과 주의사항은 실제 제품 포장의 최신 표시를 우선합니다.'}]}),
 insight({title:'제품에 사용된 GMK® 원료 형태는 어떻게 확인하나요?',slug:'check-gmk-form-in-product',category:'식품과 제품',summary:'원재료명과 공식 제품정보를 통해 적용된 원료 형태를 확인하는 방법을 안내합니다.',answer:'제품 포장의 원재료명과 기운찬 공식 제품정보에서 GMK®, GMK® 추출액, GMK® 추출물 중 어떤 형태가 사용됐는지 확인하세요.',thumbnail:'/assets/product-mushroom-spoon.jpg',tags:['제품 표시','GMK','원재료명'],sections:[{title:'포장에서 찾을 곳',body:'원재료명, 식품유형, 내용량과 주의사항이 표시된 정보면을 확인합니다.'},{title:'이름으로 추정하지 않기',body:'제품명이 비슷해도 적용된 원료 형태가 다를 수 있습니다. 마케팅 문구보다 법정 표시사항을 우선합니다.'},{title:'문의가 필요한 경우',body:'포장 정보가 불분명하거나 기업용 원료자료가 필요한 경우 기운찬 문의 채널을 이용할 수 있습니다.'}]})
];
const preclinical='해당 연구는 세포 또는 동물모델을 이용한 전임상 연구로, 사람의 질병 예방·치료 효과나 판매제품의 효능을 의미하지 않습니다.';
const news=(x:Partial<ContentEntry>&Pick<ContentEntry,'title'|'originalTitle'|'slug'|'category'|'publishedAt'|'legacyPostId'|'publisher'|'answer'|'pastStatus'|'currentStatus'>):ContentEntry=>({contentType:'newsroom' as const,updatedAt:'2026-09-06',author,reviewer,thumbnail:'/assets/giunchan-rnd-team.jpg',thumbnailAlt:'주식회사 기운찬 기업부설연구소 연구진',tags:[],relatedEntities:['주식회사 기운찬'],sourceLinks:[],featured:false,draft:false,verificationStatus:'confirmed',disclosureStatus:'public',readingTime:3,legacyUrl:`https://www.guc.co.kr/forum/view/${x.legacyPostId}`,relatedOrganizations:[],migrationStatus:'핵심 콘텐츠 이전 완료',...x,originalArticleUrl:x.originalArticleUrl||x.sourceLinks?.[0]?.url||`https://www.guc.co.kr/forum/view/${x.legacyPostId}`,summary:x.summary||x.answer,sections:[{title:'당시 발표 내용',body:x.pastStatus||''},{title:'현재 상태',body:x.currentStatus||''},{title:'기운찬과의 관련성',body:'기운찬의 연구·사업·사회공헌 활동을 기록한 기존 언론보도를 현재 공개 기준에 맞춰 요약했습니다.'},{title:'해석 시 주의사항',body:x.disclaimer||'원 보도의 표현과 현재 홈페이지의 공식 설명은 구분됩니다. 제품 정보는 최신 표시사항을 확인해 주세요.'}]});
export const newsroomEntries:ContentEntry[]=[
 news({legacyPostId:'gmk-human-study-complete-2026',originalTitle:'기운찬, GMK® 추출물 인체적용시험 완료',title:'기운찬, GMK® 추출물 인체적용시험 완료 및 인정 절차 진행',slug:'gmk-human-study-complete-2026',category:'연구성과',publishedAt:'2026-09-06',publisher:'주식회사 기운찬',researchStage:'인체적용시험 완료·인정 절차 진행 중',relatedMaterial:'GMK® 추출물',relatedOrganizations:['고려대학교 구로병원','김천의료원'],answer:'기운찬은 GMK® 추출물 인체적용시험을 완료했으며, 2026년 8월 보도된 결과를 바탕으로 식품의약품안전처 개별인정형 원료 인정 절차를 진행하고 있습니다.',pastStatus:'만 55세 이상 주관적 인지저하를 호소하는 성인을 대상으로 16주간 무작위배정·이중눈가림·위약대조 방식의 인체적용시험을 수행했습니다. 2026년 8월 언론보도에 따르면 K-MMSE 총점에서 두 군 사이에 통계적으로 유의한 차이가 나타났고(p<0.05), 시험 기간 중 중대한 이상반응은 보고되지 않았습니다.',currentStatus:'현재 식품의약품안전처에 건강기능식품 개별인정형 원료 인정을 신청해 심사 절차를 진행하고 있습니다. 아직 기능성 인정이 완료된 상태는 아니며, 해당 연구결과가 개별 판매제품의 효능을 의미하지는 않습니다.',disclaimer:'인체적용시험은 의약품 임상시험과 구분됩니다. 공개된 연구결과는 해당 연구시료와 조건의 범위에서 해석해야 하며 개별 판매제품의 효능을 의미하지 않습니다.',featured:true,thumbnail:'/assets/heroes/clinical-study-24-desktop.jpg',sourceLinks:[{label:'중앙일보 · 2026.08.26',url:'https://www.joongang.co.kr/article/25456430'},{label:'뉴스파고 · 2026.08.27',url:'https://www.newspago.com/newnews/print.php?uid=121969'}]}),
 news({legacyPostId:'355080',originalTitle:'[한국경제]건양대·기운찬, 복합 버섯 균사체로 치매 예방 가능성 제시',title:'건양대학교·기운찬, GMK® 추출물 관련 세포연구 발표',slug:'gmk-cell-study-2025',category:'연구성과',publishedAt:'2025-06-30',publisher:'한국경제',reporter:'임호범',researchStage:'세포연구',relatedMaterial:'GMK® 추출물',relatedOrganizations:['건양대학교 의과대학'],answer:'2025년 6월 30일 한국경제는 기운찬과 건양대학교 연구팀의 GMK® 추출물 관련 세포연구가 Cells에 게재됐다고 보도했습니다. 현재 이 결과는 세포 수준의 전임상 연구 범위로 해석합니다.',pastStatus:'산화 스트레스와 염증 관련 세포모델에서 GMK® 추출물을 살펴본 연구가 국제학술지 Cells에 발표됐다는 내용입니다.',currentStatus:'논문은 2025년 발표된 세포연구 기록으로 관리되며, 연구논문 상세정보는 Technology에서 확인할 수 있습니다.',disclaimer:preclinical,featured:true,thumbnail:'/assets/researcher-microscope.webp',sourceLinks:[{label:'한국경제 원문',url:'https://www.hankyung.com/article/202506308890h'},{label:'논문 DOI',url:'https://doi.org/10.3390/cells14130977'}]}),
 news({legacyPostId:'355078',originalTitle:'[굿모닝충청]㈜기운찬, 인지기능 개선 물질 GMK 인체적용시험 눈앞에',title:'기운찬, GMK® 추출물 인체적용시험 추진',slug:'gmk-human-application-plan',category:'연구성과',publishedAt:'2024-08-06',publisher:'굿모닝충청',reporter:'노준희',researchStage:'인체적용시험 완료·인정 절차 진행 중',relatedMaterial:'GMK® 추출물',answer:'2024년 8월 6일 보도는 GMK® 추출물 인체적용시험 추진 계획을 다뤘습니다. 이후 시험은 완료됐으며, 현재 식품의약품안전처 개별인정형 원료 인정 절차가 진행 중입니다.',pastStatus:'당시 보도는 GMK® 추출물 인체적용시험의 추진 계획을 다룬 기록입니다.',currentStatus:'인체적용시험은 완료됐고 식품의약품안전처 개별인정형 원료 인정 절차가 진행 중입니다. 기능성 인정이 완료된 상태는 아닙니다.',disclaimer:'인체적용시험은 의약품 임상시험과 구분됩니다. 시험의 세부 설계와 결과는 공개 승인 범위 밖이므로 이 페이지에서 제공하지 않습니다.',featured:true,thumbnail:'/assets/heroes/clinical-study-24-desktop.jpg',sourceLinks:[{label:'굿모닝충청 원문',url:'https://www.goodmorningcc.com/news/articleView.html?idxno=402317'}]}),
 news({legacyPostId:'355077',originalTitle:'[아시아투데이]기운찬, 세계 최초 ‘버섯균사체’ 알츠하이머성 치매 개선 입증',title:'기운찬·건양대학교 연구팀, 복합버섯균사체 관련 전임상 연구 발표',slug:'gmk-preclinical-neuro-study',category:'연구성과',publishedAt:'2023-09-19',publisher:'아시아투데이',reporter:'배승빈',researchStage:'세포·동물 전임상 연구',relatedMaterial:'GMK® 추출물',relatedOrganizations:['건양대학교 의과대학'],answer:'2023년 9월 19일 아시아투데이는 기운찬과 건양대학교 의과대학 연구팀의 세포·동물 전임상 연구 발표를 보도했습니다. 현재 이 결과는 사람이나 판매제품의 효과가 아닌 전임상 연구 범위로 설명합니다.',pastStatus:'세포와 동물모델을 이용해 GMK® 추출물의 신경 관련 반응을 관찰한 공동연구가 발표됐습니다.',currentStatus:'2023년 논문 발표 이후 관련 인체적용시험이 별도로 진행됐습니다. 두 연구단계의 결과는 구분해 해석합니다.',disclaimer:preclinical,thumbnail:'/assets/mushroom-study.webp',sourceLinks:[{label:'아시아투데이 원문',url:'https://www.asiatoday.co.kr/kn/view.php?key=20230919010011255'},{label:'논문 DOI',url:'https://doi.org/10.3390/cimb45080428'}]}),
 news({legacyPostId:'355076',originalTitle:"[충남일보] 기운찬, 천안시장애인체육회에 건강식품 지원 '눈길'",title:'기운찬, 천안시장애인체육회 선수단 제품 후원',slug:'cheonan-disabled-sports-support',category:'사회공헌',publishedAt:'2022-09-22',publisher:'충남일보',reporter:'선희홍',answer:'2022년 9월 22일 기운찬은 충청남도 장애인체육대회에 출전한 천안시장애인체육회 선수단에 제품을 후원했습니다.',pastStatus:'제28회 충청남도 장애인체육대회 출전 선수단을 위해 아연·비타민D 플러스 제품을 전달했습니다.',currentStatus:'당시 전달 활동을 기록한 사회공헌 아카이브입니다. 후원제품과 선수의 경기력 또는 건강 변화는 연결해 설명하지 않습니다.',thumbnail:'/assets/giunchan-rnd-team.jpg',sourceLinks:[{label:'충남일보 원문',url:'https://www.chungnamilbo.co.kr/news/articleView.html?idxno=680342'}]}),
 news({legacyPostId:'355071',originalTitle:'[충남일보]기운찬-건양대학교 유영춘 교수팀, GMK-Immune 경구투여... 급성폐렴 억제효과',title:'기운찬·건양대학교 연구팀, 복합버섯균사체 면역조절 관련 동물연구 수행',slug:'gmk-immune-animal-study',category:'연구성과',publishedAt:'2022-01-28',publisher:'충남일보',reporter:'선희홍',researchStage:'동물연구',relatedMaterial:'복합버섯균사체 연구시료',relatedOrganizations:['건양대학교 의과대학'],answer:'2022년 1월 28일 충남일보는 기운찬과 건양대학교 연구팀이 동물모델에서 복합버섯균사체 연구시료의 면역조절 관련 반응을 살펴본 연구를 보도했습니다.',pastStatus:'LPS 유도 동물모델에서 염증 관련 지표를 관찰한 연구가 발표됐습니다.',currentStatus:'동물연구 단계의 과거 기록입니다. 사람이나 판매제품의 효과로 확대하지 않습니다.',disclaimer:preclinical,thumbnail:'/assets/bio-cell.webp',sourceLinks:[{label:'충남일보 원문',url:'https://www.chungnamilbo.co.kr/news/articleView.html?idxno=645338'}]}),
 news({legacyPostId:'355069',originalTitle:"[메디컬투데이]기운찬, 천연 바이오 신물질 'GMK' 제조법 美 특허등록 결정",title:'기운찬, GMK® 복합배양 기술 관련 미국 특허 확보',slug:'gmk-us-patent',category:'특허·인증',publishedAt:'2022-08-18',publisher:'메디컬투데이',reporter:'남연희',researchStage:'특허등록',relatedMaterial:'GMK®',answer:'2022년 8월 18일 메디컬투데이는 GMK® 복합배양 기술과 관련한 미국 특허등록 결정을 보도했습니다. 특허는 기술적 권리 확보를 뜻하며 제품의 기능성 승인을 의미하지 않습니다.',pastStatus:'미국 특허청의 관련 특허등록 결정과 해외 사업 기반 확보 계획이 발표됐습니다.',currentStatus:'관련 미국 특허는 기운찬의 지식재산권 현황에 포함돼 관리되고 있습니다. 정확한 등록정보는 Technology 특허 페이지를 확인해 주세요.',disclaimer:'특허등록은 기술적 권리의 확보를 의미하며 제품의 기능성 승인이나 효능 보증을 의미하지 않습니다.',featured:true,thumbnail:'/assets/heroes/patents-desktop.jpg',sourceLinks:[{label:'메디컬투데이 원문',url:'https://mdtoday.co.kr/news/view/1065582404405227'}]}),
 news({legacyPostId:'355067',originalTitle:'[시사뉴스24]㈜기운찬, 면역항암제 후보 물질 ‘GMK’ B16-BL6에 뛰어난 효과 검증',title:'기운찬, 복합버섯균사체의 암 관련 세포·동물연구 결과 발표',slug:'gmk-oncology-preclinical-study',category:'연구성과',publishedAt:'2021-09-27',publisher:'시사뉴스24',reporter:'엄병길',researchStage:'세포·동물 전임상 연구',relatedMaterial:'복합버섯균사체 연구시료',relatedOrganizations:['건양대학교 의과대학'],answer:'2021년 9월 27일 시사뉴스24는 기운찬과 건양대학교 연구팀의 암 관련 세포·동물 전임상 연구 결과를 보도했습니다.',pastStatus:'세포와 동물모델을 이용해 연구시료의 면역 관련 반응을 살펴본 결과가 발표됐습니다.',currentStatus:'전임상 연구 단계의 기록이며 판매제품이나 사람의 효과를 의미하지 않습니다.',disclaimer:preclinical,thumbnail:'/assets/bio-cell.webp',sourceLinks:[{label:'시사뉴스24 원문',url:'http://www.sisanews24.co.kr/6618'}]}),
 news({legacyPostId:'355066',originalTitle:"[충남일보]기운찬, 복합 배양 바이오 신소재'GMK' 대량 생산 ‘초읽기’",title:'기운찬, GMK® 생산과 원료 사업화 기반 확대',slug:'gmk-production-scale-up',category:'사업·협력',publishedAt:'2021-07-15',publisher:'충남일보',reporter:'선희홍',relatedMaterial:'GMK®',answer:'2021년 7월 15일 충남일보는 기운찬이 GMK® 생산기반을 확대하고 원료 사업화를 추진한다고 보도했습니다.',pastStatus:'배양 생산 기반을 확충하고 원료 공급과 수출을 준비하던 시점의 사업 발표입니다.',currentStatus:'기운찬은 현재 GMK®, GMK® 추출액과 GMK® 추출물을 기업용 원료로 공급·협력하고 있습니다. 비공개 제조조건은 공개하지 않습니다.',thumbnail:'/assets/gmk-landscape-dark.webp',sourceLinks:[{label:'충남일보 원문',url:'https://www.chungnamilbo.co.kr/news/articleView.html?idxno=613264'}]}),
 news({legacyPostId:'355065',originalTitle:'[에이블뉴스]㈜기운찬, 장애인국가대표 건강기능식품 후원',title:'기운찬, 장애인국가대표 선수단 제품 후원',slug:'national-disabled-team-support',category:'사회공헌',publishedAt:'2021-03-09',publisher:'에이블뉴스',reporter:'백민',answer:'2021년 3월 9일 기운찬은 대한장애인체육회를 통해 장애인국가대표 선수단에 아연·비타민D 제품을 후원했습니다.',pastStatus:'대한장애인체육회 관계자와 기운찬 임직원이 참석한 전달식에서 제품을 전달했습니다.',currentStatus:'당시 후원 사실을 기록한 사회공헌 아카이브입니다. 제품 후원과 경기력 또는 회복 효과를 연결하지 않습니다.',thumbnail:'/assets/giunchan-rnd-team.jpg',sourceLinks:[{label:'에이블뉴스 원문',url:'https://www.ablenews.co.kr/news/articleView.html?idxno=92645'}]}),
 news({legacyPostId:'355062',originalTitle:'[금강일보] 기운찬 박종례 대표, 충남장애인부모회에 제품 기부',title:'기운찬, 충남장애인부모회 천안지회에 제품 기부',slug:'disabled-parents-association-donation',category:'사회공헌',publishedAt:'2020-07-16',publisher:'금강일보',reporter:'김인수',answer:'2020년 7월 16일 금강일보는 기운찬이 충남장애인부모회 천안지회에 식품을 기부했다고 보도했습니다.',pastStatus:'사랑의열매를 통해 기운찬 우리밥상 제품을 전달한 활동입니다.',currentStatus:'당시 제품 기부를 기록한 사회공헌 아카이브입니다. 제품 섭취에 따른 건강효과를 주장하지 않습니다.',thumbnail:'/assets/product-pouches.webp',sourceLinks:[{label:'금강일보 원문',url:'https://www.ggilbo.com/news/articleView.html?idxno=783687'}]}),
 news({legacyPostId:'355061',originalTitle:'[매일경제][톡톡 이상품] 기운찬 / 항당뇨 특화제품 `기운찬`',title:'매일경제, 기운찬 초기 분말제품과 사업화 과정 소개',slug:'giunchan-powder-product-archive',category:'제품·브랜드',publishedAt:'2020-04-07',publisher:'매일경제',answer:'2020년 4월 7일 매일경제는 기운찬의 초기 분말제품과 복합버섯균사체 사업화 과정을 소개했습니다. 과거 기사에 포함된 질병 관련 표현은 현재 제품 설명에 사용하지 않습니다.',pastStatus:'초기 제품의 개발 배경과 판매 계획이 소개됐습니다.',currentStatus:'해당 제품 계보는 현재 브랜드 페이지의 기운찬 本 소개에서 확인할 수 있습니다. 제품은 일반식품으로 최신 표시사항을 기준으로 안내합니다.',thumbnail:'/assets/product-gift.webp',sourceLinks:[{label:'매일경제 원문',url:'https://www.mk.co.kr/news/special-edition/view/2020/04/359976/'}]}),
 news({legacyPostId:'355060',originalTitle:'[중부매일](주)기운찬, 천안시에 면역력 강화에 필요한 물품 기탁',title:'기운찬, 천안시에 아연·비타민D 제품 기탁',slug:'cheonan-city-product-donation',category:'사회공헌',publishedAt:'2020-03-05',publisher:'중부매일',reporter:'송문용',answer:'2020년 3월 5일 중부매일은 기운찬이 천안시에 아연·비타민D 제품을 기탁했다고 보도했습니다.',pastStatus:'2020년 3월 천안시청을 방문해 지역사회를 위한 제품을 전달했습니다.',currentStatus:'당시 기탁 사실을 기록한 사회공헌 아카이브입니다. 특정 감염병의 예방과 제품을 연결하지 않습니다.',thumbnail:'/assets/giunchan-rnd-team.jpg',sourceLinks:[{label:'중부매일 원문',url:'http://www.jbnews.com/news/articleView.html?idxno=1281360'}]}),
 news({legacyPostId:'355059',originalTitle:"[충청신문]'코로나19’ 등 학생면역력 우리가 책임진다",title:'충청신문, 기운찬 학교급식용 제품 소개',slug:'school-meal-product-archive',category:'제품·브랜드',publishedAt:'2020-02-24',publisher:'충청신문',reporter:'장선화',answer:'2020년 2월 24일 충청신문은 충남 지역 학교급식에 공급되던 기운찬의 곡물 분말제품을 소개했습니다.',pastStatus:'친환경학교급식 지역우수가공품과 당시 제품 적용 사례가 소개됐습니다.',currentStatus:'과거 제품과 학교급식 사업의 기록입니다. 특정 감염병 예방이나 학생의 건강효과를 보장하는 표현은 현재 공식 설명에 사용하지 않습니다.',thumbnail:'/assets/product-mushroom-spoon.jpg',sourceLinks:[{label:'충청신문 원문',url:'http://www.dailycc.net/news/articlePrint.html?idxno=581082'}]}),
 news({legacyPostId:'355058',originalTitle:'[중부매일]박종례 천안 기운찬대표, 제27회 충남 농어촌발전상 수상',title:'박종례 기운찬 대표, 제27회 충남 농어촌발전상 수상',slug:'chungnam-rural-development-award',category:'기업소식',publishedAt:'2019-12-11',publisher:'중부매일',reporter:'송문용',answer:'2019년 12월 11일 박종례 기운찬 대표가 충남 농어촌발전상 농촌융복합 분야에서 수상했습니다.',pastStatus:'충청남도가 주관한 제27회 농어촌발전상에서 농촌융복합 분야 수상자로 선정됐습니다.',currentStatus:'회사의 연구개발과 농촌융복합 사업 이력에 포함되는 기업 기록입니다.',thumbnail:'/assets/ceo-park-jongrye-lab-portrait.jpg',sourceLinks:[{label:'중부매일 원문',url:'http://www.jbnews.com/news/articleView.html?idxno=1271252'}]}),
 news({legacyPostId:'355057',originalTitle:"[뉴시스]기운찬 '꿈꾸는 버섯' 복합균사체 건강식품 호응",title:'기운찬, 2016 농수산식품 창업콘테스트 본선 진출',slug:'food-startup-contest-2016',category:'기업소식',publishedAt:'2016-09-19',publisher:'뉴시스',reporter:'이종익',answer:'2016년 뉴시스는 기운찬이 ‘꿈꾸는 버섯’ 팀으로 농수산식품 창업콘테스트 본선에 진출했다고 보도했습니다.',pastStatus:'전국의 식품 창업 아이디어 가운데 본선 진출 기업으로 선정된 초기 창업 기록입니다.',currentStatus:'2015년 설립 이후 연구소와 원료·제품 사업으로 확장해 온 회사 연혁의 한 장면입니다.',thumbnail:'/assets/field-research.webp',sourceLinks:[{label:'뉴시스 원문',url:'https://newsis.com/common/?id=NISX20161018_0014457977&method=print&type=article'}]})
];
const isPubliclyPublishable=(x:ContentEntry)=>!x.draft&&x.verificationStatus==='confirmed'&&(x.disclosureStatus==='public'||x.disclosureStatus==='limited');
export const publishedInsights=insightEntries.filter(isPubliclyPublishable);
export const publishedNews=newsroomEntries.filter(isPubliclyPublishable).sort((a,b)=>b.publishedAt.localeCompare(a.publishedAt));
export const allPublished=[...publishedInsights,...publishedNews];
export const findContent=(path:string)=>allPublished.find(x=>`/${x.contentType}/${x.slug}`===path);
