import {icon} from './visuals.mjs';
const image=(name,alt,hero=false)=>`<img src="/assets/${name}.webp" alt="${alt}" ${hero?'fetchpriority="high"':'loading="lazy"'} width="1200" height="800">`;
const label=t=>`<span class="story-label">${t}</span>`;
export function brandStory(products,comparison){return `<div class="dodoon-story">
<section id="BB01" class="story-hero">${image('forest','숲속 나무와 흰 균사를 표현한 이미지',true)}<div class="container">${label('BRAND STORY')}<h1>보이지 않는 곳에서 시작되는 생명력, 도두On</h1><p>숲속의 죽은 나무와 축축하게 쌓인 낙엽 사이.<br>버섯의 삶은 눈에 잘 보이지 않는 아주 가느다란 실에서 시작됩니다.</p></div></section>
<section id="BB02" class="story-section"><div class="container story-split"><figure>${image('petri','가느다란 흰 균사의 연결을 표현한 배양 이미지')}<figcaption>FUNGAL HYPHAE · 균사</figcaption></figure><div>${label('01 · THE BEGINNING')}<h2>아주 작은 균사에서 시작됩니다</h2><p>이 작은 실을 ‘균사’라고 합니다. 균사는 죽은 나무와 낙엽의 유기물을 분해해 영양분을 얻으며 자랍니다.</p><p>수많은 균사가 서로 이어지고 단단하게 엮이면서 더 크고 강한 생명체인 ‘균사체’로 확장됩니다.</p></div></div></section>
<section id="BB03" class="story-forest">${image('mycelium','나무 위로 연결된 균사와 밖으로 돋아난 버섯을 표현한 이미지')}<div class="container story-forest-layout"><div>${label('02 · CONNECTION & GROWTH')}<h2>연결되고, 확장되고,<br>마침내 모습을 드러내다</h2><p>균사체가 충분히 성장하고 온도와 습도 등 알맞은 환경을 만나면, 비로소 땅과 나무 밖으로 모습을 드러냅니다.</p><p>우리가 흔히 버섯이라고 부르는 ‘자실체’가 만들어지는 순간입니다.</p></div><ol class="story-growth"><li>균사의 연결</li><li>균사체로 확장</li><li>자실체의 탄생</li></ol></div></section>
<section id="story-value" class="story-section"><div class="container story-split story-reverse"><figure>${image('company-nature','나무에 자란 차가버섯과 균사를 표현한 이미지')}</figure><div>${label('03 · NATURE INTO RESEARCH')}<h2>기운찬이 발견한<br>보이지 않는 가치</h2><p>단단한 돌덩이처럼 보이는 차가버섯을 비롯해 영지버섯과 상황버섯은 오랜 시간 식품과 천연물 연구의 소재로 주목받아 왔습니다.</p><p>그러나 기운찬이 바라본 것은 겉으로 드러난 버섯만이 아니었습니다.</p><p>보이지 않는 곳에서 주변의 유기물을 분해하고, 생명력을 축적하며, 새로운 생명으로 확장되는 ‘버섯균사체의 삶’에 주목했습니다.</p></div></div></section>
<section id="BB04" class="story-section story-white"><div class="container">${label('RESEARCH')}<h2>복합버섯균사체 소재 GMK®</h2><h3 class="story-subtitle">차가·영지·상황버섯균사체 복합배양</h3><p class="story-intro">기운찬은 차가·영지·상황버섯의 균사체를 함께 복합배양하여 독자적인 버섯균사체 소재 ‘GMK®’를 개발했습니다.</p><div class="story-materials">${['차가버섯 균사체','영지버섯 균사체','상황버섯 균사체'].map(t=>`<figure><div class="story-placeholder" role="img" aria-label="${t} 사진 준비 중">${icon('culture')}<span>균사체 이미지 교체 예정</span><small>권장 1200 × 900px · 4:3</small></div><figcaption><h3>${t}</h3></figcaption></figure>`).join('')}<figure>${image('research','연구자가 배양 접시를 들고 있는 복합배양 연구 표현 이미지')}<figcaption><h3>세 가지의 만남, GMK®</h3></figcaption></figure></div></div></section>
<section id="BB05" class="story-section story-bridge"><div class="container"><h2>연구에서 일상으로</h2><p class="story-intro">그리고 이 연구의 결실을 일상에서 보다 편안하게 만날 수 있도록 소비자 브랜드 ‘도두On’을 만들었습니다.</p><ol class="story-steps">${['기초연구','복합배양','도두On','일상'].map((t,i)=>`<li>${icon(['search','culture','leaf','globe'][i])}<h3>${t}</h3></li>`).join('')}</ol></div></section>
<section id="BB06" class="story-section story-meaning"><div class="container">${label('BRAND NAME')}<h2>도두On, 이름에 담은 의미</h2><div class="story-meanings">${[['도두','건강을 돋우고 기운을 돋우다'],['On','일상의 건강 스위치를 켜다'],['溫','따뜻한 마음을 담다']].map(([a,b])=>`<article><h3>${a}</h3><p>${b}</p></article>`).join('')}</div><p class="story-intro">보이지 않는 곳에서 시작된 작은 균사가 서로 연결되어 단단한 생명력으로 자라나듯, 도두On은 자연의 지혜와 기운찬의 연구를 연결해 우리의 일상에 건강한 힘을 더하고자 합니다.</p></div></section>
<section id="BB07" class="story-section story-white"><div class="container"><h2>도두On 제품에 담긴 GMK®</h2><p class="story-intro">도두On의 제품에는 제품의 특성에 맞게 기운찬의 복합버섯균사체 소재 GMK® 또는 GMK® 추출물이 담깁니다.</p><div id="products">${products}</div><details class="story-buying"><summary>제품 비교·구매 안내</summary>${comparison}<p>제품의 구성과 판매정보는 공식 판매처에서 확인하실 수 있습니다.</p><a class="text-link" href="/contact/?type=consumer">제품 구성·구매 문의 →</a></details><aside class="story-related" aria-label="관련 콘텐츠"><h3>관련 콘텐츠</h3><a href="/rnd/gmk/">GMK® 소재와 기술 →</a><a href="/rnd/evidence/">연구 근거 →</a><a href="/insights/">인사이트 →</a></aside></div></section>
<section id="BB08" class="story-section story-finale"><div class="container story-split"><figure>${image('gift','도두On 버섯마시면 기운차 선물세트 원본 제품 이미지')}</figure><div>${label('NATURE · SCIENCE · EVERYDAY')}<h2>건강을 돋우다.<br>기운을 돋우다.<br>일상의 건강을 켜다.</h2><p class="story-brand">도두On</p><a class="button" href="#products"><span>도두On 제품 만나보기</span><span aria-hidden="true">↗</span></a></div></div></section></div>`;}
