const {chromium}=require('C:/Users/coqqu/.cache/codex-runtimes/codex-primary-runtime/dependencies/node/node_modules/playwright');
const path=require('node:path');
const fs=require('node:fs');
(async()=>{const browser=await chromium.launch({headless:true,executablePath:'C:/Program Files (x86)/Microsoft/Edge/Application/msedge.exe'});const page=await browser.newPage({viewport:{width:1440,height:1000}});const errors=[];page.on('pageerror',e=>errors.push(e.message));const routes=JSON.parse(fs.readFileSync(path.join(__dirname,'../review/routes.json'),'utf8'));const results=[];
for(const width of [1440,390,360]){await page.setViewportSize({width,height:width>700?1000:844});for(const route of routes){const response=await page.goto('http://127.0.0.1:4173'+route);await page.evaluate(async()=>{document.querySelectorAll('img').forEach(im=>im.loading='eager');await Promise.all([...document.images].map(im=>im.decode().catch(()=>{})));});const state=await page.evaluate(()=>({overflow:document.documentElement.scrollWidth>innerWidth,broken:[...document.images].filter(im=>!im.naturalWidth).map(im=>im.src),h1:document.querySelectorAll('h1').length}));results.push({width,route,status:response.status(),...state});if([1440,390].includes(width)&&['/','/company/','/rnd/','/business/','/business/brands/','/ir/','/insights/','/contact/','/products/mushroom-giuncha/','/rnd/evidence/'].includes(route)){const name=route==='/'?'home':route.split('/').filter(Boolean).join('-');await page.screenshot({path:path.join(__dirname,`../review/${name}-${width}.png`),fullPage:true});if(route==='/')await page.screenshot({path:path.join(__dirname,`../review/home-viewport-${width}.png`)});}}}
const assert=(v,m)=>{if(!v)throw Error(m);};
await page.goto('http://127.0.0.1:4173/');await page.getByRole('button',{name:'메뉴 열기'}).click();assert(await page.locator('#main-nav').isVisible(),'menu open');await page.keyboard.press('Escape');assert(!(await page.locator('#main-nav').isVisible()),'menu close');
await page.goto('http://127.0.0.1:4173/contact/?type=ingredient&material=extract');assert(await page.locator('[name=interest]').inputValue()==='extract','material preselect');await page.locator('[name=type]').selectOption('consumer');assert(!(await page.locator('[name=company]').getAttribute('required')),'consumer optional');await page.getByRole('button',{name:'문의 내용 확인'}).click();assert((await page.locator('.result').innerText()).includes('필수'),'required validation');await page.locator('[name=name]').fill('테스트');await page.locator('[name=email]').fill('test@example.com');await page.locator('[name=message]').fill('전송하지 않는 화면 검수입니다.');await page.getByRole('button',{name:'문의 내용 확인'}).click();assert((await page.locator('.result').innerText()).includes('아직 접수되지 않았습니다'),'no false submission');
await page.goto('http://127.0.0.1:4173/insights/');await page.getByRole('button',{name:'보도자료',exact:true}).click();assert(await page.locator('#no-results').isVisible(),'empty category');await page.reload();assert(await page.getByRole('button',{name:'보도자료',exact:true}).getAttribute('aria-pressed')==='true','filter preserved');await page.getByRole('button',{name:'전체',exact:true}).click();await page.getByRole('searchbox').count();await page.locator('[name=q]').fill('GMK');await page.getByRole('button',{name:'검색',exact:true}).click();assert((await page.locator('#result-count').innerText()).includes('1'),'search');await page.goBack();assert((await page.locator('#result-count').innerText()).includes('2'),'back restores');
const missing=await page.goto('http://127.0.0.1:4173/not-a-page/');assert(missing.status()===404,'404');const failures=results.filter(r=>r.status!==200||r.overflow||r.broken.length||r.h1!==1);const report={checks:results.length,failures,consoleErrors:errors,interactions:'menu, Escape, material preselect, consumer optional, input validation, no false send, search, filter, reload, back, 404 passed',results};fs.writeFileSync(path.join(__dirname,'../review/browser-check.json'),JSON.stringify(report,null,2));console.log({checks:results.length,failures,consoleErrors:errors});await browser.close();if(failures.length||errors.length)process.exitCode=1;})().catch(e=>{console.error(e);process.exit(1)});
