import {insightsContent,pressDetail,pressMetadata,pressPath} from './press.mjs';
import {researchTimeline} from './research-timeline.mjs';
import {researchFocus} from './research-focus.mjs';
import {productizationPortfolio, productizationConsultation, productizationFAQ} from './productization.mjs';
import {keepOfficialNames} from './typography.mjs';
import {patentGallery} from './patent-gallery.mjs';
import {replacementImage, standardHeroRoute, heroImages} from './image-refresh.mjs';
import {brandStory} from './dodoon-editorial.mjs';
import {qualitySupport} from './quality-support.mjs';
import {individualArticle} from './individual-article.mjs';
import {myceliumArticle} from './mycelium-article.mjs';
import {formatHome} from './home-format.mjs';
import {icon, infographic, enhanceSection, sectionClass, productContent} from './visuals.mjs';
import fs from 'node:fs';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=path.resolve(path.dirname(fileURLToPath(import.meta.url)),'..');
const dist=path.join(root,'dist');
const raw=JSON.parse(fs.readFileSync(path.join(root,'content/scenario.json'),'utf8'));
const productizationProducts=JSON.parse(fs.readFileSync(path.join(root,'content/gmk-productization.json'),'utf8'));
const esc=s=>String(s).replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const paras=id=>raw[id].blocks.filter(b=>b.type==='paragraph'&&!/^(화면\s*[:：]|버튼\s*[:：]|편집 메모|출처 메모|※)/.test(b.text)).map(b=>b.text);
const p=s=>`<p>${esc(s)}</p>`;
const btn=(label,url,kind='')=>`<a class="button ${kind}" href="${esc(url)}"><span class="button-label">${esc(label)}</span><span aria-hidden="true">↗</span></a>`;
const link=(label,url)=>`<a class="text-link" href="${url}">${esc(label)} <span aria-hidden="true">→</span></a>`;
const picture=(name,alt,cl='')=>replacementImage(name,cl)||`<img class="${cl}" src="/assets/${/\.[a-z0-9]+$/i.test(name)?name:name+'.webp'}" alt="${esc(alt)}" loading="lazy" width="960" height="640">`;
const groups={company:[['기업소개','/company/'],['연혁·오시는 길','/company/history/'],['지속가능한 실천','/company/sustainability/']],rnd:[['연구개발 현황','/rnd/'],['보유 기술','/rnd/gmk/'],['연구 발자취','/rnd/evidence/'],['보유 특허','/rnd/patents/']],business:[['사업 개요','/business/'],['원료 공급','/business/ingredients/'],['제품화 지원','/business/development/'],['도두On','/business/brands/']]};
const brandSubmenus=[['브랜드 이야기','/business/brands/'],['제품 비교','/business/brands/#products']];
const pressPosts=JSON.parse(fs.readFileSync(path.join(root,'content/press-releases.json'),'utf8'));
const nav=[['회사소개','/company/'],['R&D','/rnd/'],['사업분야','/business/'],['도두On','/business/brands/'],['IR','/ir/'],['인사이트','/insights/']];
function header(url){
 const owner=url.startsWith('/products/')?'/business/brands/':nav.map(([,u])=>u).filter(u=>url.startsWith(u)).sort((a,b)=>b.length-a.length)[0];
 return `<a class="skip" href="#main">본문 바로가기</a><header class="site-header"><div class="container header-inner"><a href="/" class="logo" aria-label="기운찬 홈"><img src="/assets/logo.png" width="180" height="60" alt="Giunchan"></a><nav id="main-nav" aria-label="주 메뉴">${nav.map(([n,u],i)=>{
  const list=u==='/insights/'?[['연구자료','/insights/#research'],['보도자료','/insights/#press']]:u==='/business/brands/'?brandSubmenus:groups[u.split('/')[1]];
  const current=owner===u;
  if(!list)return `<a href="${u}" class="${current?'active':''}" ${url===u?'aria-current="page"':''}>${n}</a>`;
  const activeSub=list.filter(([,link])=>!link.includes('#')&&(url===link||(link!==u&&url.startsWith(link)))).sort((a,b)=>b[1].length-a[1].length)[0]?.[1];
  return `<div class="nav-item"><a class="nav-parent ${current?'active':''}" href="${u}" aria-haspopup="true" aria-expanded="false" aria-controls="nav-submenu-${i}" ${url===u?'aria-current="page"':''}>${n}</a><button class="nav-submenu-toggle" type="button" aria-label="${n} 하위 메뉴" aria-haspopup="true" aria-expanded="false" aria-controls="nav-submenu-${i}"><span aria-hidden="true"></span></button><button class="nav-mobile-trigger ${current?'active':''}" type="button" aria-haspopup="true" aria-expanded="false" aria-controls="nav-submenu-${i}">${n}<span aria-hidden="true"></span></button><div class="nav-dropdown" id="nav-submenu-${i}" hidden>${list.map(([label,href])=>`<a href="${href}" class="${href===activeSub?'active':''}" ${href===url?'aria-current="page"':''}>${label}</a>`).join('')}</div></div>`;
 }).join('')}<a class="nav-cta" href="/contact/?type=ingredient">원료 문의 <span aria-hidden="true">↗</span></a></nav><button class="menu-toggle" aria-expanded="false" aria-controls="main-nav" aria-label="메뉴 열기"><span></span><span></span></button></div></header>`;
}
function footer(){return `<footer><div class="container footer-top"><div><a href="/" class="logo"><img src="/assets/logo.png" width="180" height="60" alt="Giunchan 홈"></a><h2>주식회사 기운찬</h2><p>복합배양·발효 기술 기반 바이오소재 전문기업</p></div><div class="footer-links">${nav.map(([n,u])=>`<a href="${u}">${n}</a>`).join('')}<a href="/contact/">문의하기</a><a href="/privacy/">개인정보처리방침</a></div></div><div class="container footer-bottom"><p>대표: 박종례 · 사업자등록번호: 289-81-00204<br>충남 천안시 동남구 충절로 252, 2층<br><a href="tel:0415792203">041-579-2203</a> · <a href="mailto:guc2203@guc.co.kr">guc2203@guc.co.kr</a></p><p>Copyright © Giunchan Co., Ltd.<br>All rights reserved.</p></div></footer>`;}
function write(url,title,body,cl='',meta={}){if(url==='/rnd/patents/')body+=patentGallery();if(url==='/')body=formatHome(body);if(standardHeroRoute(url))body=body.replace('class="sub-hero"','class="sub-hero standard-hero"');let f=url==='/'?'index.html':url==='404'?'404.html':url.slice(1)+'index.html';fs.mkdirSync(path.dirname(path.join(dist,f)),{recursive:true});fs.writeFileSync(path.join(dist,f),`<!doctype html><html lang="ko"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><meta name="robots" content="noindex,nofollow"><title>${esc(title)} | 기운찬</title><meta name="description" content="${esc(meta.description||(title+' — 기운찬의 복합배양 기술과 GMK® 소재, 연구 및 사업을 소개합니다.'))}"><link rel="stylesheet" href="/style.css"><link rel="stylesheet" href="/visual.css?v=2">${url==="/business/brands/"?'<link rel="stylesheet" href="/dodoon-editorial.css">':' '}${url==='/'||standardHeroRoute(url)?'<link rel="stylesheet" href="/image-refresh.css">':''}${url==='/rnd/patents/'?'<link rel="stylesheet" href="/patent-gallery.css"><script src="/patent-gallery.js" defer></script>':''}${url==='/business/development/'?'<link rel="stylesheet" href="/productization.css"><script src="/productization.js" defer></script>':''}${url==='/rnd/'?'<link rel="stylesheet" href="/research-focus.css">':''}${url==='/rnd/evidence/'?'<link rel="stylesheet" href="/research-timeline.css">':''}${url==='/insights/'||url.startsWith('/insights/press/')?'<link rel="stylesheet" href="/press.css">':''}${url==='/insights/'?'<script src="/press.js" defer></script>':''}${meta.head||''}<script src="/app.js" defer></script></head><body class="${cl}">${keepOfficialNames(header(url))}<main id="main">${keepOfficialNames(body)}</main>${keepOfficialNames(footer())}</body></html>`);}
const eyebrow=t=>`<div class="eyebrow">${t}</div>`;
const section=(id,body,cl='')=>`<section id="${id}" class="section ${cl}" data-content-id="${id}"><div class="container">${body}</div></section>`;
function home(){const h=paras('H01');return `<section class="home-hero" data-content-id="H01"><img class="hero-bg" src="/assets/forest.webp" alt="숲과 버섯균사체를 표현한 자연 이미지" width="1920" height="900" fetchpriority="high"><div class="container hero-content">${eyebrow('GIUNCHAN · NATURE INTO SCIENCE')}<h1>${esc(h[0])}<br>${esc(h[1])}</h1><p>${esc(h[2])}</p><div class="actions">${btn('원료·협업 문의','/contact/?type=ingredient')}${btn('GMK® 기술 알아보기','/rnd/gmk/','outline-light')}</div><div class="hero-foot"><span>자연에서 발견하고, 연구로 이어갑니다</span><span aria-hidden="true">SCROLL TO EXPLORE ↓</span></div></div></section>`+
section('H02',`<div class="section-heading"><div>${eyebrow('OUR FOUNDATION')}<h2>${esc(paras('H02')[0])}</h2></div><div class="intro">${paras('H02').slice(1,3).map(p).join('')}</div></div><div class="stats"><div><strong>2015</strong><span>기운찬 설립</span></div><a href="/rnd/patents/"><strong>9<span>건</span></strong><span>국내 등록 특허</span></a><a href="/rnd/patents/"><strong>1<span>건</span></strong><span>미국 등록 특허</span></a><a href="/rnd/evidence/"><strong>4<span>건</span></strong><span>관련 SCIE급 논문</span></a></div><div class="section-tail"><small>회사 제공자료 기준 · 2026.08</small><div>${link('연구 성과 보기','/rnd/evidence/')} ${link('특허 보기','/rnd/patents/')}</div></div>`)+
section('H03',`<div class="split"><div class="visual">${picture('mixed-mushroom-mycelia-main.png','복합버섯균사체 연구 이미지','gmk-material-image')}<span class="image-label">GMK® · COMPOUND CULTURE</span></div><div>${eyebrow('OUR TECHNOLOGY')}<h2>${esc(paras('H03')[0])}</h2>${paras('H03').slice(1).map(p).join('')}${link('GMK®란 무엇인가요?','/rnd/gmk/')}</div></div><figure class="gmk-applications"><img src="/assets/gmk-applications.png" width="2169" height="725" loading="lazy" alt="현재 활용: 식품 원료·제품. 진행 중: 건강기능식품 원료 인정 절차. 향후 검토: 제약·화장품·동물사료."></figure>`,'soft')+
section('H04',`${eyebrow('RESEARCH & EVIDENCE')}<div class="section-heading"><h2>${esc(paras('H04')[0])}</h2><div class="intro">${p(paras('H04')[1])}</div></div><div class="research-grid">${paras('H04').slice(2).map((t,i)=>{let [a,b]=t.split(' — ');return `<article><span class="home-research-icon"><img class="${['research-functional','research-safety','research-human'][i]}" src="/assets/${['research-functional-evaluation','research-safety-evaluation','research-human-trial'][i]}-display.png" width="100" height="100" alt="" aria-hidden="true" loading="lazy" decoding="async"></span><span class="index">0${i+1}</span><h3>${esc(a)}</h3>${p(b)}</article>`}).join('')}</div>${link('연구개발 현황 보기','/rnd/')}`)+
section('H05',`${eyebrow('OUR BUSINESS')}<h2>${esc(paras('H05')[0])}</h2><div class="business-grid"><article class="business-card">${picture('culture','배양 소재를 표현한 연구 이미지')}<div><span class="eyebrow">FOR BUSINESS</span><h3>${esc(paras('H05')[1])}</h3>${p(paras('H05')[2])}${btn('B2B 원료·개발 보기','/business/ingredients/')}</div></article><article class="business-card brand-card">${picture('gift','버섯마시면 기운차 선물세트 이미지')}<div><span class="eyebrow">FOR YOUR EVERYDAY</span><h3>${esc(paras('H05')[3])}</h3>${p(paras('H05')[4])}${btn('브랜드·제품 보기','/business/brands/')}</div></article></div>`)+
section('H06',`<div class="split"><div>${eyebrow('INVESTOR RELATIONS')}<h2>${esc(paras('H06')[0])}</h2>${paras('H06').slice(1).map(p).join('')}${btn('사업모델과 성장 방향','/ir/','outline-light')}</div><div class="big-type">연구의 축적,<br><span>성장의 시작.</span></div></div>`,'dark')+
section('H07',`<div class="split"><div class="visual">${picture('nature','흙 위에 자라는 새싹 이미지')}</div><div>${eyebrow('SMALL ACTIONS, LASTING VALUE')}<h2>${esc(paras('H07')[0])}</h2>${paras('H07').slice(1).map(p).join('')}${link('지속가능한 실천','/company/sustainability/')}</div></div>`)+
section('H08',`<div class="section-heading"><div>${eyebrow('INSIGHTS')}<h2>${esc(paras('H08')[0])}</h2>${p(paras('H08')[1])}</div>${link('전체 소식 보기','/insights/')}</div><div class="insight-grid">${articleCards()}</div>`,'soft')+
section('H09',`${eyebrow('LET’S GROW TOGETHER')}<h2>${esc(paras('H09')[0])}</h2>${p(paras('H09')[1])}<div class="actions">${btn('원료 공급 문의','/contact/?type=ingredient')}${btn('제품개발 문의','/contact/?type=development','outline')}${btn('투자·사업협력 문의','/contact/?type=partnership','outline')}</div>`,'contact-band');}
function articleCards(){return [['버섯균사체란 무엇인가요?','버섯과의 차이부터 균사체의 역할과 배양까지','insight-mycelium-thumbnail.png','what-is-gmk'],['개별인정형 원료란 무엇인가요?','일반 식품 원료와 무엇이 다르고, 어떻게 인정받는지 알아보기','insight-individual-approval','human-study-and-approval']].map(([t,d,im,slug])=>`<article class="insight-card" data-category="research"><a href="/insights/${slug}/">${picture(im,t)}<div><span class="eyebrow">연구소개</span><h3>${t}</h3><p>${d}</p><span class="text-link">자세히 보기 →</span></div></a></article>`).join('');}
write('/','복합배양 기술 기반 천연물 바이오소재 GMK®',home());
write('404','페이지를 찾을 수 없습니다',section('not-found','<h1>페이지를 찾을 수 없습니다</h1><p>주소를 확인하거나 홈에서 다시 시작해 주세요.</p>'+btn('홈으로','/')));

const range=(prefix,n)=>Array.from({length:n},(_,i)=>prefix+String(i+1).padStart(2,'0'));
const routes=[['/company/','회사소개','ABOUT GIUNCHAN',range('C',7)],['/company/history/','연혁·오시는 길','OUR HISTORY',[...range('CH',2),'CL01']],['/company/sustainability/','지속가능한 실천','SUSTAINABILITY',range('CS',5)],['/company/location/','오시는 길','VISIT GIUNCHAN',['CL01']],['/rnd/','연구개발 현황','RESEARCH & DEVELOPMENT',range('R',4)],['/rnd/gmk/','GMK® 소재와 기술','OUR TECHNOLOGY',range('RG',5)],['/rnd/evidence/','연구 근거','RESEARCH EVIDENCE',range('RE',4)],['/rnd/patents/','특허','INTELLECTUAL PROPERTY',range('RP',2)],['/business/','사업분야','OUR BUSINESS',range('B',5)],['/business/ingredients/','B2B 원료 공급','OUR MATERIALS',['BI01','BI05']],['/business/ingredients/gmk/','GMK® 분말','OUR MATERIALS',['BI02','BI05']],['/business/ingredients/extract/','GMK®추출물','OUR MATERIALS',['BI03','BI05']],['/business/ingredients/liquid/','GMK®추출액','OUR MATERIALS',['BI04','BI05']],['/business/development/','제품화 지원','PRODUCT DEVELOPMENT',range('BD',4)],['/ir/','IR·투자협력','INVESTOR RELATIONS',range('I',6)],['/insights/what-is-gmk/','GMK®란 무엇인가요?','TECHNOLOGY INSIGHT',['N02']],['/insights/human-study-and-approval/','개별인정형 원료란 무엇인가요?','RESEARCH INSIGHT',['N03']]];
const myceliumRoute=routes.find(([url])=>url==='/insights/what-is-gmk/');
if(myceliumRoute){myceliumRoute[1]='버섯균사체란 무엇인가요?';myceliumRoute[2]='RESEARCH INSIGHT';}
raw.N02.blocks.filter(block=>block.type==='paragraph')[0].text='버섯균사체란 무엇인가요?';
raw.N02.blocks.filter(block=>block.type==='paragraph')[1].text='버섯과의 차이부터 자연에서의 역할, 식품 소재를 위한 배양 연구까지 쉽게 알아봅니다.';
heroImages['/insights/what-is-gmk/']='insight-mycelium-hero.png';
const products=[['P01','masimyeon-giuncha','drink'],['P02','mushroom-giuncha','tea'],['P03','giuncha-concentrate','concentrate'],['P04','ttokttok-jelly','jelly'],['P05','mushroom-spoon','spoon'],['P06','immun-mk','immun'],['P07','giunchan-bon','bon'],['P08','cognican',null]];
const materials=[['GMK® 분말','복합버섯균사체 분말','gmk'],['GMK®추출물','분말형 추출 소재','extract'],['GMK®추출액','액상 추출 소재','liquid']];
const tracked=new Map(range('H',9).map(id=>[id,['/']]));
function track(id,url){tracked.set(id,[...new Set([...(tracked.get(id)||[]),url])]);}
function subnav(){return '';} // Submenus now live in the shared header.
function subhero(title,kicker,desc='',im='research'){return `<section class="sub-hero">${replacementImage(im,'',true)||picture(im,'기운찬 소재 연구를 표현한 이미지')}<div class="container">${eyebrow(kicker)}<h1>${esc(title)}</h1>${desc?p(desc):''}</div></section>`;}
function contactUrl(id){if(id==='BI02')return '/contact/?type=ingredient&material=gmk';if(id==='BI03')return '/contact/?type=ingredient&material=extract';if(id==='BI04')return '/contact/?type=ingredient&material=liquid';if(id.startsWith('BI'))return '/contact/?type=ingredient';if(id.startsWith('BD'))return '/contact/?type=development';if(id.startsWith('I')||id.startsWith('R')||id==='B05')return '/contact/?type=partnership';return '/contact/';}
function contentButtons(id){if(id.startsWith('P'))return '';if(id==='BB07')return btn('제품 자세히 보기','/business/brands/#products');if(id==='BB08')return btn('제품 구매 문의','/contact/?type=consumer');if(id==='CL01')return btn('문의 남기기','/contact/');const lines=raw[id].blocks.filter(b=>b.type==='paragraph'&&b.text.startsWith('버튼:'));return lines.map(b=>b.text.slice(3).split(' | ').map(t=>{const m=t.match(/^(.+?)\s*→\s*(\/[^\s]*)/);return m?btn(m[1].trim(),m[2]==='/contact/'?contactUrl(id):m[2],'outline'):''}).join('')).join('');}
function publicBlocks(id){return raw[id].blocks.filter(b=>b.type==='table'||(!/^(화면\s*[:：]|버튼\s*[:：]|편집 메모|출처 메모|※)/.test(b.text)&&b.text!=='브랜드 로고와 핵심 메시지를 중심으로 구성합니다.'));}
function renderBlocks(blocks){let html='';for(let i=0;i<blocks.length;i++){const b=blocks[i];if(b.type==='table'){html+=`<div class="table-wrap"><table>${b.rows.map((r,j)=>`<tr>${r.map(c=>`<${j?'td':'th'}>${esc(c)}</${j?'td':'th'}>`).join('')}</tr>`).join('')}</table></div>`;continue;}const t=b.text;if(t.startsWith('Q.')&&blocks[i+1]?.text?.startsWith('A.')){html+=`<details><summary>${esc(t)}</summary>${p(blocks[++i].text)}</details>`;}else if(t.includes('https://doi.org/')){const u=t.match(/https:\/\/doi.org\/\S+/)[0];html+=`<p><a class="text-link" href="${u}" target="_blank" rel="noopener noreferrer">논문 원문 보기 ↗</a></p>`;}else if(t.length<45&&!/[.!?。]$/.test(t)&&!t.includes(' / ')&&!t.startsWith('A.')){html+=`<h3>${esc(t)}</h3>`;}else html+=p(t);}return html;}
function cards(list){return `<div class="route-cards">${list.map(([n,d,u])=>`<a class="route-card" href="${u}"><h3>${esc(n)}</h3>${p(d)}<span class="text-link">자세히 보기 →</span></a>`).join('')}</div>`;}
function productCards(){return `<div class="product-grid">${products.map(([id,slug,im])=>`<article class="product-card"><a href="/products/${slug}/">${im?picture(im,raw[id].title+' 제공 제품 이미지'):'<div class="product-no-image"><strong>코그니칸</strong><span>GMK®추출물 활용 제품</span></div>'}<h3>${esc(raw[id].title)}</h3>${p(paras(id)[0])}<span class="text-link">제품 자세히 보기 →</span></a></article>`).join('')}</div>`;}
function article(id,url,omit=0){track(id,url);if(id==='N02')return myceliumArticle();if(url==='/rnd/'&&id==='R03')return researchFocus();if(url==='/business/development/'&&id==='BD04')return productizationPortfolio(productizationProducts)+productizationConsultation()+productizationFAQ();let blocks=publicBlocks(id).slice(omit);let heading=raw[id].title.replace(/^인사이트 원고\s*[—]?\s*/,'');if(/첫 화면|마무리|^정의$/.test(heading)&&blocks[0]?.type==='paragraph'){heading=blocks.shift().text;}let html=(url==='/rnd/evidence/'&&id==='RE02'?researchTimeline():'')+`<section class="article-section ${sectionClass(id)}" id="${id}" data-content-id="${id}"><div class="section-kicker">${esc(({C:'ABOUT GIUNCHAN',CH:'OUR HISTORY',CS:'SUSTAINABILITY',R:'RESEARCH & DEVELOPMENT',RG:'GMK® TECHNOLOGY',RE:'RESEARCH EVIDENCE',RP:'INTELLECTUAL PROPERTY',RQ:'QUALITY',B:'BUSINESS',BI:'INGREDIENTS',BD:'PRODUCT DEVELOPMENT',BB:'DODOON STORY',I:'INVESTOR RELATIONS',N:'INSIGHTS'})[id.replace(/\d/g,'')]||'GIUNCHAN')}</div><h2>${esc(heading)}</h2>${enhanceSection(id,blocks,renderBlocks)}`;
if(id==='BB07'){track('P09',url);html+=`<div id="products">${productCards()}<h3>제품 비교</h3>${renderBlocks(publicBlocks('P09').filter(b=>b.type==='table'))}</div>`;}
html+=`<div class="actions">${contentButtons(id)}</div></section>`;if(id==='BD02'){for(const q of range('RQ',3))track(q,url);html+=qualitySupport();}return html;}
for(const [url,title,kicker,ids] of routes){if(url==='/company/location/'){write(url,'연혁·오시는 길','<meta http-equiv="refresh" content="0;url=/company/history/#CL01"><div class="container section"><h1>연혁·오시는 길</h1><a href="/company/history/#CL01">오시는 길 확인하기 →</a></div>');continue;}if(ids[0]==='N03'){track('N03',url);write(url,title,subhero(title,kicker,'식약처 인정 절차 쉽게 알아보기','insight-individual-approval')+'<div class="container article-wrap reading">'+individualArticle()+'</div>');continue;}const first=paras(ids[0]);const visual=heroImages[url]||(url.includes('sustainability')?'nature':url.includes('history')?'mycelium':url.includes('evidence')?'microscope':url.startsWith('/business/')?'research':url==='/ir/'?'science':'research');const lines=(first[0].endsWith(',')&&first[1]?.length<35)?2:1;const heroTitle=first.slice(0,lines).join(' ');const consumed=lines+1;track(ids[0],url);let content=ids.map((id,i)=>i===0?(publicBlocks(id).length>consumed?article(id,url,consumed):`<div class="actions">${contentButtons(id)}</div>`):article(id,url)).join('');
write(url,title,`<div data-content-id="${ids[0]}">`+subhero(heroTitle,kicker,first[lines]||'',visual)+'</div>'+subnav(url)+`<div class="container article-wrap ${url.startsWith('/insights/')?'reading':''}">${content}</div>`);}
const brandUrl='/business/brands/';for(const id of range('BB',8))track(id,brandUrl);track('P09',brandUrl);
write(brandUrl,'도두On 브랜드·제품',brandStory()+'<script>if(location.hash==="#products")location.replace("/products/");</script>','brand-page');
write('/products/','도두On 제품',subhero('도두On 제품에 담긴 GMK®','DODOON','도두On의 제품에는 제품의 특성에 맞게 기운찬의 복합버섯균사체 소재 GMK® 또는 GMK® 추출물이 담깁니다.','gift')+`<section class="section"><div class="container" id="products">${productCards()}<details><summary>제품 비교·구매 안내</summary>${renderBlocks(publicBlocks('P09').filter(b=>b.type==='table'))}<p>제품의 구성과 판매정보는 공식 판매처에서 확인하실 수 있습니다.</p>${link('제품 구성·구매 문의','/contact/?type=consumer')}</details></div></section>`);

for(const [id,slug,im] of products){const url=`/products/${slug}/`;track(id,url);track('P09',url);const ps=paras(id);let body=`<div class="container"><section class="product-hero" data-content-id="${id}">${im?picture(im,raw[id].title+' 제공 제품 이미지'):'<div class="product-no-image"><strong>코그니칸</strong><span>GMK®추출물 활용 제품</span></div>'}<div>${eyebrow('DODOON · PRODUCT')}<h1>${esc(raw[id].title)}</h1><h2>${esc(ps[0])}</h2>${p(ps[1])}${btn('제품 문의하기',`/contact/?type=consumer&product=${slug}`)}<p class="availability">현재 구성과 구매 가능 여부는 문의로 확인해 주세요.</p></div></section><div class="article-wrap">${productContent(publicBlocks(id).slice(2),renderBlocks,im)}<section class="article-section product-information" data-content-id="P09"><h2>제품을 자세히 확인하세요</h2>${p('제품명 / 식품유형 / 내용량 / 원재료·알레르기 정보 / 영양·기능정보 / 섭취·사용법 / 주의사항 / 보관방법 / 제조원 / 판매원.')}<p>상세 표시정보와 현재 판매 구성은 제품 문의를 통해 확인해 주세요.</p>${btn('제품 정보 문의',`/contact/?type=consumer&product=${slug}`,'outline')}</section></div></div>`;write(url,raw[id].title,subnav(url)+body);}
track('N01','/insights/');write('/insights/','인사이트',subhero('소재를 이해하는 이야기, 기운찬이 만들어 가는 소식','INSIGHTS',paras('N01')[2],heroImages['/insights/'])+insightsContent(articleCards(),pressPosts));
for(const post of pressPosts){write(pressPath(post),post.title,pressDetail(post),'',{description:post.summary,head:pressMetadata(post)});write(`/newsroom/${post.slug}/`,post.title,`<section class="container section"><h1>${esc(post.title)}</h1><p>보도자료 상세페이지로 이동합니다.</p><a href="${pressPath(post)}">보도자료 보기 →</a></section>`,'',{head:`<meta http-equiv="refresh" content="0;url=${pressPath(post)}">`});}
for(const id of range('CT',4))track(id,'/contact/');
write('/contact/','문의하기',subhero(paras('CT01')[0],'CONTACT GIUNCHAN',paras('CT01')[1])+`<div class="container contact-layout"><aside>${picture('brand','자연과 함께하는 소재 연구','contact-photo')}<h2>기운찬과 연결하세요</h2><p>원료 도입부터 제품개발,<br>투자·사업협력까지.</p><h3>${icon('phone')}전화 문의</h3><a class="text-link" href="tel:0415792203">041-579-2203</a><h3>${icon('mail')}이메일 문의</h3><a class="text-link" href="mailto:guc2203@guc.co.kr">guc2203@guc.co.kr</a><p class="availability">충남 천안시 동남구 충절로 252, 2층</p></aside><form class="contact-form" novalidate data-content-id="CT01 CT02 CT03 CT04"><p class="form-note">온라인 문의 접수는 준비 중입니다. 아래에서 문의 내용을 정리할 수 있으며, 실제 문의는 전화 또는 이메일로 연락해 주세요.</p><label>문의 유형<select name="type"><option value="ingredient">원료 공급</option><option value="development">제품개발</option><option value="partnership">투자·사업협력</option><option value="consumer">소비자 제품</option></select></label><p id="type-help" class="muted"></p><div class="form-grid"><label>회사·기관명 <span id="company-required">(필수)</span><input name="company" autocomplete="organization" required placeholder="회사 또는 기관명을 입력해 주세요."></label><label>담당자명 (필수)<input name="name" autocomplete="name" required placeholder="연락받으실 분의 성함을 입력해 주세요."></label><label>이메일 (필수)<input name="email" type="email" autocomplete="email" required placeholder="답변받으실 이메일 주소를 입력해 주세요."></label><label>전화번호 (선택)<input name="phone" type="tel" autocomplete="tel" placeholder="전화 상담을 원하시면 입력해 주세요."></label></div><label>관심 소재·제품<select name="interest"><option value="">선택해 주세요</option><optgroup label="원료">${materials.map(([n,d,s])=>`<option value="${s}">${n}</option>`).join('')}</optgroup><optgroup label="제품">${products.map(([id,s])=>`<option value="${s}">${raw[id].title}</option>`).join('')}</optgroup></select></label><label>문의 내용 (필수)<textarea name="message" required placeholder="사용 목적, 필요한 자료, 예상 수량이나 일정 등 문의 내용을 남겨주세요."></textarea></label><p class="muted">이 화면의 입력 내용은 서버에 전송하거나 저장하지 않습니다.</p><button class="button" type="submit">문의 내용 확인 <span aria-hidden="true">→</span></button><p class="result" role="status" aria-live="polite"></p></form></div>`);
write('/privacy/','개인정보처리방침',section('privacy','<h1>개인정보처리방침</h1><p>온라인 문의 접수를 위한 개인정보처리방침을 준비하고 있습니다. 현재 온라인 양식은 접수·저장 기능을 제공하지 않습니다.</p>'+btn('문의 안내','/contact/')));
fs.writeFileSync(path.join(dist,'robots.txt'),'User-agent: *\nDisallow: /\n');
const coverage=Object.keys(raw).map(id=>({id,title:raw[id].title,urls:tracked.get(id)||[],status:id.startsWith('E')?'제작 규칙 검토':tracked.has(id)?'로컬 초안 구현':'실제 기사 자료 대기',note:id==='N03'?'사용자 제공 개별인정형 원료 블로그 원고(2026-09-10)로 교체':id==='P09'?'표시정보 항목 배치; 상세값·구매 FAQ 보류':id.startsWith('P')?'현행 라벨·공식 상품 URL 공개 검수 필요':id==='N04'?'기사 원문·발행정보 미확정; 가짜 기사 생성 안 함':'전체 공개 검수 전'}));
fs.writeFileSync(path.join(root,'review/content-coverage.json'),JSON.stringify(coverage,null,2));
fs.writeFileSync(path.join(root,'review/content-coverage.csv'),'\uFEFFID,원고제목,URL,상태,비고\n'+coverage.map(o=>[o.id,o.title,o.urls.join(' | '),o.status,o.note].map(v=>'"'+v.replaceAll('"','""')+'"').join(',')).join('\n'));
write('/rnd/quality/','제품화 지원으로 이동','<meta http-equiv="refresh" content="0;url=/business/development/"><section class="section container"><h1>제품화 지원으로 이동합니다</h1><a href="/business/development/">제품화 지원 보기 →</a></section>');
const routeUrls=[...pressPosts.map(pressPath),...pressPosts.map(p=>`/newsroom/${p.slug}/`),'/products/','/',...routes.map(r=>r[0]),brandUrl,...products.map(([id,s])=>`/products/${s}/`),'/insights/','/contact/','/privacy/'];
fs.writeFileSync(path.join(root,'review/routes.json'),JSON.stringify(routeUrls,null,2));
console.log(`${routeUrls.length} local draft pages built; ${coverage.length} content IDs tracked. No deployment performed.`);

fs.writeFileSync(path.join(dist,'sitemap.xml'),'<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">'+routeUrls.filter(u=>!u.startsWith('/newsroom/')).map(u=>{const post=pressPosts.find(p=>pressPath(p)===u);return `<url><loc>https://giunchan-website.guc2103m.chatgpt.site${u}</loc>${post?.updatedAt?`<lastmod>${post.updatedAt}</lastmod>`:''}</url>`}).join('')+'</urlset>');
