import test from 'node:test';import assert from 'node:assert/strict';import sharp from 'sharp';
import {validateTree,referencedAssets,seoulDate} from '../lib/content-document.mjs';
import {renderTree,safeStyle} from '../lib/content-tree.mjs';
import {renderCard,renderArticle,optimizeImageHTML} from '../lib/content-render.mjs';
import handler from '../api/editor.js';
const res=()=>({code:0,body:'',writeHead(code){this.code=code;},end(s){this.body=s;}});
test('formatting whitelist preserves readable styles and rejects executable attributes/URLs',()=>{
 const n={type:'element',tag:'span',attrs:{style:'font-size: 22px;color: rgb(10, 50, 30);text-decoration: underline'},children:[{type:'element',tag:'sup',children:[{type:'text',text:'®'}]}]};
 assert.doesNotThrow(()=>validateTree([n]));assert.match(renderTree(n),/font-size: 22px/);
 for(const attrs of [{onclick:'evil()'},{href:'javascript:alert(1)'},{src:'data:text/html,evil'},{srcset:'javascript:alert(1) 2x'},{style:'background-image:url(https://bad.test)'}])assert.throws(()=>validateTree([{type:'element',tag:'a',attrs}]));
 assert.equal(safeStyle('color:red;position:fixed;top:0'),'color:red');
});
test('Seoul dates match between card and detail',()=>{const p={title:'test',category:'research-insight',published_at:'2026-10-01T15:00:00Z',content:{blocks:[]}};assert.equal(seoulDate(p.published_at),'2026-10-02');assert.match(renderCard(p),/>2026-10-02</);assert.match(renderArticle(p),/>2026-10-02</);assert.ok(!renderCard({...p,published_at:null}).includes('<time'));});
test('v2 manifest includes inline/gallery original and only its approved derived paths',()=>{const p='588cb2b6-e972-4831-8f83-5497582f16e8/photo.png',v={body:{path:p+'.body-v1.webp'},thumb:{path:p+'.thumb-v1.webp'}};const paths=referencedAssets([{type:'element',tag:'img',attrs:{src:'/api/content?action=asset&path='+encodeURIComponent(p)}}],null,{[p]:v});assert.deepEqual(paths,[p,v.body.path,v.thumb.path]);assert.deepEqual(referencedAssets([],null,{[p]:v}),[]);});
test('optimized cards use smaller source with responsive candidates and eager loading',()=>{const p='588cb2b6-e972-4831-8f83-5497582f16e8/photo.png',v={thumb:{path:p+'.thumb-v1.webp',width:800,height:500},body:{path:p+'.body-v1.webp',width:1600,height:1000}};const html=optimizeImageHTML(renderCard({thumbnail_path:p}),{[p]:v},true);assert.match(html,/thumb-v1.webp/);assert.match(html,/width="800"/);assert.match(html,/srcset=/);assert.match(html,/loading="eager"/);});
test('editor rejects unauthenticated save without contacting storage',async()=>{const r=res();await handler({method:'POST',headers:{},body:{}},r);assert.equal(r.code,401);});
test('server rejects unsafe tree before updating a post',async()=>{const old=global.fetch;let writes=0;try{global.fetch=async(url,options)=>{if(options.method)writes++;return new Response(JSON.stringify(url.endsWith('/user')?{id:'admin'}:[{user_id:'admin'}]));};const r=res();await handler({method:'POST',headers:{authorization:'Bearer test'},body:{action:'save',post:{slug:'safe',status:'draft',content:{blocks:[{type:'element',tag:'script',children:[]}]}}}},r);assert.equal(r.code,400);assert.equal(writes,0);}finally{global.fetch=old;}});
test('server retains initial timestamp on normal save and adds only referenced assets',async()=>{const old=global.fetch;let saved;const p={id:'existing',slug:'example',updated_at:'before',published_at:'2026-10-01T17:45:00Z',details:{ever_published:true},status:'published',content:{blocks:[]}};try{global.fetch=async(url,options={})=>{if(options.method==='PATCH'){saved=JSON.parse(options.body);return new Response(JSON.stringify([saved]));}return new Response(JSON.stringify(url.endsWith('/user')?{id:'admin'}:url.includes('content_admins')?[{user_id:'admin'}]:[p]));};const r=res();await handler({method:'POST',headers:{authorization:'Bearer test'},body:{action:'save',id:p.id,updated_at:p.updated_at,post:{...p,published_at:'2026-10-01T15:00:00Z'}}},r);assert.equal(r.code,200);assert.equal(saved.published_at,p.published_at);}finally{global.fetch=old;}});
test('image derivation keeps small transparent images at original size',async()=>{const source=await sharp({create:{width:100,height:50,channels:4,background:{r:0,g:100,b:0,alpha:.3}}}).png().toBuffer();const out=await sharp(source).rotate().resize({width:800,withoutEnlargement:true}).webp({quality:90}).toBuffer();const m=await sharp(out).metadata();assert.equal(m.width,100);assert.equal(m.height,50);assert.equal(m.hasAlpha,true);});
