import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs/promises';
import vm from 'node:vm';
import handler,{articleDocument} from '../api/content.js';
import {renderBlocks,renderCard,renderArticle,safeLink} from '../lib/content-render.mjs';
const post={id:'example',title:'균사 <script>alert(1)</script>',slug:'cms-test',category:'research-insight',summary:'버섯 이야기',author:'주식회사 기운찬',published_at:'2026-10-02T00:00:00Z',updated_at:'2026-10-02T01:00:00Z',content:{blocks:[{type:'paragraph',text:'본문 내용'},{type:'faq',question:'균사란?',answer:'실처럼 자라는 조직'}]},details:{}};
test('본문과 카드에 입력한 HTML은 실행되지 않고 링크는 http(s)만 허용한다',()=>{const html=renderBlocks([{type:'paragraph',text:'<img src=x onerror=alert(1)>'},{type:'link',url:'javascript:alert(1)',text:'bad'},{type:'table',rows:[['<script>','test']]}]);assert.ok(!html.includes('<script>'));assert.ok(!html.includes('javascript:'));assert.ok(html.includes('&lt;img'));assert.ok(!renderCard(post).includes('<script>'));assert.equal(safeLink('data:text/html,test'),'');});
test('SEO·본문은 서버에서 출력되고 기존 canonical과 구조화 데이터는 교체된다',()=>{const shell='<html><head><title>old</title><link rel="canonical" href="wrong"><script type="application/ld+json">{}</script></head><body><header>shared</header><main id="main">old body</main></body></html>';const html=articleDocument(shell,post,[],'https://www.guc.co.kr');assert.ok(html.includes('본문 내용'));assert.ok(html.includes('https://www.guc.co.kr/insights/cms-test/'));assert.ok(!html.includes('href="wrong"'));assert.equal((html.match(/application\/ld\+json/g)||[]).length,1);assert.ok(html.includes('\\u003cscript'));assert.ok(html.includes('<header>shared</header>'));});
test('공개 본문은 명시적으로 연결한 PDF만 포함한다',()=>{const assets=[{kind:'pdf',storage_path:'private.pdf',original_name:'비공개'},{kind:'pdf',storage_path:'public.pdf',original_name:'공개'}];const html=renderArticle({...post,details:{attachments:['public.pdf']}},assets);assert.ok(html.includes('public.pdf'));assert.ok(!html.includes('private.pdf'));});
function response(){let code=200,body;return {setHeader(){},writeHead(n){code=n},end(v){body=v},get code(){return code},get body(){return String(body)}};}
test('CMS 장애에도 기존 인사이트 페이지는 보존된다',async()=>{const fetchOriginal=global.fetch;process.env.SUPABASE_URL='https://example.supabase.co';process.env.SUPABASE_PUBLISHABLE_KEY='test';global.fetch=async()=>{throw new Error('offline')};try{const res=response();await handler({url:'/insights/',method:'GET'},res);assert.equal(res.code,200);assert.ok(res.body.includes('article-list'));}finally{global.fetch=fetchOriginal;}});
test('새 글은 SSR로 표시되고 미존재 글은 404다',async()=>{const fetchOriginal=global.fetch;global.fetch=async url=>new Response(JSON.stringify(String(url).includes('post_assets')?[]:String(url).includes('cms-test')?[post]:[]),{headers:{'Content-Type':'application/json'}});try{let res=response();await handler({url:'/insights/cms-test/',method:'GET'},res);assert.equal(res.code,200);assert.ok(res.body.includes('본문 내용'));res=response();await handler({url:'/insights/missing/',method:'GET'},res);assert.equal(res.code,404);}finally{global.fetch=fetchOriginal;}});
test('뉴스룸 카드는 공유 헤더가 아니라 뉴스룸 제목 아래 삽입된다',async()=>{const fetchOriginal=global.fetch;global.fetch=async()=>new Response(JSON.stringify([{...post,category:'newsroom'}]));try{const res=response();await handler({url:'/newsroom/',method:'GET'},res);assert.ok(res.body.indexOf('aria-label="최신 게시물"')>res.body.indexOf('newsroom-heading'));}finally{global.fetch=fetchOriginal;}});
test('Vercel 환경변수가 없어도 공개 연결 정보를 반환한다',async()=>{const oldURL=process.env.SUPABASE_URL,oldKey=process.env.SUPABASE_PUBLISHABLE_KEY;delete process.env.SUPABASE_URL;delete process.env.SUPABASE_PUBLISHABLE_KEY;try{const res=response();await handler({url:'/api/content?action=config',method:'GET'},res);assert.equal(res.code,200);const c=JSON.parse(res.body);assert.equal(c.url,'https://ngxiztotgjhcpcphqzag.supabase.co');assert.ok(c.key.startsWith('sb_publishable_'));assert.ok(Array.isArray(c.reservedSlugs));}finally{if(oldURL===undefined)delete process.env.SUPABASE_URL;else process.env.SUPABASE_URL=oldURL;if(oldKey===undefined)delete process.env.SUPABASE_PUBLISHABLE_KEY;else process.env.SUPABASE_PUBLISHABLE_KEY=oldKey;}});
test('연결 API 실패 후에도 로그인 버튼에서 undefined.url 오류가 발생하지 않는다',async()=>{const source=(await fs.readFile('dist/admin.js','utf8')).replace(/^import .*;\n/gm,'');const nodes=new Map();const node=s=>{if(!nodes.has(s))nodes.set(s,{value:s==='#email'?'guc2203@naver.com':'test',textContent:'',classList:{toggle(){}},hidden:false});return nodes.get(s);};const calls=[];const context={publicCMSConfig:{url:'https://test.supabase.co',key:'test-public'},document:{querySelector:node,querySelectorAll:()=>[]},window:{addEventListener(){}},sessionStorage:{getItem:()=>null,setItem(){},removeItem(){}},URL,Map,Date,JSON,structuredClone,fetch:async(url)=>{calls.push(url);if(url==='/api/content?action=config')return new Response('',{status:503});if(url==='/cms-reserved.json')return new Response('[]');return new Response('{}',{status:400});},Promise};await vm.runInNewContext('(async()=>{'+source+'})()',context);node('#login-form').onsubmit({preventDefault(){}});await new Promise(resolve=>setTimeout(resolve,10));assert.ok(calls.includes('https://test.supabase.co/auth/v1/token?grant_type=password'));assert.ok(!node('#message').textContent.includes('undefined'));assert.ok(node('#message').textContent.includes('요청에 실패'));});
