import test from 'node:test';
import assert from 'node:assert/strict';
import handler,{articleDocument} from '../api/content.js';
import {renderBlocks,renderCard,renderArticle,safeLink} from '../lib/content-render.mjs';
const post={id:'example',title:'균사 <script>alert(1)</script>',slug:'cms-test',category:'research-insight',summary:'버섯 이야기',author:'주식회사 기운찬',published_at:'2026-10-02T00:00:00Z',updated_at:'2026-10-02T01:00:00Z',content:{blocks:[{type:'paragraph',text:'본문 내용'},{type:'faq',question:'균사란?',answer:'실처럼 자라는 조직'}]},details:{}};
test('본문과 카드에 입력한 HTML은 실행되지 않고 링크는 http(s)만 허용한다',()=>{const html=renderBlocks([{type:'paragraph',text:'<img src=x onerror=alert(1)>'},{type:'link',url:'javascript:alert(1)',text:'bad'},{type:'table',rows:[['<script>','test']]}]);assert.ok(!html.includes('<script>'));assert.ok(!html.includes('javascript:'));assert.ok(html.includes('&lt;img'));assert.ok(!renderCard(post).includes('<script>'));assert.equal(safeLink('data:text/html,test'),'');});
test('SEO·본문은 서버에서 출력되고 기존 canonical과 구조화 데이터는 교체된다',()=>{const shell='<html><head><title>old</title><link rel="canonical" href="wrong"><script type="application/ld+json">{}</script></head><body><header>shared</header><main id="main">old body</main></body></html>';const html=articleDocument(shell,post,[],'https://www.guc.co.kr');assert.ok(html.includes('본문 내용'));assert.ok(html.includes('https://www.guc.co.kr/insights/cms-test/'));assert.ok(!html.includes('href="wrong"'));assert.equal((html.match(/application\/ld\+json/g)||[]).length,1);assert.ok(html.includes('\\u003cscript'));assert.ok(html.includes('<header>shared</header>'));});
test('공개 본문은 명시적으로 연결한 PDF만 포함한다',()=>{const assets=[{kind:'pdf',storage_path:'private.pdf',original_name:'비공개'},{kind:'pdf',storage_path:'public.pdf',original_name:'공개'}];const html=renderArticle({...post,details:{attachments:['public.pdf']}},assets);assert.ok(html.includes('public.pdf'));assert.ok(!html.includes('private.pdf'));});
function response(){let code=200,body;return {setHeader(){},writeHead(n){code=n},end(v){body=v},get code(){return code},get body(){return String(body)}};}
test('CMS 장애에도 기존 인사이트 페이지는 보존된다',async()=>{const fetchOriginal=global.fetch;process.env.SUPABASE_URL='https://example.supabase.co';process.env.SUPABASE_PUBLISHABLE_KEY='test';global.fetch=async()=>{throw new Error('offline')};try{const res=response();await handler({url:'/insights/',method:'GET'},res);assert.equal(res.code,200);assert.ok(res.body.includes('article-list'));}finally{global.fetch=fetchOriginal;}});
test('새 글은 SSR로 표시되고 미존재 글은 404다',async()=>{const fetchOriginal=global.fetch;global.fetch=async url=>new Response(JSON.stringify(String(url).includes('post_assets')?[]:String(url).includes('cms-test')?[post]:[]),{headers:{'Content-Type':'application/json'}});try{let res=response();await handler({url:'/insights/cms-test/',method:'GET'},res);assert.equal(res.code,200);assert.ok(res.body.includes('본문 내용'));res=response();await handler({url:'/insights/missing/',method:'GET'},res);assert.equal(res.code,404);}finally{global.fetch=fetchOriginal;}});
test('뉴스룸 카드는 공유 헤더가 아니라 뉴스룸 제목 아래 삽입된다',async()=>{const fetchOriginal=global.fetch;global.fetch=async()=>new Response(JSON.stringify([{...post,category:'newsroom'}]));try{const res=response();await handler({url:'/newsroom/',method:'GET'},res);assert.ok(res.body.indexOf('aria-label="최신 게시물"')>res.body.indexOf('newsroom-heading'));}finally{global.fetch=fetchOriginal;}});
