import test from 'node:test';import assert from 'node:assert/strict';import fs from 'node:fs';import crypto from 'node:crypto';
import handler from '../api/content.js';import {renderBlocks} from '../lib/content-render.mjs';import {validateTree,seoulDate} from '../lib/content-document.mjs';import {sortNewsroom,newsroomCard} from '../lib/newsroom.mjs';import {migratedRoutes} from '../lib/content-migrations.mjs';
const dir='content/cms-migrations/newsroom/';const inventory=JSON.parse(fs.readFileSync(dir+'inventory.json'));const rows=JSON.parse(fs.readFileSync(dir+'db-after.json'));
const res=()=>({headers:{},code:200,setHeader(k,v){this.headers[k]=v;},writeHead(n,h){this.code=n;Object.assign(this.headers,h);},end(s){this.body=s;}});
for(const item of inventory)test(item.slug+': complete original body and DB fields preserved',()=>{
 const p=JSON.parse(fs.readFileSync(dir+item.slug+'.json'));const db=rows.find(x=>x.slug===p.slug);assert.ok(db);validateTree(p.content.blocks);
 for(const [k,v] of Object.entries(p))if(k==='published_at')assert.equal(seoulDate(db[k]),item.date);else assert.deepEqual(db[k],v,k);
 const html=fs.readFileSync(dir+item.slug+'.html','utf8');assert.equal(crypto.createHash('sha256').update(html).digest('hex'),item.sha256);
 const body=html.match(/<article class="newsroom-detail container">([\s\S]*?)<\/article>/)[1].replace(/<header>[\s\S]*?<\/header>/,'').replace(/<a class="text-link newsroom-back"[\s\S]*?<\/a>/,'');
 const normalize=s=>s.replaceAll('&#39;',"'").replaceAll('&#x27;',"'").replace(/\srel="[^"]*"/g,'');assert.equal(normalize(renderBlocks(p.content.blocks)),normalize(body));
 for(const link of item.links)assert.ok(renderBlocks(p.content.blocks).includes(link.replaceAll('&','&amp;')));
});
test('news cards contain only image and full title, stable date ordering',()=>{const p=rows[0],h=newsroomCard(p);assert.ok(!/<time|자세히 보기|class="eyebrow"|<p>/.test(h));assert.ok(h.includes('/insights/press/'+p.slug+'/'));const same=[{slug:'b',published_at:'2020-01-01'},{slug:'a',published_at:'2020-01-01'},{slug:'c',published_at:'2021-01-01'}];assert.deepEqual(sortNewsroom(same).map(p=>p.slug),['c','a','b']);assert.equal(seoulDate('2026-10-01T15:00:00Z'),'2026-10-02');});
test('newsroom list deduplicates, hides unpublished migrations, and fails closed',async()=>{const before=global.fetch;try{global.fetch=async()=>new Response(JSON.stringify(rows.slice(0,2)));let r=res();await handler({url:'/newsroom/',method:'GET'},r);assert.equal((r.body.match(/class="newsroom-card"/g)||[]).length,2);assert.ok(!r.body.includes('newsroom-year'));assert.equal((r.body.match(new RegExp('href="/insights/press/'+rows[0].slug+'/"','g'))||[]).length,1);global.fetch=async()=>{throw new Error('test offline')};r=res();await handler({url:'/newsroom/',method:'GET'},r);assert.ok(!r.body.includes('class="newsroom-card"'));assert.ok(r.body.includes('현재 미디어자료를 불러오지 못했습니다'));}finally{global.fetch=before;}});
test('both migrated URL families never reveal static content when hidden',async()=>{const before=global.fetch;try{global.fetch=async()=>new Response('[]');for(const route of migratedRoutes.filter(x=>x.startsWith('/newsroom/')||x.startsWith('/insights/press/'))){const r=res();await handler({url:route,method:'GET'},r);assert.equal(r.code,404,route);}}finally{global.fetch=before;}});
test('all migrated news details retain original SEO, canonical and links',async()=>{const before=global.fetch;try{for(const p of rows){global.fetch=async u=>new Response(JSON.stringify(String(u).includes('post_assets')?[]:[p]));const r=res();await handler({url:'/insights/press/'+p.slug+'/',method:'GET'},r);assert.equal(r.code,200);const old=fs.readFileSync('.cms-runtime/insights/press/'+p.slug+'/index.html','utf8');for(const tag of old.matchAll(/<title>[\s\S]*?<\/title>|<meta[^>]+>|<link rel="canonical"[^>]+>|<script type="application\/ld\+json">[\s\S]*?<\/script>/g))assert.ok(r.body.includes(tag[0]),p.slug);assert.ok(r.body.includes(seoulDate(p.published_at)));}}finally{global.fetch=before;}});
test('original blog content snapshots remain preserved byte for byte',()=>{const inventory=JSON.parse(fs.readFileSync(dir+'blog-preservation.json'));for(const p of inventory.filter(x=>x.file.startsWith('content/')))assert.equal(crypto.createHash('sha256').update(fs.readFileSync(p.file)).digest('hex'),p.sha256,p.file);const backup=JSON.parse(fs.readFileSync('content/cms-migrations/gmk-note-review-20261003/manifest.json'));for(const [current,source] of [['content/gmk-notes.json','gmk-notes-original.json'],['content/note-edits/gmk-three-mushrooms.json','gmk-three-mushrooms-original.json']])assert.equal(crypto.createHash('sha256').update(fs.readFileSync(current)).digest('hex'),backup.find(x=>x.file===source).sha256,current);});
