const e=value=>String(value??'').replaceAll('&','&amp;').replaceAll('<','&lt;').replaceAll('>','&gt;').replaceAll('"','&quot;');
const origin='https://giunchan-website.guc2103m.chatgpt.site';
export const pressPath=p=>`/insights/press/${p.slug}/`;
export const sortPress=posts=>posts.map((p,i)=>({...p,_order:i})).sort((a,b)=>b.publishedAt.localeCompare(a.publishedAt)||a._order-b._order);
const notice='보도자료는 발표 당시의 연구·사업 현황과 기운찬의 공식 활동을 기록합니다. 과거 자료에 포함된 개발단계와 명칭은 현재 상태와 다를 수 있으므로 게시일과 현재 안내 내용을 함께 확인해 주세요.';
export function insightsContent(researchCards,posts){return `<section class="section" data-content-id="N01"><div class="container">
 <div class="insights-tabs" role="tablist" aria-label="인사이트 콘텐츠"><button id="research-tab" role="tab" aria-selected="true" aria-controls="research-panel" tabindex="0">연구자료</button><button id="press-tab" role="tab" aria-selected="false" aria-controls="press-panel" tabindex="-1">보도자료</button></div>
 <section id="research-panel" role="tabpanel" aria-labelledby="research-tab"><span id="research"></span><div class="insight-grid" id="article-list">${researchCards}</div><nav class="research-pagination" aria-label="연구자료 페이지" hidden></nav><p class="research-page-status" aria-live="polite"></p></section>
 <section id="press-panel" role="tabpanel" aria-labelledby="press-tab" hidden><h2 id="press">보도자료</h2><p>기운찬의 연구성과와 특허, 제품, 사업협력 및 주요 활동을 전합니다.</p><div class="press-grid">${sortPress(posts).map(p=>`<article class="press-card"><a href="${pressPath(p)}" aria-label="${e(p.title)} 자세히 보기"><div class="press-thumb"><img src="${e(p.image)}" alt="${e(p.thumbnailAlt)}" width="1200" height="675" loading="lazy" decoding="async"></div><div class="press-card-body"><time datetime="${e(p.publishedAt)}">${e(p.publishedAt)}</time><h3>${e(p.title)}</h3><p class="press-summary">${e(p.summary)}</p><p class="press-source">${e(p.publisher||p.relatedOrganizations?.join(', ')||p.author)}</p><span class="text-link">자세히 보기 →</span></div></a></article>`).join('')}</div><p class="press-notice">${notice}</p></section></div></section>`;}
export function pressDetail(p){const facts=[['관련 기관',p.relatedOrganizations?.join(', ')],['언론사·출처',p.publisher],['기자',p.reporter],['원 보도 제목',p.originalTitle],['관련 원료',p.relatedMaterial],['연구단계',p.researchStage]];const links=[...(p.sourceLinks||[])];if(p.originalArticleUrl&&!links.some(x=>x.url===p.originalArticleUrl))links.push({label:'외부 원문',url:p.originalArticleUrl});if(p.legacyUrl&&!links.some(x=>x.url===p.legacyUrl))links.push({label:'기존 기운찬 게시물',url:p.legacyUrl});return `<article class="press-detail container"><a class="text-link" href="/insights/#press">보도자료 목록으로 돌아가기 →</a><header><div class="press-dates"><time datetime="${e(p.publishedAt)}">게시일 ${e(p.publishedAt)}</time>${p.updatedAt?`<time datetime="${e(p.updatedAt)}">최종 수정일 ${e(p.updatedAt)}</time>`:''}</div><h1>${e(p.title)}</h1><p class="press-lead">${e(p.answer)}</p><p>${e(p.author)}${p.reviewer?` · 자료 검토: ${e(p.reviewer)}`:''}</p></header><img class="press-cover" src="${e(p.image)}" alt="${e(p.thumbnailAlt)}" width="1200" height="675"><dl class="press-facts">${facts.filter(([,v])=>v).map(([k,v])=>`<div><dt>${k}</dt><dd>${e(v)}</dd></div>`).join('')}</dl>${p.sections.map(s=>`<section><h2>${e(s.title)}</h2><p>${e(s.body)}</p></section>`).join('')}<section><h2>참고자료와 출처</h2><ul>${links.map(l=>`<li><a href="${e(l.url)}" target="_blank" rel="noopener noreferrer">${e(l.label)} ↗</a></li>`).join('')}</ul></section>${p.disclaimer?`<p class="press-notice">${e(p.disclaimer)}</p>`:''}<p class="press-notice">${notice}</p><a class="text-link" href="/insights/#press">보도자료 목록으로 돌아가기 →</a></article>`;}
export function pressMetadata(p){const url=origin+pressPath(p);const structured={'@context':'https://schema.org','@type':'NewsArticle',headline:p.title,description:p.summary,datePublished:p.publishedAt,...(p.updatedAt?{dateModified:p.updatedAt}:{}),image:[origin+p.image],author:{'@type':'Organization',name:p.author},publisher:{'@type':'Organization',name:'주식회사 기운찬'},mainEntityOfPage:url};return `<link rel="canonical" href="${url}"><script type="application/ld+json">${JSON.stringify(structured).replaceAll('<','\\u003c')}</script>`;}
