'use client';
import {useEffect,useMemo,useState} from 'react';
import Image from 'next/image';
import type {ContentEntry} from '@/lib/content-data';
export type ContentListEntry=Pick<ContentEntry,'title'|'slug'|'contentType'|'category'|'summary'|'updatedAt'|'thumbnail'|'thumbnailAlt'|'tags'|'relatedEntities'|'relatedOrganizations'|'featured'|'readingTime'|'relatedMaterial'>;
const normalize=(s:string)=>s.toLowerCase().replaceAll('®','').replace(/\s/g,'');
export function ContentExplorer({entries,type,categories}:{entries:ContentListEntry[];type:'insight'|'newsroom';categories:string[]}){
 const [query,setQuery]=useState(''),[category,setCategory]=useState('전체'),[page,setPage]=useState(1);const perPage=type==='newsroom'?6:9;
 useEffect(()=>{const p=new URLSearchParams(location.search);queueMicrotask(()=>{setQuery(p.get('q')||'');setCategory(p.get('category')||'전체');setPage(Math.max(1,Number(p.get('page'))||1))})},[]);
 const results=useMemo(()=>entries.filter(e=>{const hay=normalize([e.title,e.summary,e.category,...e.tags,...e.relatedEntities,...(e.relatedOrganizations||[])].join(' '));return(category==='전체'||e.category===category)&&(!query||hay.includes(normalize(query)))}),[entries,query,category]);
 const pages=Math.max(1,Math.ceil(results.length/perPage));useEffect(()=>{if(page>pages)queueMicrotask(()=>setPage(pages))},[page,pages]);
 const update=(q:string,c:string,p:number)=>{const next=new URLSearchParams();if(q)next.set('q',q);if(c!=='전체')next.set('category',c);if(p>1)next.set('page',String(p));history.replaceState(null,'',`${location.pathname}${next.size?'?'+next:''}`)};
 const setQ=(v:string)=>{setQuery(v);setPage(1);update(v,category,1)},setC=(v:string)=>{setCategory(v);setPage(1);update(query,v,1)},setP=(v:number)=>{setPage(v);update(query,category,v);document.getElementById('content-results')?.scrollIntoView({behavior:'smooth'})};
 const visible=results.slice((page-1)*perPage,page*perPage);
 return <section className="content-explorer" aria-labelledby="content-results-title"><div className="content-tools"><div className="content-search"><label htmlFor={`${type}-search`}>{type==='insight'?'인사이트 검색':'뉴스룸 검색'}</label><input id={`${type}-search`} type="search" value={query} onChange={e=>setQ(e.target.value)} placeholder={type==='insight'?'GMK®, 균사체, 추출물, 특허 등 궁금한 내용을 검색하세요':'연구, 특허, 제품, 협력 등 기운찬 소식을 검색하세요'}/></div><div className="content-filters" aria-label="카테고리 필터">{categories.map(c=><button key={c} type="button" aria-pressed={category===c} onClick={()=>setC(c)}>{c}</button>)}</div>{(query||category!=='전체')&&<button className="filter-reset" onClick={()=>{setQuery('');setCategory('전체');setPage(1);update('','전체',1)}}>전체 초기화</button>}</div><div id="content-results" className="content-result-head"><h2 id="content-results-title">{type==='insight'?'전체 인사이트':'전체 뉴스'}</h2><p aria-live="polite">{results.length}개의 글</p></div>{visible.length?<div className="content-grid">{visible.map((item,i)=><article className={item.featured&&page===1&&i===0?'content-card featured':'content-card'} key={item.slug}><a href={`/${type}/${item.slug}`}><Image src={item.thumbnail} alt={item.thumbnailAlt} width={800} height={450} unoptimized/><div><span>{item.category}</span><time dateTime={item.updatedAt}>{type==='insight'?'최종 수정 ':''}{item.updatedAt.replaceAll('-','.')}</time><h3>{item.title}</h3><p>{item.summary}</p><small>{type==='insight'?`${item.readingTime}분 읽기`:(item.relatedOrganizations?.[0]||item.relatedMaterial||'주식회사 기운찬')}</small><b>{type==='insight'?'자세히 읽기':'소식 자세히 보기'} →</b></div></a></article>)}</div>:<div className="content-empty">검색 결과가 없습니다. 다른 검색어를 입력하거나 전체 {type==='insight'?'인사이트':'뉴스'}를 확인해 주세요.</div>}{pages>1&&<nav className="content-pagination" aria-label="페이지 이동"><button disabled={page===1} onClick={()=>setP(page-1)}>이전</button>{Array.from({length:pages},(_,i)=>i+1).map(p=><button key={p} aria-current={p===page?'page':undefined} onClick={()=>setP(p)}>{p}</button>)}<button disabled={page===pages} onClick={()=>setP(page+1)}>다음</button></nav>}</section>
}
