'use client';
import Image from 'next/image';
import { useEffect, useState } from 'react';
import { usePathname } from 'next/navigation';
import { Menu, X, ChevronDown } from 'lucide-react';
import { nav, contactHref, inquiryTypes } from '@/lib/site-data';

export function Header(){
 const [open,setOpen]=useState(false);
 const pathname=usePathname();
 const [scrolled,setScrolled]=useState(false);
 useEffect(()=>{const update=()=>setScrolled(window.scrollY>28);const frame=requestAnimationFrame(update);window.addEventListener('scroll',update,{passive:true});return()=>{cancelAnimationFrame(frame);window.removeEventListener('scroll',update)}},[]);
 const ko:Record<string,string>={COMPANY:'회사',TECHNOLOGY:'기술',BUSINESS:'사업',BRANDS:'브랜드',INSIGHT:'인사이트',NEWSROOM:'뉴스'};
 return <header className={'site-header'+(scrolled?' is-scrolled':'')}><div className="shell nav-row"><a className="brand" href="/" aria-label="기운찬 홈"><Image src="/assets/giunchan-logo-trimmed.png" alt="주식회사 기운찬" width={2465} height={848} priority unoptimized/></a><nav className="desktop-nav" aria-label="주 메뉴">{nav.map(item=>{const active=pathname===item.href||pathname.startsWith(item.href+'/');return <div className={'nav-item'+(active?' is-active':'')} key={item.href}><a href={item.href} aria-current={active?'page':undefined}><span>{item.label}</span><small>{ko[item.label]}</small></a>{item.children.length>0&&<div className="mega"><b>{item.label}</b>{item.children.map(child=><a href={child.href} key={child.href}>{child.label}<span>→</span></a>)}</div>}</div>})}</nav><div className="nav-actions"><a className="contact-pill" href={contactHref}>문의하기</a><button className="menu-toggle" aria-label={open?'메뉴 닫기':'메뉴 열기'} aria-expanded={open} aria-controls="mobile-navigation" onClick={()=>setOpen(!open)}>{open?<X/>:<Menu/>}</button></div></div>{open&&<nav id="mobile-navigation" className="mobile-nav" aria-label="모바일 주 메뉴">{nav.map(item=>item.children.length?<details key={item.href}><summary>{item.label}<ChevronDown size={16}/></summary><a href={item.href} onClick={()=>setOpen(false)}>{item.label} 전체 보기</a>{item.children.map(child=><a href={child.href} key={child.href} onClick={()=>setOpen(false)}>{child.label}</a>)}</details>:<a className="mobile-direct" key={item.href} href={item.href} onClick={()=>setOpen(false)}>{item.label}</a>)}<a className="button dark mobile-inquiry" href={contactHref} onClick={()=>setOpen(false)}>문의하기</a></nav>}</header>
}
export function FAQ({items}:{items:{q:string;a:string;href?:string;link?:string}[]}){
 const [open,setOpen]=useState<number|null>(null);
 return <div className="faq">{items.map((item,index)=>{const expanded=open===index;const panelId=`faq-panel-${index}`;return <section className="faq-item" key={item.q}><h3><button type="button" aria-expanded={expanded} aria-controls={panelId} onClick={()=>setOpen(expanded?null:index)}><span>{item.q}</span><b aria-hidden="true">{expanded?'−':'+'}</b></button></h3><div id={panelId} hidden={!expanded}><p>{item.a}</p>{item.href&&<a href={item.href}>{item.link} →</a>}</div></section>})}</div>
}
export function ContactForm(){
 const [type,setType]=useState('');
 useEffect(()=>{const selected=new URLSearchParams(window.location.search).get('inquiry');if(selected&&inquiryTypes.includes(selected))queueMicrotask(()=>setType(selected))},[]);
 return <form className="contact-form" onSubmit={e=>e.preventDefault()} aria-describedby="contact-form-note"><div className="field full"><label htmlFor="inquiry-type">문의 유형 *</label><select id="inquiry-type" required value={type} onChange={e=>setType(e.target.value)}><option value="" disabled>문의 유형을 선택해 주세요</option>{inquiryTypes.map(x=><option key={x}>{x}</option>)}</select></div><div className="field"><label htmlFor="company-name">회사명 *</label><input id="company-name" autoComplete="organization" required/></div><div className="field"><label htmlFor="person-name">담당자명 *</label><input id="person-name" autoComplete="name" required/></div><div className="field"><label htmlFor="email">이메일 *</label><input id="email" type="email" autoComplete="email" required/></div><div className="field"><label htmlFor="phone">연락처 *</label><input id="phone" type="tel" autoComplete="tel" required/></div><div className="field"><label htmlFor="interest">관심 원료 또는 제품</label><input id="interest"/></div><div className="field"><label htmlFor="product-type">개발하려는 제품 유형</label><input id="product-type"/></div><div className="field"><label htmlFor="quantity">예상 수량</label><input id="quantity" placeholder="미정인 경우 ‘미정’ 입력"/></div><div className="field"><label htmlFor="schedule">희망 일정</label><input id="schedule" placeholder="예: 2027년 상반기 또는 미정"/></div><div className="field full"><label htmlFor="market">판매지역</label><select id="market" defaultValue=""><option value="">선택해 주세요</option><option>국내 판매</option><option>수출</option><option>국내 판매 및 수출</option><option>미정</option></select></div><div className="field full"><label htmlFor="message">문의 내용 *</label><textarea id="message" rows={7} required/></div><div className="field full consent"><label><input type="checkbox"/> 개인정보 수집 안내를 확인했습니다</label></div><p id="contact-form-note" className="full form-note">온라인 전송 기능은 현재 제공하지 않습니다. 작성할 내용을 정리한 뒤 이메일 또는 전화로 문의해 주세요.</p><div className="inline-actions full"><a className="button orange" href={'mailto:guc2203@guc.co.kr?subject='+encodeURIComponent(type||'사업 문의')}>이메일로 문의하기</a><a className="text-link" href="tel:0415792203">041-579-2203 전화 문의</a></div></form>
}

